function [A] = A_matrix(t_init, t_final)
%UNTITLED2 Summary of this function D = blkdiag(A, A, A);goes here
%   Detailed explanation goes here
Ax = [position_time(t_init)';...
     velocity_time(t_init)';...
     acceleration_time(t_init)';...
     jerk_time(t_init)';
     snap_time(t_init)';
     position_time(t_final)';...
     velocity_time(t_final)';...
     acceleration_time(t_final)'
     jerk_time(t_final)'
     snap_time(t_final)'];
A = blkdiag(Ax, Ax, Ax);
end