/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[4] = {1., 0., 0., 0.};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[13],i1[],i2[],i3[17])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+25, *w20=w+42, *w21=w+45, *w22=w+58, *w23=w+61, *w24=w+70, *w25=w+74, *w26=w+78, *w27=w+82, *w28=w+86, *w29=w+90, *w30=w+94, *w31=w+110, *w32=w+126, *w33=w+129, *w34=w+132;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #28: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #29: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #30: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #31: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #32: @17 = input[0][11] */
  w17 = arg[0] ? arg[0][11] : 0;
  /* #33: @18 = input[0][12] */
  w18 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @15, @16, @17, @18) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 2.5 */
  w2 = 2.5000000000000000e+00;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 10 */
  w2 = 10.;
  /* #48: @3 = 0 */
  w3 = 0.;
  /* #49: @24 = [1, 0, 0, 0] */
  casadi_copy(casadi_c0, 4, w24);
  /* #50: @4 = 0 */
  w4 = 0.;
  /* #51: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #52: @26 = horzcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @26 = @26' */
  /* #54: @5 = (-@9) */
  w5 = (- w9 );
  /* #55: @6 = (-@10) */
  w6 = (- w10 );
  /* #56: @27 = horzcat(@5, @8, @11, @6) */
  rr=w27;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w6;
  /* #57: @27 = @27' */
  /* #58: @11 = (-@11) */
  w11 = (- w11 );
  /* #59: @28 = horzcat(@6, @11, @8, @9) */
  rr=w28;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w8;
  *rr++ = w9;
  /* #60: @28 = @28' */
  /* #61: @29 = horzcat(@11, @10, @5, @8) */
  rr=w29;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w8;
  /* #62: @29 = @29' */
  /* #63: @30 = horzcat(@26, @27, @28, @29) */
  rr=w30;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  /* #64: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #65: @26 = @21[6:10] */
  for (rr=w26, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #66: @25 = mac(@31,@26,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w31+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #67: @11 = @25[0] */
  for (rr=(&w11), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #68: @4 = (@4<@11) */
  w4  = (w4<w11);
  /* #69: @26 = (@4?@25:0) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++)  = (w4?(*cs++):0);
  /* #70: @11 = (!@4) */
  w11 = (! w4 );
  /* #71: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #72: @25 = (@11?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w11?(*cs++):0);
  /* #73: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #74: @24 = (@24-@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #75: @26 = @24' */
  casadi_copy(w24, 4, w26);
  /* #76: @3 = mac(@26,@24,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #77: @2 = (@2*@3) */
  w2 *= w3;
  /* #78: @0 = (@0+@2) */
  w0 += w2;
  /* #79: @2 = 0 */
  w2 = 0.;
  /* #80: @22 = @21[10:13] */
  for (rr=w22, ss=w21+10; ss!=w21+13; ss+=1) *rr++ = *ss;
  /* #81: @32 = @22' */
  casadi_copy(w22, 3, w32);
  /* #82: @2 = mac(@32,@22,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0+@2) */
  w0 += w2;
  /* #84: @2 = 0 */
  w2 = 0.;
  /* #85: @32 = @21[3:6] */
  for (rr=w32, ss=w21+3; ss!=w21+6; ss+=1) *rr++ = *ss;
  /* #86: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #87: @2 = mac(@33,@32,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #88: @0 = (@0+@2) */
  w0 += w2;
  /* #89: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #90: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #91: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #92: (@21[3:6] += @32) */
  for (rr=w21+3, ss=w32; rr!=w21+6; rr+=1) *rr += *ss++;
  /* #93: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #94: (@21[10:13] += @22) */
  for (rr=w21+10, ss=w22; rr!=w21+13; rr+=1) *rr += *ss++;
  /* #95: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #96: @0 = 1 */
  w0 = 1.;
  /* #97: @11 = (@11?@0:0) */
  w11  = (w11?w0:0);
  /* #98: @0 = 10 */
  w0 = 10.;
  /* #99: @25 = (@0*@24) */
  for (i=0, rr=w25, cs=w24; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #100: @24 = @24' */
  /* #101: @24 = (@0*@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #102: @24 = @24' */
  /* #103: @25 = (@25+@24) */
  for (i=0, rr=w25, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #104: @24 = (@11*@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #105: @11 = 1 */
  w11 = 1.;
  /* #106: @4 = (@4?@11:0) */
  w4  = (w4?w11:0);
  /* #107: @25 = (@4*@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #108: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #109: @26 = mac(@30,@24,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w30+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #110: (@21[6:10] += @26) */
  for (rr=w21+6, ss=w26; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #111: @1 = @1' */
  /* #112: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #113: @20 = @20' */
  /* #114: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #115: @22 = mac(@20,@34,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #116: @22 = @22' */
  /* #117: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #118: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #119: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #120: output[1][0] = @21 */
  casadi_copy(w21, 13, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 141;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
