/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s7[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s8[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s10[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s11[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s12[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s13[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s14[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s15[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s16[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s17[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[61] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s19[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s20[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s21[3] = {0, 0, 0};
static const casadi_int casadi_s22[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s23[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s24[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[],i3[17])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+71, *w26=w+75, *w27=w+79, *w28=w+95, *w29=w+99, *w30=w+103, *w31=w+119, *w32=w+128, *w33=w+169, *w37=w+178, *w38=w+189, *w49=w+191;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 4.5 */
  w2 = 4.5000000000000000e+00;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #49: @25 = @19[13:17] */
  for (rr=w25, ss=w19+13; ss!=w19+17; ss+=1) *rr++ = *ss;
  /* #50: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #51: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #52: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #53: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #54: @26 = vertcat(@3, @4, @5, @6) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #55: @25 = (@25-@26) */
  for (i=0, rr=w25, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #56: @26 = @25' */
  casadi_copy(w25, 4, w26);
  /* #57: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #58: @3 = 0.671141 */
  w3 = 6.7114093959731547e-01;
  /* #59: (@27[0] = @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #60: @3 = 600 */
  w3 = 600.;
  /* #61: (@27[5] = @3) */
  for (rr=w27+5, ss=(&w3); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #62: @3 = 600 */
  w3 = 600.;
  /* #63: (@27[10] = @3) */
  for (rr=w27+10, ss=(&w3); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #64: @3 = 600 */
  w3 = 600.;
  /* #65: (@27[15] = @3) */
  for (rr=w27+15, ss=(&w3); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #66: @24 = mac(@26,@27,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #67: @2 = mac(@24,@25,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = (@0+@2) */
  w0 += w2;
  /* #69: @2 = 10 */
  w2 = 10.;
  /* #70: @3 = 1 */
  w3 = 1.;
  /* #71: @4 = 0 */
  w4 = 0.;
  /* #72: @26 = @19[6:10] */
  for (rr=w26, ss=w19+6; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #73: @28 = @26' */
  casadi_copy(w26, 4, w28);
  /* #74: @29 = @21[6:10] */
  for (rr=w29, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #75: @4 = mac(@28,@29,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #76: @5 = fabs(@4) */
  w5 = fabs( w4 );
  /* #77: @3 = (@3-@5) */
  w3 -= w5;
  /* #78: @2 = (@2*@3) */
  w2 *= w3;
  /* #79: @0 = (@0+@2) */
  w0 += w2;
  /* #80: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #81: @24 = @24' */
  /* #82: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #83: @25 = @25' */
  /* #84: @30 = @27' */
  for (i=0, rr=w30, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #85: @28 = mac(@25,@30,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #86: @28 = @28' */
  /* #87: @24 = (@24+@28) */
  for (i=0, rr=w24, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #88: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #89: {@0, @2, @3, @5} = vertsplit(@24) */
  w0 = w24[0];
  w2 = w24[1];
  w3 = w24[2];
  w5 = w24[3];
  /* #90: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #91: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #92: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #93: output[1][3] = @5 */
  if (res[1]) res[1][3] = w5;
  /* #94: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #95: @5 = -10 */
  w5 = -10.;
  /* #96: @4 = sign(@4) */
  w4 = casadi_sign( w4 );
  /* #97: @5 = (@5*@4) */
  w5 *= w4;
  /* #98: @26 = (@26*@5) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) *= w5;
  /* #99: (@21[6:10] += @26) */
  for (rr=w21+6, ss=w26; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #100: @1 = @1' */
  /* #101: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #102: @20 = @20' */
  /* #103: @31 = @23' */
  for (i=0, rr=w31, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #104: @22 = mac(@20,@31,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #105: @22 = @22' */
  /* #106: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #107: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #108: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #109: {@5, @4, @3, @2, @0, @6, @7, @8, @9, @10, @11, @12, @13} = vertsplit(@21) */
  w5 = w21[0];
  w4 = w21[1];
  w3 = w21[2];
  w2 = w21[3];
  w0 = w21[4];
  w6 = w21[5];
  w7 = w21[6];
  w8 = w21[7];
  w9 = w21[8];
  w10 = w21[9];
  w11 = w21[10];
  w12 = w21[11];
  w13 = w21[12];
  /* #110: output[1][4] = @5 */
  if (res[1]) res[1][4] = w5;
  /* #111: output[1][5] = @4 */
  if (res[1]) res[1][5] = w4;
  /* #112: output[1][6] = @3 */
  if (res[1]) res[1][6] = w3;
  /* #113: output[1][7] = @2 */
  if (res[1]) res[1][7] = w2;
  /* #114: output[1][8] = @0 */
  if (res[1]) res[1][8] = w0;
  /* #115: output[1][9] = @6 */
  if (res[1]) res[1][9] = w6;
  /* #116: output[1][10] = @7 */
  if (res[1]) res[1][10] = w7;
  /* #117: output[1][11] = @8 */
  if (res[1]) res[1][11] = w8;
  /* #118: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  /* #119: output[1][13] = @10 */
  if (res[1]) res[1][13] = w10;
  /* #120: output[1][14] = @11 */
  if (res[1]) res[1][14] = w11;
  /* #121: output[1][15] = @12 */
  if (res[1]) res[1][15] = w12;
  /* #122: output[1][16] = @13 */
  if (res[1]) res[1][16] = w13;
  /* #123: @32 = zeros(17x17,41nz) */
  casadi_clear(w32, 41);
  /* #124: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #125: @33 = ones(17x1,9nz) */
  casadi_fill(w33, 9, 1.);
  /* #126: {@13, NULL, NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@33) */
  w13 = w33[0];
  w12 = w33[1];
  /* #127: @34 = 00 */
  /* #128: @35 = 00 */
  /* #129: @36 = 00 */
  /* #130: @11 = vertcat(@13, @34, @35, @36) */
  rr=(&w11);
  *rr++ = w13;
  /* #131: @11 = (-@11) */
  w11 = (- w11 );
  /* #132: @13 = @11' */
  casadi_copy((&w11), 1, (&w13));
  /* #133: @26 = mac(@13,@27,@26) */
  casadi_mtimes((&w13), casadi_s2, w27, casadi_s1, w26, casadi_s0, w, 0);
  /* #134: @26 = @26' */
  /* #135: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #136: @11 = @11' */
  /* #137: @24 = mac(@11,@30,@24) */
  casadi_mtimes((&w11), casadi_s2, w30, casadi_s1, w24, casadi_s0, w, 0);
  /* #138: @24 = @24' */
  /* #139: @26 = (@26+@24) */
  for (i=0, rr=w26, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #140: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #141: {@11, @13, @10, @9} = vertsplit(@26) */
  w11 = w26[0];
  w13 = w26[1];
  w10 = w26[2];
  w9 = w26[3];
  /* #142: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #143: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #144: @8 = @12[0] */
  for (rr=(&w8), ss=(&w12)+0; ss!=(&w12)+1; ss+=1) *rr++ = *ss;
  /* #145: @8 = (-@8) */
  w8 = (- w8 );
  /* #146: @12 = @8' */
  casadi_copy((&w8), 1, (&w12));
  /* #147: @1 = mac(@12,@23,@1) */
  casadi_mtimes((&w12), casadi_s5, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #148: @1 = @1' */
  /* #149: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #150: @8 = @8' */
  /* #151: @22 = mac(@8,@31,@22) */
  casadi_mtimes((&w8), casadi_s5, w31, casadi_s4, w22, casadi_s3, w, 0);
  /* #152: @22 = @22' */
  /* #153: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #154: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #155: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #156: {@8, @12, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17} = vertsplit(@21) */
  w8 = w21[0];
  w12 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w0 = w21[4];
  w2 = w21[5];
  w3 = w21[6];
  w4 = w21[7];
  w5 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #157: @19 = vertcat(@11, @13, @10, @9, @8, @12, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #158: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #159: (@32[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @37) */
  for (cii=casadi_s7, rr=w32, ss=w37; cii!=casadi_s7+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #160: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #161: (@32[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @37) */
  for (cii=casadi_s8, rr=w32, ss=w37; cii!=casadi_s8+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #162: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #163: @34 = 00 */
  /* #164: @1 = ones(17x1,3nz) */
  casadi_fill(w1, 3, 1.);
  /* #165: {NULL, @11, NULL, NULL, NULL, @13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w11 = w1[0];
  w13 = w1[1];
  /* #166: @35 = 00 */
  /* #167: @36 = 00 */
  /* #168: @10 = vertcat(@34, @11, @35, @36) */
  rr=(&w10);
  *rr++ = w11;
  /* #169: @10 = (-@10) */
  w10 = (- w10 );
  /* #170: @11 = @10' */
  casadi_copy((&w10), 1, (&w11));
  /* #171: @26 = mac(@11,@27,@26) */
  casadi_mtimes((&w11), casadi_s9, w27, casadi_s1, w26, casadi_s0, w, 0);
  /* #172: @26 = @26' */
  /* #173: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #174: @10 = @10' */
  /* #175: @24 = mac(@10,@30,@24) */
  casadi_mtimes((&w10), casadi_s9, w30, casadi_s1, w24, casadi_s0, w, 0);
  /* #176: @24 = @24' */
  /* #177: @26 = (@26+@24) */
  for (i=0, rr=w26, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #178: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #179: {@10, @11, @9, @8} = vertsplit(@26) */
  w10 = w26[0];
  w11 = w26[1];
  w9 = w26[2];
  w8 = w26[3];
  /* #180: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #181: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #182: @12 = @13[0] */
  for (rr=(&w12), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #183: @12 = (-@12) */
  w12 = (- w12 );
  /* #184: @13 = @12' */
  casadi_copy((&w12), 1, (&w13));
  /* #185: @1 = mac(@13,@23,@1) */
  casadi_mtimes((&w13), casadi_s10, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #186: @1 = @1' */
  /* #187: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #188: @12 = @12' */
  /* #189: @22 = mac(@12,@31,@22) */
  casadi_mtimes((&w12), casadi_s10, w31, casadi_s4, w22, casadi_s3, w, 0);
  /* #190: @22 = @22' */
  /* #191: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #192: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #193: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #194: {@12, @13, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17} = vertsplit(@21) */
  w12 = w21[0];
  w13 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w0 = w21[4];
  w2 = w21[5];
  w3 = w21[6];
  w4 = w21[7];
  w5 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #195: @19 = vertcat(@10, @11, @9, @8, @12, @13, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #196: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #197: (@32[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @37) */
  for (cii=casadi_s11, rr=w32, ss=w37; cii!=casadi_s11+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #198: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #199: (@32[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @37) */
  for (cii=casadi_s12, rr=w32, ss=w37; cii!=casadi_s12+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #200: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #201: @34 = 00 */
  /* #202: @35 = 00 */
  /* #203: @1 = ones(17x1,3nz) */
  casadi_fill(w1, 3, 1.);
  /* #204: {NULL, NULL, @10, NULL, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w10 = w1[0];
  w11 = w1[1];
  /* #205: @36 = 00 */
  /* #206: @9 = vertcat(@34, @35, @10, @36) */
  rr=(&w9);
  *rr++ = w10;
  /* #207: @9 = (-@9) */
  w9 = (- w9 );
  /* #208: @10 = @9' */
  casadi_copy((&w9), 1, (&w10));
  /* #209: @26 = mac(@10,@27,@26) */
  casadi_mtimes((&w10), casadi_s13, w27, casadi_s1, w26, casadi_s0, w, 0);
  /* #210: @26 = @26' */
  /* #211: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #212: @9 = @9' */
  /* #213: @24 = mac(@9,@30,@24) */
  casadi_mtimes((&w9), casadi_s13, w30, casadi_s1, w24, casadi_s0, w, 0);
  /* #214: @24 = @24' */
  /* #215: @26 = (@26+@24) */
  for (i=0, rr=w26, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #216: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #217: {@9, @10, @8, @12} = vertsplit(@26) */
  w9 = w26[0];
  w10 = w26[1];
  w8 = w26[2];
  w12 = w26[3];
  /* #218: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #219: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #220: @13 = @11[0] */
  for (rr=(&w13), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #221: @13 = (-@13) */
  w13 = (- w13 );
  /* #222: @11 = @13' */
  casadi_copy((&w13), 1, (&w11));
  /* #223: @1 = mac(@11,@23,@1) */
  casadi_mtimes((&w11), casadi_s14, w23, casadi_s4, w1, casadi_s3, w, 0);
  /* #224: @1 = @1' */
  /* #225: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #226: @13 = @13' */
  /* #227: @22 = mac(@13,@31,@22) */
  casadi_mtimes((&w13), casadi_s14, w31, casadi_s4, w22, casadi_s3, w, 0);
  /* #228: @22 = @22' */
  /* #229: @1 = (@1+@22) */
  for (i=0, rr=w1, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #230: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #231: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #232: {@13, @11, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17} = vertsplit(@21) */
  w13 = w21[0];
  w11 = w21[1];
  w7 = w21[2];
  w6 = w21[3];
  w0 = w21[4];
  w2 = w21[5];
  w3 = w21[6];
  w4 = w21[7];
  w5 = w21[8];
  w14 = w21[9];
  w15 = w21[10];
  w16 = w21[11];
  w17 = w21[12];
  /* #233: @19 = vertcat(@9, @10, @8, @12, @13, @11, @7, @6, @0, @2, @3, @4, @5, @14, @15, @16, @17) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #234: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #235: (@32[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @37) */
  for (cii=casadi_s15, rr=w32, ss=w37; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #236: @37 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s6, rr=w37, ss=w19; cii!=casadi_s6+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #237: (@32[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @37) */
  for (cii=casadi_s16, rr=w32, ss=w37; cii!=casadi_s16+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #238: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #239: @34 = 00 */
  /* #240: @35 = 00 */
  /* #241: @36 = 00 */
  /* #242: @38 = ones(17x1,2nz) */
  casadi_fill(w38, 2, 1.);
  /* #243: {NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@38) */
  w9 = w38[0];
  /* #244: @10 = vertcat(@34, @35, @36, @9) */
  rr=(&w10);
  *rr++ = w9;
  /* #245: @10 = (-@10) */
  w10 = (- w10 );
  /* #246: @9 = @10' */
  casadi_copy((&w10), 1, (&w9));
  /* #247: @26 = mac(@9,@27,@26) */
  casadi_mtimes((&w9), casadi_s17, w27, casadi_s1, w26, casadi_s0, w, 0);
  /* #248: @26 = @26' */
  /* #249: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #250: @10 = @10' */
  /* #251: @24 = mac(@10,@30,@24) */
  casadi_mtimes((&w10), casadi_s17, w30, casadi_s1, w24, casadi_s0, w, 0);
  /* #252: @24 = @24' */
  /* #253: @26 = (@26+@24) */
  for (i=0, rr=w26, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #254: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #255: {@10, @9, @8, @12} = vertsplit(@26) */
  w10 = w26[0];
  w9 = w26[1];
  w8 = w26[2];
  w12 = w26[3];
  /* #256: @34 = 00 */
  /* #257: @35 = 00 */
  /* #258: @36 = 00 */
  /* #259: @39 = 00 */
  /* #260: @40 = 00 */
  /* #261: @41 = 00 */
  /* #262: @42 = 00 */
  /* #263: @43 = 00 */
  /* #264: @44 = 00 */
  /* #265: @45 = 00 */
  /* #266: @46 = 00 */
  /* #267: @47 = 00 */
  /* #268: @48 = 00 */
  /* #269: @26 = vertcat(@10, @9, @8, @12, @34, @35, @36, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48) */
  rr=w26;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w8;
  *rr++ = w12;
  /* #270: @24 = @26[:4] */
  for (rr=w24, ss=w26+0; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #271: (@32[12:16] = @24) */
  for (rr=w32+12, ss=w24; rr!=w32+16; rr+=1) *rr = *ss++;
  /* #272: @24 = @26[:4] */
  for (rr=w24, ss=w26+0; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #273: (@32[3:19:4] = @24) */
  for (rr=w32+3, ss=w24; rr!=w32+19; rr+=4) *rr = *ss++;
  /* #274: @49 = @32' */
  casadi_trans(w32,casadi_s18, w49, casadi_s18, iw);
  /* #275: output[2][0] = @49 */
  casadi_copy(w49, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s20;
    case 2: return casadi_s21;
    case 3: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s22;
    case 2: return casadi_s18;
    case 3: return casadi_s21;
    case 4: return casadi_s24;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 232;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
