/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s38 CASADI_PREFIX(s38)
#define casadi_s39 CASADI_PREFIX(s39)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s40 CASADI_PREFIX(s40)
#define casadi_s41 CASADI_PREFIX(s41)
#define casadi_s42 CASADI_PREFIX(s42)
#define casadi_s43 CASADI_PREFIX(s43)
#define casadi_s44 CASADI_PREFIX(s44)
#define casadi_s45 CASADI_PREFIX(s45)
#define casadi_s46 CASADI_PREFIX(s46)
#define casadi_s47 CASADI_PREFIX(s47)
#define casadi_s48 CASADI_PREFIX(s48)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[11] = {8, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[15] = {4, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[11] = {8, 4, 0, 1, 2, 3, 4, 4, 5, 6, 7};
static const casadi_int casadi_s4[15] = {4, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[8] = {0, 4, 8, 12, 16, 24, 32, 40};
static const casadi_int casadi_s8[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s9[11] = {8, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s10[15] = {4, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 1, 0, 3, 2};
static const casadi_int casadi_s11[11] = {8, 4, 0, 1, 2, 3, 4, 5, 4, 7, 6};
static const casadi_int casadi_s12[15] = {4, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s13[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 0, 3, 2, 5, 4, 7, 6};
static const casadi_int casadi_s14[8] = {1, 5, 9, 13, 17, 25, 33, 41};
static const casadi_int casadi_s15[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s16[11] = {8, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s17[15] = {4, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 2, 3, 0, 1};
static const casadi_int casadi_s18[11] = {8, 4, 0, 1, 2, 3, 4, 6, 7, 4, 5};
static const casadi_int casadi_s19[15] = {4, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s20[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 0, 1, 6, 7, 4, 5};
static const casadi_int casadi_s21[8] = {2, 6, 10, 14, 18, 26, 34, 42};
static const casadi_int casadi_s22[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s23[11] = {8, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s24[15] = {4, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 3, 2, 1, 0};
static const casadi_int casadi_s25[11] = {8, 4, 0, 1, 2, 3, 4, 7, 6, 5, 4};
static const casadi_int casadi_s26[15] = {4, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s27[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 3, 2, 1, 0, 7, 6, 5, 4};
static const casadi_int casadi_s28[8] = {3, 7, 11, 15, 19, 27, 35, 43};
static const casadi_int casadi_s29[15] = {8, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 4, 5, 6, 7};
static const casadi_int casadi_s30[15] = {8, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s31[15] = {8, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 5, 4, 7, 6};
static const casadi_int casadi_s32[15] = {8, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s33[15] = {8, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 6, 7, 4, 5};
static const casadi_int casadi_s34[15] = {8, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s35[15] = {8, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 7, 6, 5, 4};
static const casadi_int casadi_s36[15] = {8, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s37[59] = {8, 8, 0, 8, 16, 24, 32, 36, 40, 44, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7};
static const casadi_int casadi_s38[59] = {8, 8, 0, 4, 8, 12, 16, 24, 32, 40, 48, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s39[5] = {8, 1, 0, 1, 1};
static const casadi_int casadi_s40[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s41[5] = {8, 1, 0, 1, 2};
static const casadi_int casadi_s42[5] = {8, 1, 0, 1, 3};
static const casadi_int casadi_s43[5] = {8, 1, 0, 1, 5};
static const casadi_int casadi_s44[5] = {8, 1, 0, 1, 6};
static const casadi_int casadi_s45[5] = {8, 1, 0, 1, 7};
static const casadi_int casadi_s46[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s47[3] = {0, 0, 0};
static const casadi_int casadi_s48[57] = {8, 6, 0, 8, 16, 24, 32, 40, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};

/* quadrotor_impl_dae_fun_jac_x_xdot_u:(i0[8],i1[8],i2[6],i3[],i4[])->(o0[8],o1[8x8,48nz],o2[8x8,8nz],o3[8x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+16, *w9=w+24, *w10=w+32, *w11=w+36, *w12=w+40, *w13=w+44, *w14=w+48, *w15=w+64, *w16=w+80, *w17=w+112, *w18=w+144, *w19=w+160, *w20=w+192, *w21=w+256, w22, *w23=w+321, *w24=w+329, *w29=w+377, *w31=w+385;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7) */
  rr=w8;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #9: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #10: @9 = zeros(8x1) */
  casadi_clear(w9, 8);
  /* #11: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #12: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #13: @3 = (-@2) */
  w3 = (- w2 );
  /* #14: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #15: @5 = (-@4) */
  w5 = (- w4 );
  /* #16: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #17: @7 = (-@6) */
  w7 = (- w6 );
  /* #18: @10 = horzcat(@1, @3, @5, @7) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #19: @10 = @10' */
  /* #20: @3 = (-@6) */
  w3 = (- w6 );
  /* #21: @11 = horzcat(@2, @1, @3, @4) */
  rr=w11;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #22: @11 = @11' */
  /* #23: @3 = (-@2) */
  w3 = (- w2 );
  /* #24: @12 = horzcat(@4, @6, @1, @3) */
  rr=w12;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w3;
  /* #25: @12 = @12' */
  /* #26: @4 = (-@4) */
  w4 = (- w4 );
  /* #27: @13 = horzcat(@6, @4, @2, @1) */
  rr=w13;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w2;
  *rr++ = w1;
  /* #28: @13 = @13' */
  /* #29: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #30: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #31: @14 = zeros(4x4) */
  casadi_clear(w14, 16);
  /* #32: @16 = horzcat(@15, @14) */
  rr=w16;
  for (i=0, cs=w15; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<16; ++i) *rr++ = *cs++;
  /* #33: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #34: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #35: @4 = input[0][5] */
  w4 = arg[0] ? arg[0][5] : 0;
  /* #36: @2 = (-@4) */
  w2 = (- w4 );
  /* #37: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #38: @3 = (-@1) */
  w3 = (- w1 );
  /* #39: @5 = input[0][7] */
  w5 = arg[0] ? arg[0][7] : 0;
  /* #40: @7 = (-@5) */
  w7 = (- w5 );
  /* #41: @10 = horzcat(@6, @2, @3, @7) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  /* #42: @10 = @10' */
  /* #43: @2 = (-@5) */
  w2 = (- w5 );
  /* #44: @11 = horzcat(@4, @6, @2, @1) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w1;
  /* #45: @11 = @11' */
  /* #46: @2 = (-@4) */
  w2 = (- w4 );
  /* #47: @12 = horzcat(@1, @5, @6, @2) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w2;
  /* #48: @12 = @12' */
  /* #49: @1 = (-@1) */
  w1 = (- w1 );
  /* #50: @13 = horzcat(@5, @1, @4, @6) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w6;
  /* #51: @13 = @13' */
  /* #52: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #53: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #54: @16 = horzcat(@18, @15) */
  rr=w16;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<16; ++i) *rr++ = *cs++;
  /* #55: @19 = @16' */
  for (i=0, rr=w19, cs=w16; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #56: @20 = horzcat(@17, @19) */
  rr=w20;
  for (i=0, cs=w17; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  /* #57: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #58: @5 = 0 */
  w5 = 0.;
  /* #59: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #60: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #61: @6 = input[2][2] */
  w6 = arg[2] ? arg[2][2] : 0;
  /* #62: @2 = 0 */
  w2 = 0.;
  /* #63: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #64: @7 = input[2][4] */
  w7 = arg[2] ? arg[2][4] : 0;
  /* #65: @22 = input[2][5] */
  w22 = arg[2] ? arg[2][5] : 0;
  /* #66: @23 = vertcat(@5, @1, @4, @6, @2, @3, @7, @22) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w22;
  /* #67: @9 = mac(@21,@23,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w21+j, tt=w23+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #68: @9 = (@0*@9) */
  for (i=0, rr=w9, cs=w9; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #69: @8 = (@8-@9) */
  for (i=0, rr=w8, cs=w9; i<8; ++i) (*rr++) -= (*cs++);
  /* #70: output[0][0] = @8 */
  casadi_copy(w8, 8, res[0]);
  /* #71: @24 = zeros(8x8,48nz) */
  casadi_clear(w24, 48);
  /* #72: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #73: @5 = ones(8x1,1nz) */
  w5 = 1.;
  /* #74: {@1, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w1 = w5;
  /* #75: @25 = 00 */
  /* #76: @26 = 00 */
  /* #77: @27 = 00 */
  /* #78: @5 = horzcat(@1, @25, @26, @27) */
  rr=(&w5);
  *rr++ = w1;
  /* #79: @5 = @5' */
  /* #80: @25 = 00 */
  /* #81: @26 = 00 */
  /* #82: @27 = 00 */
  /* #83: @4 = horzcat(@25, @1, @26, @27) */
  rr=(&w4);
  *rr++ = w1;
  /* #84: @4 = @4' */
  /* #85: @26 = 00 */
  /* #86: @28 = 00 */
  /* #87: @6 = horzcat(@27, @26, @1, @28) */
  rr=(&w6);
  *rr++ = w1;
  /* #88: @6 = @6' */
  /* #89: @27 = 00 */
  /* #90: @2 = horzcat(@26, @27, @25, @1) */
  rr=(&w2);
  *rr++ = w1;
  /* #91: @2 = @2' */
  /* #92: @10 = horzcat(@5, @4, @6, @2) */
  rr=w10;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w2;
  /* #93: @11 = @10' */
  casadi_trans(w10,casadi_s0, w11, casadi_s0, iw);
  /* #94: @26 = zeros(4x4,0nz) */
  /* #95: @10 = horzcat(@11, @26) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #96: @12 = @10' */
  casadi_trans(w10,casadi_s2, w12, casadi_s1, iw);
  /* #97: @26 = zeros(4x4,0nz) */
  /* #98: @10 = horzcat(@26, @11) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #99: @11 = @10' */
  casadi_trans(w10,casadi_s4, w11, casadi_s3, iw);
  /* #100: @9 = horzcat(@12, @11) */
  rr=w9;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #101: @29 = @9' */
  casadi_trans(w9,casadi_s5, w29, casadi_s5, iw);
  /* #102: @8 = mac(@29,@23,@8) */
  casadi_mtimes(w29, casadi_s5, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #103: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #104: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #105: (@24[0, 4, 8, 12, 16, 24, 32, 40] = @8) */
  for (cii=casadi_s7, rr=w24, ss=w8; cii!=casadi_s7+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #106: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #107: @26 = 00 */
  /* #108: @5 = ones(8x1,1nz) */
  w5 = 1.;
  /* #109: {NULL, @4, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w4 = w5;
  /* #110: @5 = (-@4) */
  w5 = (- w4 );
  /* #111: @27 = 00 */
  /* #112: @25 = 00 */
  /* #113: @6 = horzcat(@26, @5, @27, @25) */
  rr=(&w6);
  *rr++ = w5;
  /* #114: @6 = @6' */
  /* #115: @27 = 00 */
  /* #116: @25 = 00 */
  /* #117: @5 = horzcat(@4, @26, @27, @25) */
  rr=(&w5);
  *rr++ = w4;
  /* #118: @5 = @5' */
  /* #119: @27 = 00 */
  /* #120: @2 = (-@4) */
  w2 = (- w4 );
  /* #121: @1 = horzcat(@25, @27, @26, @2) */
  rr=(&w1);
  *rr++ = w2;
  /* #122: @1 = @1' */
  /* #123: @25 = 00 */
  /* #124: @2 = horzcat(@27, @25, @4, @26) */
  rr=(&w2);
  *rr++ = w4;
  /* #125: @2 = @2' */
  /* #126: @12 = horzcat(@6, @5, @1, @2) */
  rr=w12;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w2;
  /* #127: @11 = @12' */
  casadi_trans(w12,casadi_s8, w11, casadi_s8, iw);
  /* #128: @27 = zeros(4x4,0nz) */
  /* #129: @12 = horzcat(@11, @27) */
  rr=w12;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #130: @10 = @12' */
  casadi_trans(w12,casadi_s10, w10, casadi_s9, iw);
  /* #131: @27 = zeros(4x4,0nz) */
  /* #132: @12 = horzcat(@27, @11) */
  rr=w12;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #133: @11 = @12' */
  casadi_trans(w12,casadi_s12, w11, casadi_s11, iw);
  /* #134: @29 = horzcat(@10, @11) */
  rr=w29;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #135: @9 = @29' */
  casadi_trans(w29,casadi_s13, w9, casadi_s13, iw);
  /* #136: @8 = mac(@9,@23,@8) */
  casadi_mtimes(w9, casadi_s13, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #137: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #138: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #139: (@24[1, 5, 9, 13, 17, 25, 33, 41] = @8) */
  for (cii=casadi_s14, rr=w24, ss=w8; cii!=casadi_s14+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #140: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #141: @27 = 00 */
  /* #142: @25 = 00 */
  /* #143: @6 = ones(8x1,1nz) */
  w6 = 1.;
  /* #144: {NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w5 = w6;
  /* #145: @6 = (-@5) */
  w6 = (- w5 );
  /* #146: @26 = 00 */
  /* #147: @1 = horzcat(@27, @25, @6, @26) */
  rr=(&w1);
  *rr++ = w6;
  /* #148: @1 = @1' */
  /* #149: @25 = 00 */
  /* #150: @26 = 00 */
  /* #151: @6 = horzcat(@25, @27, @26, @5) */
  rr=(&w6);
  *rr++ = w5;
  /* #152: @6 = @6' */
  /* #153: @26 = 00 */
  /* #154: @28 = 00 */
  /* #155: @2 = horzcat(@5, @26, @27, @28) */
  rr=(&w2);
  *rr++ = w5;
  /* #156: @2 = @2' */
  /* #157: @5 = (-@5) */
  w5 = (- w5 );
  /* #158: @4 = horzcat(@26, @5, @25, @27) */
  rr=(&w4);
  *rr++ = w5;
  /* #159: @4 = @4' */
  /* #160: @10 = horzcat(@1, @6, @2, @4) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w4;
  /* #161: @11 = @10' */
  casadi_trans(w10,casadi_s15, w11, casadi_s15, iw);
  /* #162: @26 = zeros(4x4,0nz) */
  /* #163: @10 = horzcat(@11, @26) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #164: @12 = @10' */
  casadi_trans(w10,casadi_s17, w12, casadi_s16, iw);
  /* #165: @26 = zeros(4x4,0nz) */
  /* #166: @10 = horzcat(@26, @11) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #167: @11 = @10' */
  casadi_trans(w10,casadi_s19, w11, casadi_s18, iw);
  /* #168: @9 = horzcat(@12, @11) */
  rr=w9;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #169: @29 = @9' */
  casadi_trans(w9,casadi_s20, w29, casadi_s20, iw);
  /* #170: @8 = mac(@29,@23,@8) */
  casadi_mtimes(w29, casadi_s20, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #171: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #172: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #173: (@24[2, 6, 10, 14, 18, 26, 34, 42] = @8) */
  for (cii=casadi_s21, rr=w24, ss=w8; cii!=casadi_s21+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #174: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #175: @26 = 00 */
  /* #176: @25 = 00 */
  /* #177: @27 = 00 */
  /* #178: @1 = ones(8x1,1nz) */
  w1 = 1.;
  /* #179: {NULL, NULL, NULL, @6, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w6 = w1;
  /* #180: @1 = (-@6) */
  w1 = (- w6 );
  /* #181: @2 = horzcat(@26, @25, @27, @1) */
  rr=(&w2);
  *rr++ = w1;
  /* #182: @2 = @2' */
  /* #183: @25 = 00 */
  /* #184: @1 = (-@6) */
  w1 = (- w6 );
  /* #185: @27 = 00 */
  /* #186: @4 = horzcat(@25, @26, @1, @27) */
  rr=(&w4);
  *rr++ = w1;
  /* #187: @4 = @4' */
  /* #188: @28 = 00 */
  /* #189: @1 = horzcat(@27, @6, @26, @28) */
  rr=(&w1);
  *rr++ = w6;
  /* #190: @1 = @1' */
  /* #191: @27 = 00 */
  /* #192: @5 = horzcat(@6, @27, @25, @26) */
  rr=(&w5);
  *rr++ = w6;
  /* #193: @5 = @5' */
  /* #194: @12 = horzcat(@2, @4, @1, @5) */
  rr=w12;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w5;
  /* #195: @11 = @12' */
  casadi_trans(w12,casadi_s22, w11, casadi_s22, iw);
  /* #196: @27 = zeros(4x4,0nz) */
  /* #197: @12 = horzcat(@11, @27) */
  rr=w12;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #198: @10 = @12' */
  casadi_trans(w12,casadi_s24, w10, casadi_s23, iw);
  /* #199: @27 = zeros(4x4,0nz) */
  /* #200: @12 = horzcat(@27, @11) */
  rr=w12;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #201: @11 = @12' */
  casadi_trans(w12,casadi_s26, w11, casadi_s25, iw);
  /* #202: @29 = horzcat(@10, @11) */
  rr=w29;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #203: @9 = @29' */
  casadi_trans(w29,casadi_s27, w9, casadi_s27, iw);
  /* #204: @8 = mac(@9,@23,@8) */
  casadi_mtimes(w9, casadi_s27, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #205: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #206: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #207: (@24[3, 7, 11, 15, 19, 27, 35, 43] = @8) */
  for (cii=casadi_s28, rr=w24, ss=w8; cii!=casadi_s28+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #208: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #209: @27 = zeros(8x4,0nz) */
  /* #210: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #211: {NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL} = vertsplit(@2) */
  w4 = w2;
  /* #212: @25 = 00 */
  /* #213: @26 = 00 */
  /* #214: @28 = 00 */
  /* #215: @2 = horzcat(@4, @25, @26, @28) */
  rr=(&w2);
  *rr++ = w4;
  /* #216: @2 = @2' */
  /* #217: @25 = 00 */
  /* #218: @26 = 00 */
  /* #219: @28 = 00 */
  /* #220: @1 = horzcat(@25, @4, @26, @28) */
  rr=(&w1);
  *rr++ = w4;
  /* #221: @1 = @1' */
  /* #222: @26 = 00 */
  /* #223: @30 = 00 */
  /* #224: @5 = horzcat(@28, @26, @4, @30) */
  rr=(&w5);
  *rr++ = w4;
  /* #225: @5 = @5' */
  /* #226: @28 = 00 */
  /* #227: @6 = horzcat(@26, @28, @25, @4) */
  rr=(&w6);
  *rr++ = w4;
  /* #228: @6 = @6' */
  /* #229: @10 = horzcat(@2, @1, @5, @6) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w5;
  *rr++ = w6;
  /* #230: @11 = @10' */
  casadi_trans(w10,casadi_s0, w11, casadi_s0, iw);
  /* #231: @26 = zeros(4x4,0nz) */
  /* #232: @10 = horzcat(@11, @26) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #233: @11 = @10' */
  casadi_trans(w10,casadi_s2, w11, casadi_s1, iw);
  /* #234: @10 = horzcat(@27, @11) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #235: @11 = @10' */
  casadi_trans(w10,casadi_s30, w11, casadi_s29, iw);
  /* #236: @8 = mac(@11,@23,@8) */
  casadi_mtimes(w11, casadi_s29, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #237: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #238: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #239: @11 = @8[4:8] */
  for (rr=w11, ss=w8+4; ss!=w8+8; ss+=1) *rr++ = *ss;
  /* #240: (@24[20:52:8] = @11) */
  for (rr=w24+20, ss=w11; rr!=w24+52; rr+=8) *rr = *ss++;
  /* #241: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #242: @27 = zeros(8x4,0nz) */
  /* #243: @26 = 00 */
  /* #244: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #245: {NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL} = vertsplit(@2) */
  w1 = w2;
  /* #246: @2 = (-@1) */
  w2 = (- w1 );
  /* #247: @28 = 00 */
  /* #248: @25 = 00 */
  /* #249: @5 = horzcat(@26, @2, @28, @25) */
  rr=(&w5);
  *rr++ = w2;
  /* #250: @5 = @5' */
  /* #251: @28 = 00 */
  /* #252: @25 = 00 */
  /* #253: @2 = horzcat(@1, @26, @28, @25) */
  rr=(&w2);
  *rr++ = w1;
  /* #254: @2 = @2' */
  /* #255: @28 = 00 */
  /* #256: @6 = (-@1) */
  w6 = (- w1 );
  /* #257: @4 = horzcat(@25, @28, @26, @6) */
  rr=(&w4);
  *rr++ = w6;
  /* #258: @4 = @4' */
  /* #259: @25 = 00 */
  /* #260: @6 = horzcat(@28, @25, @1, @26) */
  rr=(&w6);
  *rr++ = w1;
  /* #261: @6 = @6' */
  /* #262: @11 = horzcat(@5, @2, @4, @6) */
  rr=w11;
  *rr++ = w5;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w6;
  /* #263: @10 = @11' */
  casadi_trans(w11,casadi_s8, w10, casadi_s8, iw);
  /* #264: @28 = zeros(4x4,0nz) */
  /* #265: @11 = horzcat(@10, @28) */
  rr=w11;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  /* #266: @10 = @11' */
  casadi_trans(w11,casadi_s10, w10, casadi_s9, iw);
  /* #267: @11 = horzcat(@27, @10) */
  rr=w11;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  /* #268: @10 = @11' */
  casadi_trans(w11,casadi_s32, w10, casadi_s31, iw);
  /* #269: @8 = mac(@10,@23,@8) */
  casadi_mtimes(w10, casadi_s31, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #270: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #271: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #272: @10 = @8[4:8] */
  for (rr=w10, ss=w8+4; ss!=w8+8; ss+=1) *rr++ = *ss;
  /* #273: (@24[21:53:8] = @10) */
  for (rr=w24+21, ss=w10; rr!=w24+53; rr+=8) *rr = *ss++;
  /* #274: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #275: @27 = zeros(8x4,0nz) */
  /* #276: @28 = 00 */
  /* #277: @25 = 00 */
  /* #278: @5 = ones(8x1,1nz) */
  w5 = 1.;
  /* #279: {NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL} = vertsplit(@5) */
  w2 = w5;
  /* #280: @5 = (-@2) */
  w5 = (- w2 );
  /* #281: @26 = 00 */
  /* #282: @4 = horzcat(@28, @25, @5, @26) */
  rr=(&w4);
  *rr++ = w5;
  /* #283: @4 = @4' */
  /* #284: @25 = 00 */
  /* #285: @26 = 00 */
  /* #286: @5 = horzcat(@25, @28, @26, @2) */
  rr=(&w5);
  *rr++ = w2;
  /* #287: @5 = @5' */
  /* #288: @26 = 00 */
  /* #289: @30 = 00 */
  /* #290: @6 = horzcat(@2, @26, @28, @30) */
  rr=(&w6);
  *rr++ = w2;
  /* #291: @6 = @6' */
  /* #292: @2 = (-@2) */
  w2 = (- w2 );
  /* #293: @1 = horzcat(@26, @2, @25, @28) */
  rr=(&w1);
  *rr++ = w2;
  /* #294: @1 = @1' */
  /* #295: @10 = horzcat(@4, @5, @6, @1) */
  rr=w10;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w1;
  /* #296: @11 = @10' */
  casadi_trans(w10,casadi_s15, w11, casadi_s15, iw);
  /* #297: @26 = zeros(4x4,0nz) */
  /* #298: @10 = horzcat(@11, @26) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #299: @11 = @10' */
  casadi_trans(w10,casadi_s17, w11, casadi_s16, iw);
  /* #300: @10 = horzcat(@27, @11) */
  rr=w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #301: @11 = @10' */
  casadi_trans(w10,casadi_s34, w11, casadi_s33, iw);
  /* #302: @8 = mac(@11,@23,@8) */
  casadi_mtimes(w11, casadi_s33, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #303: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #304: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #305: @11 = @8[4:8] */
  for (rr=w11, ss=w8+4; ss!=w8+8; ss+=1) *rr++ = *ss;
  /* #306: (@24[22:54:8] = @11) */
  for (rr=w24+22, ss=w11; rr!=w24+54; rr+=8) *rr = *ss++;
  /* #307: @8 = zeros(8x1) */
  casadi_clear(w8, 8);
  /* #308: @27 = zeros(8x4,0nz) */
  /* #309: @26 = 00 */
  /* #310: @25 = 00 */
  /* #311: @28 = 00 */
  /* #312: @4 = ones(8x1,1nz) */
  w4 = 1.;
  /* #313: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5} = vertsplit(@4) */
  w5 = w4;
  /* #314: @4 = (-@5) */
  w4 = (- w5 );
  /* #315: @6 = horzcat(@26, @25, @28, @4) */
  rr=(&w6);
  *rr++ = w4;
  /* #316: @6 = @6' */
  /* #317: @25 = 00 */
  /* #318: @4 = (-@5) */
  w4 = (- w5 );
  /* #319: @28 = 00 */
  /* #320: @1 = horzcat(@25, @26, @4, @28) */
  rr=(&w1);
  *rr++ = w4;
  /* #321: @1 = @1' */
  /* #322: @30 = 00 */
  /* #323: @4 = horzcat(@28, @5, @26, @30) */
  rr=(&w4);
  *rr++ = w5;
  /* #324: @4 = @4' */
  /* #325: @28 = 00 */
  /* #326: @2 = horzcat(@5, @28, @25, @26) */
  rr=(&w2);
  *rr++ = w5;
  /* #327: @2 = @2' */
  /* #328: @11 = horzcat(@6, @1, @4, @2) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w2;
  /* #329: @10 = @11' */
  casadi_trans(w11,casadi_s22, w10, casadi_s22, iw);
  /* #330: @28 = zeros(4x4,0nz) */
  /* #331: @11 = horzcat(@10, @28) */
  rr=w11;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  /* #332: @10 = @11' */
  casadi_trans(w11,casadi_s24, w10, casadi_s23, iw);
  /* #333: @11 = horzcat(@27, @10) */
  rr=w11;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  /* #334: @10 = @11' */
  casadi_trans(w11,casadi_s36, w10, casadi_s35, iw);
  /* #335: @8 = mac(@10,@23,@8) */
  casadi_mtimes(w10, casadi_s35, w23, casadi_s6, w8, casadi_s6, w, 0);
  /* #336: @8 = (@0*@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #337: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<8; ++i) *rr++ = (- *cs++ );
  /* #338: @10 = @8[4:8] */
  for (rr=w10, ss=w8+4; ss!=w8+8; ss+=1) *rr++ = *ss;
  /* #339: (@24[23:55:8] = @10) */
  for (rr=w24+23, ss=w10; rr!=w24+55; rr+=8) *rr = *ss++;
  /* #340: @31 = @24' */
  casadi_trans(w24,casadi_s38, w31, casadi_s37, iw);
  /* #341: output[1][0] = @31 */
  casadi_copy(w31, 48, res[1]);
  /* #342: @8 = zeros(8x8,8nz) */
  casadi_clear(w8, 8);
  /* #343: @23 = ones(8x1) */
  casadi_fill(w23, 8, 1.);
  /* #344: (@8[:8] = @23) */
  for (rr=w8+0, ss=w23; rr!=w8+8; rr+=1) *rr = *ss++;
  /* #345: @23 = @8' */
  casadi_trans(w8,casadi_s5, w23, casadi_s5, iw);
  /* #346: output[2][0] = @23 */
  casadi_copy(w23, 8, res[2]);
  /* #347: @31 = zeros(6x8) */
  casadi_clear(w31, 48);
  /* #348: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #349: @27 = 00 */
  /* #350: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #351: {@1, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w1 = w6;
  /* #352: @28 = 00 */
  /* #353: @25 = 00 */
  /* #354: @26 = 00 */
  /* #355: @30 = 00 */
  /* #356: @32 = 00 */
  /* #357: @33 = 00 */
  /* #358: @6 = vertcat(@27, @1, @28, @25, @26, @30, @32, @33) */
  rr=(&w6);
  *rr++ = w1;
  /* #359: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s39, w23, casadi_s6, w, 0);
  /* #360: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #361: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #362: (@31[:48:6] = @23) */
  for (rr=w31+0, ss=w23; rr!=w31+48; rr+=6) *rr = *ss++;
  /* #363: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #364: @27 = 00 */
  /* #365: @28 = 00 */
  /* #366: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #367: {NULL, @1, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w1 = w6;
  /* #368: @25 = 00 */
  /* #369: @26 = 00 */
  /* #370: @30 = 00 */
  /* #371: @32 = 00 */
  /* #372: @33 = 00 */
  /* #373: @6 = vertcat(@27, @28, @1, @25, @26, @30, @32, @33) */
  rr=(&w6);
  *rr++ = w1;
  /* #374: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s41, w23, casadi_s6, w, 0);
  /* #375: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #376: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #377: (@31[1:49:6] = @23) */
  for (rr=w31+1, ss=w23; rr!=w31+49; rr+=6) *rr = *ss++;
  /* #378: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #379: @27 = 00 */
  /* #380: @28 = 00 */
  /* #381: @25 = 00 */
  /* #382: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #383: {NULL, NULL, @1, NULL, NULL, NULL} = vertsplit(@6) */
  w1 = w6;
  /* #384: @26 = 00 */
  /* #385: @30 = 00 */
  /* #386: @32 = 00 */
  /* #387: @33 = 00 */
  /* #388: @6 = vertcat(@27, @28, @25, @1, @26, @30, @32, @33) */
  rr=(&w6);
  *rr++ = w1;
  /* #389: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s42, w23, casadi_s6, w, 0);
  /* #390: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #391: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #392: (@31[2:50:6] = @23) */
  for (rr=w31+2, ss=w23; rr!=w31+50; rr+=6) *rr = *ss++;
  /* #393: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #394: @27 = 00 */
  /* #395: @28 = 00 */
  /* #396: @25 = 00 */
  /* #397: @26 = 00 */
  /* #398: @30 = 00 */
  /* #399: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #400: {NULL, NULL, NULL, @1, NULL, NULL} = vertsplit(@6) */
  w1 = w6;
  /* #401: @32 = 00 */
  /* #402: @33 = 00 */
  /* #403: @6 = vertcat(@27, @28, @25, @26, @30, @1, @32, @33) */
  rr=(&w6);
  *rr++ = w1;
  /* #404: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s43, w23, casadi_s6, w, 0);
  /* #405: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #406: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #407: (@31[3:51:6] = @23) */
  for (rr=w31+3, ss=w23; rr!=w31+51; rr+=6) *rr = *ss++;
  /* #408: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #409: @27 = 00 */
  /* #410: @28 = 00 */
  /* #411: @25 = 00 */
  /* #412: @26 = 00 */
  /* #413: @30 = 00 */
  /* #414: @32 = 00 */
  /* #415: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #416: {NULL, NULL, NULL, NULL, @1, NULL} = vertsplit(@6) */
  w1 = w6;
  /* #417: @33 = 00 */
  /* #418: @6 = vertcat(@27, @28, @25, @26, @30, @32, @1, @33) */
  rr=(&w6);
  *rr++ = w1;
  /* #419: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s44, w23, casadi_s6, w, 0);
  /* #420: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #421: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #422: (@31[4:52:6] = @23) */
  for (rr=w31+4, ss=w23; rr!=w31+52; rr+=6) *rr = *ss++;
  /* #423: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #424: @27 = 00 */
  /* #425: @28 = 00 */
  /* #426: @25 = 00 */
  /* #427: @26 = 00 */
  /* #428: @30 = 00 */
  /* #429: @32 = 00 */
  /* #430: @33 = 00 */
  /* #431: @6 = ones(6x1,1nz) */
  w6 = 1.;
  /* #432: {NULL, NULL, NULL, NULL, NULL, @1} = vertsplit(@6) */
  w1 = w6;
  /* #433: @6 = vertcat(@27, @28, @25, @26, @30, @32, @33, @1) */
  rr=(&w6);
  *rr++ = w1;
  /* #434: @23 = mac(@21,@6,@23) */
  casadi_mtimes(w21, casadi_s40, (&w6), casadi_s45, w23, casadi_s6, w, 0);
  /* #435: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #436: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<8; ++i) *rr++ = (- *cs++ );
  /* #437: (@31[5:53:6] = @23) */
  for (rr=w31+5, ss=w23; rr!=w31+53; rr+=6) *rr = *ss++;
  /* #438: @24 = @31' */
  for (i=0, rr=w24, cs=w31; i<8; ++i) for (j=0; j<6; ++j) rr[i+j*8] = *cs++;
  /* #439: output[3][0] = @24 */
  casadi_copy(w24, 48, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s46;
    case 3: return casadi_s47;
    case 4: return casadi_s47;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s37;
    case 2: return casadi_s5;
    case 3: return casadi_s48;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 433;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
