/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* quadrotor_impl_dae_fun:(i0[8],i1[8],i2[6],i3[],i4[])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+16, *w9=w+24, *w10=w+32, *w11=w+36, *w12=w+40, *w13=w+44, *w14=w+48, *w15=w+64, *w16=w+80, *w17=w+112, *w18=w+144, *w19=w+160, *w20=w+192, *w21=w+256, w22, *w23=w+321;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7) */
  rr=w8;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #9: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #10: @9 = zeros(8x1) */
  casadi_clear(w9, 8);
  /* #11: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #12: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #13: @3 = (-@2) */
  w3 = (- w2 );
  /* #14: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #15: @5 = (-@4) */
  w5 = (- w4 );
  /* #16: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #17: @7 = (-@6) */
  w7 = (- w6 );
  /* #18: @10 = horzcat(@1, @3, @5, @7) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #19: @10 = @10' */
  /* #20: @3 = (-@6) */
  w3 = (- w6 );
  /* #21: @11 = horzcat(@2, @1, @3, @4) */
  rr=w11;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w4;
  /* #22: @11 = @11' */
  /* #23: @3 = (-@2) */
  w3 = (- w2 );
  /* #24: @12 = horzcat(@4, @6, @1, @3) */
  rr=w12;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w3;
  /* #25: @12 = @12' */
  /* #26: @4 = (-@4) */
  w4 = (- w4 );
  /* #27: @13 = horzcat(@6, @4, @2, @1) */
  rr=w13;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w2;
  *rr++ = w1;
  /* #28: @13 = @13' */
  /* #29: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #30: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #31: @14 = zeros(4x4) */
  casadi_clear(w14, 16);
  /* #32: @16 = horzcat(@15, @14) */
  rr=w16;
  for (i=0, cs=w15; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<16; ++i) *rr++ = *cs++;
  /* #33: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #34: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #35: @4 = input[0][5] */
  w4 = arg[0] ? arg[0][5] : 0;
  /* #36: @2 = (-@4) */
  w2 = (- w4 );
  /* #37: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #38: @3 = (-@1) */
  w3 = (- w1 );
  /* #39: @5 = input[0][7] */
  w5 = arg[0] ? arg[0][7] : 0;
  /* #40: @7 = (-@5) */
  w7 = (- w5 );
  /* #41: @10 = horzcat(@6, @2, @3, @7) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  /* #42: @10 = @10' */
  /* #43: @2 = (-@5) */
  w2 = (- w5 );
  /* #44: @11 = horzcat(@4, @6, @2, @1) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w1;
  /* #45: @11 = @11' */
  /* #46: @2 = (-@4) */
  w2 = (- w4 );
  /* #47: @12 = horzcat(@1, @5, @6, @2) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w2;
  /* #48: @12 = @12' */
  /* #49: @1 = (-@1) */
  w1 = (- w1 );
  /* #50: @13 = horzcat(@5, @1, @4, @6) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w6;
  /* #51: @13 = @13' */
  /* #52: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #53: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #54: @16 = horzcat(@18, @15) */
  rr=w16;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<16; ++i) *rr++ = *cs++;
  /* #55: @19 = @16' */
  for (i=0, rr=w19, cs=w16; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #56: @20 = horzcat(@17, @19) */
  rr=w20;
  for (i=0, cs=w17; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<32; ++i) *rr++ = *cs++;
  /* #57: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #58: @5 = 0 */
  w5 = 0.;
  /* #59: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #60: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #61: @6 = input[2][2] */
  w6 = arg[2] ? arg[2][2] : 0;
  /* #62: @2 = 0 */
  w2 = 0.;
  /* #63: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #64: @7 = input[2][4] */
  w7 = arg[2] ? arg[2][4] : 0;
  /* #65: @22 = input[2][5] */
  w22 = arg[2] ? arg[2][5] : 0;
  /* #66: @23 = vertcat(@5, @1, @4, @6, @2, @3, @7, @22) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w22;
  /* #67: @9 = mac(@21,@23,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w21+j, tt=w23+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #68: @9 = (@0*@9) */
  for (i=0, rr=w9, cs=w9; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #69: @8 = (@8-@9) */
  for (i=0, rr=w8, cs=w9; i<8; ++i) (*rr++) -= (*cs++);
  /* #70: output[0][0] = @8 */
  casadi_copy(w8, 8, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 329;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
