/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* quadrotor_cost_ext_cost_0_fun_jac:(i0[7],i1[3],i2[],i3[10])->(o0,o1[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, *w2=w+6, *w3=w+9, w4, w5, w6, w7, *w8=w+17, w9, w10, *w11=w+23, w12, *w13=w+28, *w14=w+32, *w15=w+36, *w16=w+52, w17, w18, w19, w20, *w21=w+72, *w22=w+79, *w23=w+82, *w24=w+85, *w25=w+88, *w26=w+91, *w27=w+94, w28, w29, w30, w31, w32, w33, *w34=w+109, *w35=w+113, *w36=w+117, w37, w38, w39, *w40=w+136, *w41=w+146, *w42=w+149, *w43=w+152, *w44=w+155, *w45=w+158, *w46=w+167, *w47=w+176, *w48=w+192;
  /* #0: @0 = 1000 */
  w0 = 1000.;
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #3: @3 = zeros(4x1) */
  casadi_clear(w3, 4);
  /* #4: @4 = input[3][0] */
  w4 = arg[3] ? arg[3][0] : 0;
  /* #5: @5 = input[3][1] */
  w5 = arg[3] ? arg[3][1] : 0;
  /* #6: @6 = input[3][2] */
  w6 = arg[3] ? arg[3][2] : 0;
  /* #7: @7 = input[3][3] */
  w7 = arg[3] ? arg[3][3] : 0;
  /* #8: @8 = horzcat(@4, @5, @6, @7) */
  rr=w8;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #9: @8 = @8' */
  /* #10: @9 = (-@5) */
  w9 = (- w5 );
  /* #11: @10 = (-@6) */
  w10 = (- w6 );
  /* #12: @11 = horzcat(@9, @4, @7, @10) */
  rr=w11;
  *rr++ = w9;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w10;
  /* #13: @11 = @11' */
  /* #14: @12 = (-@7) */
  w12 = (- w7 );
  /* #15: @13 = horzcat(@10, @12, @4, @5) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w5;
  /* #16: @13 = @13' */
  /* #17: @14 = horzcat(@12, @6, @9, @4) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w4;
  /* #18: @14 = @14' */
  /* #19: @15 = horzcat(@8, @11, @13, @14) */
  rr=w15;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  /* #20: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #21: @12 = input[0][0] */
  w12 = arg[0] ? arg[0][0] : 0;
  /* #22: @9 = input[0][1] */
  w9 = arg[0] ? arg[0][1] : 0;
  /* #23: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #24: @17 = input[0][3] */
  w17 = arg[0] ? arg[0][3] : 0;
  /* #25: @18 = input[0][4] */
  w18 = arg[0] ? arg[0][4] : 0;
  /* #26: @19 = input[0][5] */
  w19 = arg[0] ? arg[0][5] : 0;
  /* #27: @20 = input[0][6] */
  w20 = arg[0] ? arg[0][6] : 0;
  /* #28: @21 = vertcat(@12, @9, @10, @17, @18, @19, @20) */
  rr=w21;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #29: @8 = @21[:4] */
  for (rr=w8, ss=w21+0; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #30: @3 = mac(@16,@8,@3) */
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w8+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #31: @22 = @3[1:4] */
  for (rr=w22, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #32: @12 = @3[0] */
  for (rr=(&w12), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #33: @23 = (@22/@12) */
  for (i=0, rr=w23, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w12);
  /* #34: @24 = (2.*@23) */
  for (i=0, rr=w24, cs=w23; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #35: @9 = 1 */
  w9 = 1.;
  /* #36: @10 = ||@22||_F */
  w10 = sqrt(casadi_dot(3, w22, w22));
  /* #37: @17 = 3 */
  w17 = 3.;
  /* #38: @17 = (@10/@17) */
  w17  = (w10/w17);
  /* #39: @18 = sq(@12) */
  w18 = casadi_sq( w12 );
  /* #40: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #41: @9 = (@9-@19) */
  w9 -= w19;
  /* #42: @25 = (@24*@9) */
  for (i=0, rr=w25, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #43: @26 = @25' */
  casadi_copy(w25, 3, w26);
  /* #44: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #45: @19 = 2 */
  w19 = 2.;
  /* #46: (@27[0] = @19) */
  for (rr=w27+0, ss=(&w19); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #47: @19 = 2 */
  w19 = 2.;
  /* #48: (@27[8] = @19) */
  for (rr=w27+8, ss=(&w19); rr!=w27+9; rr+=1) *rr = *ss++;
  /* #49: @19 = 2 */
  w19 = 2.;
  /* #50: (@27[4] = @19) */
  for (rr=w27+4, ss=(&w19); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #51: @2 = mac(@26,@27,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #52: @1 = mac(@2,@25,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w25+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #53: @0 = (@0*@1) */
  w0 *= w1;
  /* #54: @1 = 5 */
  w1 = 5.;
  /* #55: @19 = 0 */
  w19 = 0.;
  /* #56: @26 = @21[4:7] */
  for (rr=w26, ss=w21+4; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #57: @8 = zeros(4x1) */
  casadi_clear(w8, 4);
  /* #58: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #59: @20 = @3[0] */
  for (rr=(&w20), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #60: @28 = @3[1] */
  for (rr=(&w28), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #61: @29 = @3[2] */
  for (rr=(&w29), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #62: @30 = @3[3] */
  for (rr=(&w30), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #63: @13 = horzcat(@20, @28, @29, @30) */
  rr=w13;
  *rr++ = w20;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #64: @13 = @13' */
  /* #65: @20 = (-@28) */
  w20 = (- w28 );
  /* #66: @31 = @3[0] */
  for (rr=(&w31), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #67: @32 = (-@29) */
  w32 = (- w29 );
  /* #68: @14 = horzcat(@20, @31, @30, @32) */
  rr=w14;
  *rr++ = w20;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w32;
  /* #69: @14 = @14' */
  /* #70: @31 = (-@30) */
  w31 = (- w30 );
  /* #71: @33 = @3[0] */
  for (rr=(&w33), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #72: @34 = horzcat(@32, @31, @33, @28) */
  rr=w34;
  *rr++ = w32;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w28;
  /* #73: @34 = @34' */
  /* #74: @32 = @3[0] */
  for (rr=(&w32), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #75: @35 = horzcat(@31, @29, @20, @32) */
  rr=w35;
  *rr++ = w31;
  *rr++ = w29;
  *rr++ = w20;
  *rr++ = w32;
  /* #76: @35 = @35' */
  /* #77: @16 = horzcat(@13, @14, @34, @35) */
  rr=w16;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  /* #78: @36 = @16' */
  for (i=0, rr=w36, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #79: @31 = 0 */
  w31 = 0.;
  /* #80: @20 = input[3][4] */
  w20 = arg[3] ? arg[3][4] : 0;
  /* #81: @32 = input[3][5] */
  w32 = arg[3] ? arg[3][5] : 0;
  /* #82: @33 = input[3][6] */
  w33 = arg[3] ? arg[3][6] : 0;
  /* #83: @37 = input[3][7] */
  w37 = arg[3] ? arg[3][7] : 0;
  /* #84: @38 = input[3][8] */
  w38 = arg[3] ? arg[3][8] : 0;
  /* #85: @39 = input[3][9] */
  w39 = arg[3] ? arg[3][9] : 0;
  /* #86: @40 = vertcat(@4, @5, @6, @7, @20, @32, @33, @37, @38, @39) */
  rr=w40;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w20;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  /* #87: @41 = @40[4:7] */
  for (rr=w41, ss=w40+4; ss!=w40+7; ss+=1) *rr++ = *ss;
  /* #88: @13 = vertcat(@31, @41) */
  rr=w13;
  *rr++ = w31;
  for (i=0, cs=w41; i<3; ++i) *rr++ = *cs++;
  /* #89: @11 = mac(@36,@13,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #90: @31 = @11[0] */
  for (rr=(&w31), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #91: @4 = @11[1] */
  for (rr=(&w4), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #92: @4 = (-@4) */
  w4 = (- w4 );
  /* #93: @5 = @11[2] */
  for (rr=(&w5), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #94: @5 = (-@5) */
  w5 = (- w5 );
  /* #95: @6 = @11[3] */
  for (rr=(&w6), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #96: @6 = (-@6) */
  w6 = (- w6 );
  /* #97: @14 = horzcat(@31, @4, @5, @6) */
  rr=w14;
  *rr++ = w31;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #98: @14 = @14' */
  /* #99: @31 = @11[1] */
  for (rr=(&w31), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #100: @4 = @11[0] */
  for (rr=(&w4), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #101: @5 = @11[3] */
  for (rr=(&w5), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #102: @5 = (-@5) */
  w5 = (- w5 );
  /* #103: @6 = @11[2] */
  for (rr=(&w6), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #104: @34 = horzcat(@31, @4, @5, @6) */
  rr=w34;
  *rr++ = w31;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #105: @34 = @34' */
  /* #106: @31 = @11[2] */
  for (rr=(&w31), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #107: @4 = @11[3] */
  for (rr=(&w4), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #108: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #109: @6 = @11[1] */
  for (rr=(&w6), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #110: @6 = (-@6) */
  w6 = (- w6 );
  /* #111: @35 = horzcat(@31, @4, @5, @6) */
  rr=w35;
  *rr++ = w31;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #112: @35 = @35' */
  /* #113: @31 = @11[3] */
  for (rr=(&w31), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #114: @4 = @11[2] */
  for (rr=(&w4), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #115: @4 = (-@4) */
  w4 = (- w4 );
  /* #116: @5 = @11[1] */
  for (rr=(&w5), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #117: @6 = @11[0] */
  for (rr=(&w6), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #118: @11 = horzcat(@31, @4, @5, @6) */
  rr=w11;
  *rr++ = w31;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #119: @11 = @11' */
  /* #120: @36 = horzcat(@14, @34, @35, @11) */
  rr=w36;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #121: @16 = @36' */
  for (i=0, rr=w16, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #122: @31 = @3[0] */
  for (rr=(&w31), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #123: @3 = vertcat(@31, @28, @29, @30) */
  rr=w3;
  *rr++ = w31;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #124: @8 = mac(@16,@3,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #125: @41 = @8[1:4] */
  for (rr=w41, ss=w8+1; ss!=w8+4; ss+=1) *rr++ = *ss;
  /* #126: @26 = (@26-@41) */
  for (i=0, rr=w26, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #127: @41 = @26' */
  casadi_copy(w26, 3, w41);
  /* #128: @19 = mac(@41,@26,@19) */
  for (i=0, rr=(&w19); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w41+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #129: @1 = (@1*@19) */
  w1 *= w19;
  /* #130: @0 = (@0+@1) */
  w0 += w1;
  /* #131: @1 = 0 */
  w1 = 0.;
  /* #132: @19 = 5 */
  w19 = 5.;
  /* #133: @41 = @25' */
  casadi_copy(w25, 3, w41);
  /* #134: @41 = (@19*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #135: @1 = mac(@41,@26,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w41+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #136: @0 = (@0+@1) */
  w0 += w1;
  /* #137: @1 = 0 */
  w1 = 0.;
  /* #138: @42 = zeros(1x3) */
  casadi_clear(w42, 3);
  /* #139: @43 = @40[7:10] */
  for (rr=w43, ss=w40+7; ss!=w40+10; ss+=1) *rr++ = *ss;
  /* #140: @31 = input[1][0] */
  w31 = arg[1] ? arg[1][0] : 0;
  /* #141: @28 = input[1][1] */
  w28 = arg[1] ? arg[1][1] : 0;
  /* #142: @29 = input[1][2] */
  w29 = arg[1] ? arg[1][2] : 0;
  /* #143: @44 = vertcat(@31, @28, @29) */
  rr=w44;
  *rr++ = w31;
  *rr++ = w28;
  *rr++ = w29;
  /* #144: @43 = (@43-@44) */
  for (i=0, rr=w43, cs=w44; i<3; ++i) (*rr++) -= (*cs++);
  /* #145: @44 = @43' */
  casadi_copy(w43, 3, w44);
  /* #146: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #147: @31 = 0.0001 */
  w31 = 1.0000000000000000e-04;
  /* #148: (@45[0] = @31) */
  for (rr=w45+0, ss=(&w31); rr!=w45+1; rr+=1) *rr = *ss++;
  /* #149: @31 = 0.0001 */
  w31 = 1.0000000000000000e-04;
  /* #150: (@45[4] = @31) */
  for (rr=w45+4, ss=(&w31); rr!=w45+5; rr+=1) *rr = *ss++;
  /* #151: @31 = 0.0001 */
  w31 = 1.0000000000000000e-04;
  /* #152: (@45[8] = @31) */
  for (rr=w45+8, ss=(&w31); rr!=w45+9; rr+=1) *rr = *ss++;
  /* #153: @42 = mac(@44,@45,@42) */
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #154: @1 = mac(@42,@43,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #155: @0 = (@0+@1) */
  w0 += w1;
  /* #156: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #157: @42 = @42' */
  /* #158: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #159: @43 = @43' */
  /* #160: @46 = @45' */
  for (i=0, rr=w46, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #161: @44 = mac(@43,@46,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #162: @44 = @44' */
  /* #163: @42 = (@42+@44) */
  for (i=0, rr=w42, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #164: @42 = (-@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) *rr++ = (- *cs++ );
  /* #165: {@0, @1, @31} = vertsplit(@42) */
  w0 = w42[0];
  w1 = w42[1];
  w31 = w42[2];
  /* #166: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #167: output[1][1] = @1 */
  if (res[1]) res[1][1] = w1;
  /* #168: output[1][2] = @31 */
  if (res[1]) res[1][2] = w31;
  /* #169: @21 = zeros(7x1) */
  casadi_clear(w21, 7);
  /* #170: @41 = @41' */
  /* #171: @31 = 5 */
  w31 = 5.;
  /* #172: @42 = (@31*@26) */
  for (i=0, rr=w42, cs=w26; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #173: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #174: @42 = @26' */
  casadi_copy(w26, 3, w42);
  /* #175: @42 = (@31*@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #176: @42 = @42' */
  /* #177: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #178: (@21[4:7] += @41) */
  for (rr=w21+4, ss=w41; rr!=w21+7; rr+=1) *rr += *ss++;
  /* #179: @8 = zeros(4x1) */
  casadi_clear(w8, 4);
  /* #180: @14 = zeros(4x1) */
  casadi_clear(w14, 4);
  /* #181: @34 = zeros(4x1) */
  casadi_clear(w34, 4);
  /* #182: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #183: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #184: (@35[1:4] += @41) */
  for (rr=w35+1, ss=w41; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #185: @34 = mac(@36,@35,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #186: {@31, @1, @0, @28} = vertsplit(@34) */
  w31 = w34[0];
  w1 = w34[1];
  w0 = w34[2];
  w28 = w34[3];
  /* #187: (@14[0] += @31) */
  for (rr=w14+0, ss=(&w31); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #188: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #189: @34 = zeros(4x1) */
  casadi_clear(w34, 4);
  /* #190: @16 = zeros(4x4) */
  casadi_clear(w16, 16);
  /* #191: @3 = @3' */
  /* #192: @16 = mac(@35,@3,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w3+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #193: @47 = @16' */
  for (i=0, rr=w47, cs=w16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #194: {@35, @3, @11, @48} = horzsplit(@47) */
  casadi_copy(w47, 4, w35);
  casadi_copy(w47+4, 4, w3);
  casadi_copy(w47+8, 4, w11);
  casadi_copy(w47+12, 4, w48);
  /* #195: @48 = @48' */
  /* #196: {@31, @29, @30, @4} = horzsplit(@48) */
  w31 = w48[0];
  w29 = w48[1];
  w30 = w48[2];
  w4 = w48[3];
  /* #197: (@34[0] += @4) */
  for (rr=w34+0, ss=(&w4); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #198: (@34[1] += @30) */
  for (rr=w34+1, ss=(&w30); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #199: @29 = (-@29) */
  w29 = (- w29 );
  /* #200: (@34[2] += @29) */
  for (rr=w34+2, ss=(&w29); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #201: (@34[3] += @31) */
  for (rr=w34+3, ss=(&w31); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #202: @11 = @11' */
  /* #203: {@31, @29, @30, @4} = horzsplit(@11) */
  w31 = w11[0];
  w29 = w11[1];
  w30 = w11[2];
  w4 = w11[3];
  /* #204: @4 = (-@4) */
  w4 = (- w4 );
  /* #205: (@34[1] += @4) */
  for (rr=w34+1, ss=(&w4); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #206: (@34[0] += @30) */
  for (rr=w34+0, ss=(&w30); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #207: (@34[3] += @29) */
  for (rr=w34+3, ss=(&w29); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #208: (@34[2] += @31) */
  for (rr=w34+2, ss=(&w31); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #209: @3 = @3' */
  /* #210: {@31, @29, @30, @4} = horzsplit(@3) */
  w31 = w3[0];
  w29 = w3[1];
  w30 = w3[2];
  w4 = w3[3];
  /* #211: (@34[2] += @4) */
  for (rr=w34+2, ss=(&w4); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #212: @30 = (-@30) */
  w30 = (- w30 );
  /* #213: (@34[3] += @30) */
  for (rr=w34+3, ss=(&w30); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #214: (@34[0] += @29) */
  for (rr=w34+0, ss=(&w29); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #215: (@34[1] += @31) */
  for (rr=w34+1, ss=(&w31); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #216: @35 = @35' */
  /* #217: {@31, @29, @30, @4} = horzsplit(@35) */
  w31 = w35[0];
  w29 = w35[1];
  w30 = w35[2];
  w4 = w35[3];
  /* #218: @4 = (-@4) */
  w4 = (- w4 );
  /* #219: (@34[3] += @4) */
  for (rr=w34+3, ss=(&w4); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #220: @30 = (-@30) */
  w30 = (- w30 );
  /* #221: (@34[2] += @30) */
  for (rr=w34+2, ss=(&w30); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #222: @29 = (-@29) */
  w29 = (- w29 );
  /* #223: (@34[1] += @29) */
  for (rr=w34+1, ss=(&w29); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #224: (@34[0] += @31) */
  for (rr=w34+0, ss=(&w31); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #225: @13 = @13' */
  /* #226: @36 = mac(@34,@13,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w13+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #227: @47 = @36' */
  for (i=0, rr=w47, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #228: {@34, @13, @35, @3} = horzsplit(@47) */
  casadi_copy(w47, 4, w34);
  casadi_copy(w47+4, 4, w13);
  casadi_copy(w47+8, 4, w35);
  casadi_copy(w47+12, 4, w3);
  /* #229: @3 = @3' */
  /* #230: {@31, @29, @30, @4} = horzsplit(@3) */
  w31 = w3[0];
  w29 = w3[1];
  w30 = w3[2];
  w4 = w3[3];
  /* #231: (@14[0] += @4) */
  for (rr=w14+0, ss=(&w4); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #232: @35 = @35' */
  /* #233: {@4, @5, @6, @7} = horzsplit(@35) */
  w4 = w35[0];
  w5 = w35[1];
  w6 = w35[2];
  w7 = w35[3];
  /* #234: (@14[0] += @6) */
  for (rr=w14+0, ss=(&w6); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #235: @13 = @13' */
  /* #236: {@6, @20, @32, @33} = horzsplit(@13) */
  w6 = w13[0];
  w20 = w13[1];
  w32 = w13[2];
  w33 = w13[3];
  /* #237: (@14[0] += @20) */
  for (rr=w14+0, ss=(&w20); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #238: @31 = (@31+@5) */
  w31 += w5;
  /* #239: @28 = (@28-@31) */
  w28 -= w31;
  /* #240: @28 = (@28+@32) */
  w28 += w32;
  /* #241: @34 = @34' */
  /* #242: {@32, @31, @5, @20} = horzsplit(@34) */
  w32 = w34[0];
  w31 = w34[1];
  w5 = w34[2];
  w20 = w34[3];
  /* #243: @28 = (@28+@20) */
  w28 += w20;
  /* #244: (@14[3] += @28) */
  for (rr=w14+3, ss=(&w28); rr!=w14+4; rr+=1) *rr += *ss++;
  /* #245: @0 = (@0+@29) */
  w0 += w29;
  /* #246: @4 = (@4+@33) */
  w4 += w33;
  /* #247: @0 = (@0-@4) */
  w0 -= w4;
  /* #248: @0 = (@0+@5) */
  w0 += w5;
  /* #249: (@14[2] += @0) */
  for (rr=w14+2, ss=(&w0); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #250: @1 = (@1+@7) */
  w1 += w7;
  /* #251: @30 = (@30+@6) */
  w30 += w6;
  /* #252: @1 = (@1-@30) */
  w1 -= w30;
  /* #253: @1 = (@1+@31) */
  w1 += w31;
  /* #254: (@14[1] += @1) */
  for (rr=w14+1, ss=(&w1); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #255: (@14[0] += @32) */
  for (rr=w14+0, ss=(&w32); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #256: @23 = (@23/@12) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w12;
  /* #257: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #258: @26 = @26' */
  /* #259: @26 = (@19*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #260: @26 = @26' */
  /* #261: @19 = 1000 */
  w19 = 1000.;
  /* #262: @2 = @2' */
  /* #263: @2 = (@19*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #264: @26 = (@26+@2) */
  for (i=0, rr=w26, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #265: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #266: @25 = @25' */
  /* #267: @25 = (@19*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #268: @46 = @27' */
  for (i=0, rr=w46, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #269: @2 = mac(@25,@46,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #270: @2 = @2' */
  /* #271: @26 = (@26+@2) */
  for (i=0, rr=w26, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #272: @2 = (@9*@26) */
  for (i=0, rr=w2, cs=w26; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #273: @2 = (2.*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #274: @9 = dot(@23, @2) */
  w9 = casadi_dot(3, w23, w2);
  /* #275: @19 = (2.*@12) */
  w19 = (2.* w12 );
  /* #276: @32 = dot(@24, @26) */
  w32 = casadi_dot(3, w24, w26);
  /* #277: @17 = (@17*@32) */
  w17 *= w32;
  /* #278: @19 = (@19*@17) */
  w19 *= w17;
  /* #279: @9 = (@9-@19) */
  w9 -= w19;
  /* #280: (@14[0] += @9) */
  for (rr=w14+0, ss=(&w9); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #281: @2 = (@2/@12) */
  for (i=0, rr=w2; i<3; ++i) (*rr++) /= w12;
  /* #282: @12 = 0.333333 */
  w12 = 3.3333333333333331e-01;
  /* #283: @18 = (@18*@32) */
  w18 *= w32;
  /* #284: @12 = (@12*@18) */
  w12 *= w18;
  /* #285: @12 = (@12/@10) */
  w12 /= w10;
  /* #286: @22 = (@12*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #287: @2 = (@2-@22) */
  for (i=0, rr=w2, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #288: (@14[1:4] += @2) */
  for (rr=w14+1, ss=w2; rr!=w14+4; rr+=1) *rr += *ss++;
  /* #289: @8 = mac(@15,@14,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w14+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #290: (@21[:4] += @8) */
  for (rr=w21+0, ss=w8; rr!=w21+4; rr+=1) *rr += *ss++;
  /* #291: {@12, @10, @18, @32, @9, @19, @17} = vertsplit(@21) */
  w12 = w21[0];
  w10 = w21[1];
  w18 = w21[2];
  w32 = w21[3];
  w9 = w21[4];
  w19 = w21[5];
  w17 = w21[6];
  /* #292: output[1][3] = @12 */
  if (res[1]) res[1][3] = w12;
  /* #293: output[1][4] = @10 */
  if (res[1]) res[1][4] = w10;
  /* #294: output[1][5] = @18 */
  if (res[1]) res[1][5] = w18;
  /* #295: output[1][6] = @32 */
  if (res[1]) res[1][6] = w32;
  /* #296: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #297: output[1][8] = @19 */
  if (res[1]) res[1][8] = w19;
  /* #298: output[1][9] = @17 */
  if (res[1]) res[1][9] = w17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 196;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
