/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[64] = {0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 2.};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[14],i1[],i2[],i3[18])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, *w2=w+10, w3, w4, *w5=w+20, *w6=w+23, *w7=w+31, w8, w9, w10, w11, *w12=w+53, w13, w14, *w15=w+59, *w16=w+63, *w17=w+67, *w18=w+71, *w19=w+87, *w20=w+103, *w21=w+135, *w22=w+167, *w23=w+183, *w24=w+215, *w25=w+279, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+351, *w35=w+365, *w36=w+373, w37, w38, w39, w40, w41, w42, w43, *w44=w+383, *w45=w+387, *w46=w+395, *w47=w+403, w48, w49, w50;
  /* #0: @0 = 10 */
  w0 = 10.;
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #3: @3 = 0 */
  w3 = 0.;
  /* #4: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #5: @5 = all_2.22045e-16(3x1) */
  casadi_fill(w5, 3, 2.2204460492503131e-16);
  /* #6: @6 = zeros(8x1) */
  casadi_clear(w6, 8);
  /* #7: @7 = input[3][0] */
  casadi_copy(arg[3], 18, w7);
  /* #8: @8 = @7[0] */
  for (rr=(&w8), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #9: @9 = @7[1] */
  for (rr=(&w9), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #10: @10 = @7[2] */
  for (rr=(&w10), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #11: @11 = @7[3] */
  for (rr=(&w11), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #12: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @12 = @12' */
  /* #14: @8 = (-@9) */
  w8 = (- w9 );
  /* #15: @13 = @7[0] */
  for (rr=(&w13), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #16: @14 = (-@10) */
  w14 = (- w10 );
  /* #17: @15 = horzcat(@8, @13, @11, @14) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w14;
  /* #18: @15 = @15' */
  /* #19: @11 = (-@11) */
  w11 = (- w11 );
  /* #20: @13 = @7[0] */
  for (rr=(&w13), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #21: @16 = horzcat(@14, @11, @13, @9) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w9;
  /* #22: @16 = @16' */
  /* #23: @14 = @7[0] */
  for (rr=(&w14), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #24: @17 = horzcat(@11, @10, @8, @14) */
  rr=w17;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w14;
  /* #25: @17 = @17' */
  /* #26: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #27: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @20 = horzcat(@19, @18) */
  rr=w20;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #30: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #31: @11 = @7[4] */
  for (rr=(&w11), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #32: @10 = @7[5] */
  for (rr=(&w10), ss=w7+5; ss!=w7+6; ss+=1) *rr++ = *ss;
  /* #33: @8 = @7[6] */
  for (rr=(&w8), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #34: @14 = @7[7] */
  for (rr=(&w14), ss=w7+7; ss!=w7+8; ss+=1) *rr++ = *ss;
  /* #35: @12 = horzcat(@11, @10, @8, @14) */
  rr=w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w14;
  /* #36: @12 = @12' */
  /* #37: @11 = (-@10) */
  w11 = (- w10 );
  /* #38: @13 = @7[4] */
  for (rr=(&w13), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #39: @9 = (-@8) */
  w9 = (- w8 );
  /* #40: @15 = horzcat(@11, @13, @14, @9) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w9;
  /* #41: @15 = @15' */
  /* #42: @14 = (-@14) */
  w14 = (- w14 );
  /* #43: @13 = @7[4] */
  for (rr=(&w13), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #44: @16 = horzcat(@9, @14, @13, @10) */
  rr=w16;
  *rr++ = w9;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w10;
  /* #45: @16 = @16' */
  /* #46: @9 = @7[4] */
  for (rr=(&w9), ss=w7+4; ss!=w7+5; ss+=1) *rr++ = *ss;
  /* #47: @17 = horzcat(@14, @8, @11, @9) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w9;
  /* #48: @17 = @17' */
  /* #49: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #50: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #51: @20 = horzcat(@22, @19) */
  rr=w20;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  /* #52: @23 = @20' */
  for (i=0, rr=w23, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #53: @24 = horzcat(@21, @23) */
  rr=w24;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  /* #54: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #55: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #56: @8 = input[0][1] */
  w8 = arg[0] ? arg[0][1] : 0;
  /* #57: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #58: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #59: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #60: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #61: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #62: @27 = input[0][7] */
  w27 = arg[0] ? arg[0][7] : 0;
  /* #63: @28 = input[0][8] */
  w28 = arg[0] ? arg[0][8] : 0;
  /* #64: @29 = input[0][9] */
  w29 = arg[0] ? arg[0][9] : 0;
  /* #65: @30 = input[0][10] */
  w30 = arg[0] ? arg[0][10] : 0;
  /* #66: @31 = input[0][11] */
  w31 = arg[0] ? arg[0][11] : 0;
  /* #67: @32 = input[0][12] */
  w32 = arg[0] ? arg[0][12] : 0;
  /* #68: @33 = input[0][13] */
  w33 = arg[0] ? arg[0][13] : 0;
  /* #69: @34 = vertcat(@14, @8, @11, @9, @13, @10, @26, @27, @28, @29, @30, @31, @32, @33) */
  rr=w34;
  *rr++ = w14;
  *rr++ = w8;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #70: @35 = @34[:8] */
  for (rr=w35, ss=w34+0; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #71: @6 = mac(@25,@35,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w25+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #72: @36 = @6[1:4] */
  for (rr=w36, ss=w6+1; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #73: @5 = (@5+@36) */
  for (i=0, rr=w5, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #74: @14 = ||@5||_F */
  w14 = sqrt(casadi_dot(3, w5, w5));
  /* #75: @8 = @6[0] */
  for (rr=(&w8), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #76: @11 = atan2(@14,@8) */
  w11  = atan2(w14,w8);
  /* #77: @9 = (@4*@11) */
  w9  = (w4*w11);
  /* #78: @13 = @6[1] */
  for (rr=(&w13), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #79: @10 = (@9*@13) */
  w10  = (w9*w13);
  /* #80: @10 = (@10/@14) */
  w10 /= w14;
  /* #81: @26 = 0.5 */
  w26 = 5.0000000000000000e-01;
  /* #82: @27 = (@26*@11) */
  w27  = (w26*w11);
  /* #83: @28 = @6[2] */
  for (rr=(&w28), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #84: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #85: @29 = (@29/@14) */
  w29 /= w14;
  /* #86: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #87: @11 = (@30*@11) */
  w11  = (w30*w11);
  /* #88: @31 = @6[3] */
  for (rr=(&w31), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #89: @32 = (@11*@31) */
  w32  = (w11*w31);
  /* #90: @32 = (@32/@14) */
  w32 /= w14;
  /* #91: @33 = 0 */
  w33 = 0.;
  /* #92: @37 = 0.5 */
  w37 = 5.0000000000000000e-01;
  /* #93: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #94: @38 = @6[0] */
  for (rr=(&w38), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #95: @39 = @6[1] */
  for (rr=(&w39), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #96: @40 = @6[2] */
  for (rr=(&w40), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #97: @41 = @6[3] */
  for (rr=(&w41), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #98: @15 = horzcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #99: @15 = @15' */
  /* #100: @38 = (-@39) */
  w38 = (- w39 );
  /* #101: @42 = @6[0] */
  for (rr=(&w42), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #102: @43 = (-@40) */
  w43 = (- w40 );
  /* #103: @16 = horzcat(@38, @42, @41, @43) */
  rr=w16;
  *rr++ = w38;
  *rr++ = w42;
  *rr++ = w41;
  *rr++ = w43;
  /* #104: @16 = @16' */
  /* #105: @41 = (-@41) */
  w41 = (- w41 );
  /* #106: @42 = @6[0] */
  for (rr=(&w42), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #107: @17 = horzcat(@43, @41, @42, @39) */
  rr=w17;
  *rr++ = w43;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w39;
  /* #108: @17 = @17' */
  /* #109: @43 = @6[0] */
  for (rr=(&w43), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #110: @44 = horzcat(@41, @40, @38, @43) */
  rr=w44;
  *rr++ = w41;
  *rr++ = w40;
  *rr++ = w38;
  *rr++ = w43;
  /* #111: @44 = @44' */
  /* #112: @22 = horzcat(@15, @16, @17, @44) */
  rr=w22;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<4; ++i) *rr++ = *cs++;
  /* #113: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #114: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #115: @15 = @6[4:8] */
  for (rr=w15, ss=w6+4; ss!=w6+8; ss+=1) *rr++ = *ss;
  /* #116: @12 = mac(@19,@15,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w19+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #117: @41 = @12[1] */
  for (rr=(&w41), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #118: @41 = (@37*@41) */
  w41  = (w37*w41);
  /* #119: @40 = 0.5 */
  w40 = 5.0000000000000000e-01;
  /* #120: @38 = @12[2] */
  for (rr=(&w38), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #121: @38 = (@40*@38) */
  w38  = (w40*w38);
  /* #122: @43 = 0.5 */
  w43 = 5.0000000000000000e-01;
  /* #123: @42 = @12[3] */
  for (rr=(&w42), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #124: @42 = (@43*@42) */
  w42  = (w43*w42);
  /* #125: @6 = vertcat(@3, @10, @29, @32, @33, @41, @38, @42) */
  rr=w6;
  *rr++ = w3;
  *rr++ = w10;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w41;
  *rr++ = w38;
  *rr++ = w42;
  /* #126: @35 = @6' */
  casadi_copy(w6, 8, w35);
  /* #127: @25 = 
  [[0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 2, 0, 0, 0, 0, 0, 0], 
   [0, 0, 2, 0, 0, 0, 0, 0], 
   [0, 0, 0, 2, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 2, 0, 0], 
   [0, 0, 0, 0, 0, 0, 2, 0], 
   [0, 0, 0, 0, 0, 0, 0, 2]] */
  casadi_copy(casadi_c0, 64, w25);
  /* #128: @2 = mac(@35,@25,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w25+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #129: @1 = mac(@2,@6,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w6+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #130: @0 = (@0*@1) */
  w0 *= w1;
  /* #131: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #132: @34 = zeros(14x1) */
  casadi_clear(w34, 14);
  /* #133: @35 = zeros(8x1) */
  casadi_clear(w35, 8);
  /* #134: @45 = zeros(8x1) */
  casadi_clear(w45, 8);
  /* #135: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #136: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #137: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #138: @0 = 10 */
  w0 = 10.;
  /* #139: @2 = @2' */
  /* #140: @2 = (@0*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #141: @46 = zeros(1x8) */
  casadi_clear(w46, 8);
  /* #142: @6 = @6' */
  /* #143: @6 = (@0*@6) */
  for (i=0, rr=w6, cs=w6; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #144: @47 = @25' */
  for (i=0, rr=w47, cs=w25; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #145: @46 = mac(@6,@47,@46) */
  for (i=0, rr=w46; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w47+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #146: @46 = @46' */
  /* #147: @2 = (@2+@46) */
  for (i=0, rr=w2, cs=w46; i<8; ++i) (*rr++) += (*cs++);
  /* #148: {NULL, @0, @1, @3, NULL, @33, @41, @38} = vertsplit(@2) */
  w0 = w2[1];
  w1 = w2[2];
  w3 = w2[3];
  w33 = w2[5];
  w41 = w2[6];
  w38 = w2[7];
  /* #149: @43 = (@43*@38) */
  w43 *= w38;
  /* #150: (@16[3] += @43) */
  for (rr=w16+3, ss=(&w43); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #151: @40 = (@40*@41) */
  w40 *= w41;
  /* #152: (@16[2] += @40) */
  for (rr=w16+2, ss=(&w40); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #153: @37 = (@37*@33) */
  w37 *= w33;
  /* #154: (@16[1] += @37) */
  for (rr=w16+1, ss=(&w37); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #155: @12 = mac(@22,@16,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w22+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #156: (@45[4:8] += @12) */
  for (rr=w45+4, ss=w12; rr!=w45+8; rr+=1) *rr += *ss++;
  /* #157: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #158: @15 = @15' */
  /* #159: @22 = mac(@16,@15,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #160: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #161: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #162: {@16, @15, @12, @17} = horzsplit(@19) */
  casadi_copy(w19, 4, w16);
  casadi_copy(w19+4, 4, w15);
  casadi_copy(w19+8, 4, w12);
  casadi_copy(w19+12, 4, w17);
  /* #163: @17 = @17' */
  /* #164: {@37, @33, @40, @41} = horzsplit(@17) */
  w37 = w17[0];
  w33 = w17[1];
  w40 = w17[2];
  w41 = w17[3];
  /* #165: (@45[0] += @41) */
  for (rr=w45+0, ss=(&w41); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #166: @12 = @12' */
  /* #167: {@41, @43, @38, @42} = horzsplit(@12) */
  w41 = w12[0];
  w43 = w12[1];
  w38 = w12[2];
  w42 = w12[3];
  /* #168: (@45[0] += @38) */
  for (rr=w45+0, ss=(&w38); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #169: @15 = @15' */
  /* #170: {@38, @39, @48, @49} = horzsplit(@15) */
  w38 = w15[0];
  w39 = w15[1];
  w48 = w15[2];
  w49 = w15[3];
  /* #171: (@45[0] += @39) */
  for (rr=w45+0, ss=(&w39); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #172: @37 = (@37+@43) */
  w37 += w43;
  /* #173: @48 = (@48-@37) */
  w48 -= w37;
  /* #174: @16 = @16' */
  /* #175: {@37, @43, @39, @50} = horzsplit(@16) */
  w37 = w16[0];
  w43 = w16[1];
  w39 = w16[2];
  w50 = w16[3];
  /* #176: @48 = (@48+@50) */
  w48 += w50;
  /* #177: (@45[3] += @48) */
  for (rr=w45+3, ss=(&w48); rr!=w45+4; rr+=1) *rr += *ss++;
  /* #178: @41 = (@41+@49) */
  w41 += w49;
  /* #179: @33 = (@33-@41) */
  w33 -= w41;
  /* #180: @33 = (@33+@39) */
  w33 += w39;
  /* #181: (@45[2] += @33) */
  for (rr=w45+2, ss=(&w33); rr!=w45+3; rr+=1) *rr += *ss++;
  /* #182: @40 = (@40+@38) */
  w40 += w38;
  /* #183: @42 = (@42-@40) */
  w42 -= w40;
  /* #184: @42 = (@42+@43) */
  w42 += w43;
  /* #185: (@45[1] += @42) */
  for (rr=w45+1, ss=(&w42); rr!=w45+2; rr+=1) *rr += *ss++;
  /* #186: (@45[0] += @37) */
  for (rr=w45+0, ss=(&w37); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #187: @37 = (@3/@14) */
  w37  = (w3/w14);
  /* #188: @11 = (@11*@37) */
  w11 *= w37;
  /* #189: (@45[3] += @11) */
  for (rr=w45+3, ss=(&w11); rr!=w45+4; rr+=1) *rr += *ss++;
  /* #190: @11 = (@1/@14) */
  w11  = (w1/w14);
  /* #191: @27 = (@27*@11) */
  w27 *= w11;
  /* #192: (@45[2] += @27) */
  for (rr=w45+2, ss=(&w27); rr!=w45+3; rr+=1) *rr += *ss++;
  /* #193: @27 = (@0/@14) */
  w27  = (w0/w14);
  /* #194: @9 = (@9*@27) */
  w9 *= w27;
  /* #195: (@45[1] += @9) */
  for (rr=w45+1, ss=(&w9); rr!=w45+2; rr+=1) *rr += *ss++;
  /* #196: @9 = sq(@14) */
  w9 = casadi_sq( w14 );
  /* #197: @42 = sq(@8) */
  w42 = casadi_sq( w8 );
  /* #198: @9 = (@9+@42) */
  w9 += w42;
  /* #199: @42 = (@14/@9) */
  w42  = (w14/w9);
  /* #200: @31 = (@31*@37) */
  w31 *= w37;
  /* #201: @30 = (@30*@31) */
  w30 *= w31;
  /* #202: @28 = (@28*@11) */
  w28 *= w11;
  /* #203: @26 = (@26*@28) */
  w26 *= w28;
  /* #204: @30 = (@30+@26) */
  w30 += w26;
  /* #205: @13 = (@13*@27) */
  w13 *= w27;
  /* #206: @4 = (@4*@13) */
  w4 *= w13;
  /* #207: @30 = (@30+@4) */
  w30 += w4;
  /* #208: @42 = (@42*@30) */
  w42 *= w30;
  /* #209: @42 = (-@42) */
  w42 = (- w42 );
  /* #210: (@45[0] += @42) */
  for (rr=w45+0, ss=(&w42); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #211: @29 = (@29/@14) */
  w29 /= w14;
  /* #212: @29 = (@29*@1) */
  w29 *= w1;
  /* #213: @29 = (-@29) */
  w29 = (- w29 );
  /* #214: @32 = (@32/@14) */
  w32 /= w14;
  /* #215: @32 = (@32*@3) */
  w32 *= w3;
  /* #216: @29 = (@29-@32) */
  w29 -= w32;
  /* #217: @10 = (@10/@14) */
  w10 /= w14;
  /* #218: @10 = (@10*@0) */
  w10 *= w0;
  /* #219: @29 = (@29-@10) */
  w29 -= w10;
  /* #220: @8 = (@8/@9) */
  w8 /= w9;
  /* #221: @8 = (@8*@30) */
  w8 *= w30;
  /* #222: @29 = (@29+@8) */
  w29 += w8;
  /* #223: @29 = (@29/@14) */
  w29 /= w14;
  /* #224: @5 = (@29*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #225: (@45[1:4] += @5) */
  for (rr=w45+1, ss=w5; rr!=w45+4; rr+=1) *rr += *ss++;
  /* #226: @35 = mac(@24,@45,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w24+j, tt=w45+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #227: (@34[:8] += @35) */
  for (rr=w34+0, ss=w35; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #228: output[1][0] = @34 */
  casadi_copy(w34, 14, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 470;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
