/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[7],i1[],i2[],i3[13])->(o0,o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, *w2=w+5, *w3=w+18, w4, w5, w6, w7, w8, w9, w10, *w11=w+28, *w12=w+35, *w13=w+38, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, *w31=w+64, *w32=w+67, *w33=w+70, *w34=w+79, w35, w36, w37, w38, w39, w40;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 13, w2);
  /* #3: @3 = @2[:3] */
  for (rr=w3, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #5: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #6: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #7: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #8: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #9: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #10: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #11: @11 = vertcat(@4, @5, @6, @7, @8, @9, @10) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @12 = @11[:3] */
  for (rr=w12, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #13: @3 = (@3-@12) */
  for (i=0, rr=w3, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @12 = @3' */
  casadi_copy(w3, 3, w12);
  /* #15: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #16: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #17: (@13[0] = @4) */
  for (rr=w13+0, ss=(&w4); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #18: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #19: (@13[4] = @4) */
  for (rr=w13+4, ss=(&w4); rr!=w13+5; rr+=1) *rr = *ss++;
  /* #20: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #21: (@13[8] = @4) */
  for (rr=w13+8, ss=(&w4); rr!=w13+9; rr+=1) *rr = *ss++;
  /* #22: @1 = mac(@12,@13,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #23: @0 = mac(@1,@3,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #24: @4 = 0 */
  w4 = 0.;
  /* #25: @12 = zeros(1x3) */
  casadi_clear(w12, 3);
  /* #26: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #27: @6 = (@5*@7) */
  w6  = (w5*w7);
  /* #28: @14 = @2[4] */
  for (rr=(&w14), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #29: @15 = (@14*@8) */
  w15  = (w14*w8);
  /* #30: @6 = (@6+@15) */
  w6 += w15;
  /* #31: @15 = @2[5] */
  for (rr=(&w15), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@15*@9) */
  w16  = (w15*w9);
  /* #33: @6 = (@6+@16) */
  w6 += w16;
  /* #34: @16 = @2[6] */
  for (rr=(&w16), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #35: @17 = (@16*@10) */
  w17  = (w16*w10);
  /* #36: @6 = (@6+@17) */
  w6 += w17;
  /* #37: @17 = @2[3] */
  for (rr=(&w17), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #38: @18 = (@17*@8) */
  w18  = (w17*w8);
  /* #39: @19 = @2[4] */
  for (rr=(&w19), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #40: @20 = (@19*@7) */
  w20  = (w19*w7);
  /* #41: @18 = (@18-@20) */
  w18 -= w20;
  /* #42: @20 = @2[6] */
  for (rr=(&w20), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #43: @21 = (@20*@9) */
  w21  = (w20*w9);
  /* #44: @18 = (@18+@21) */
  w18 += w21;
  /* #45: @21 = @2[5] */
  for (rr=(&w21), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #46: @22 = (@21*@10) */
  w22  = (w21*w10);
  /* #47: @18 = (@18-@22) */
  w18 -= w22;
  /* #48: @22 = (@6*@18) */
  w22  = (w6*w18);
  /* #49: @23 = @2[5] */
  for (rr=(&w23), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #50: @24 = (@23*@7) */
  w24  = (w23*w7);
  /* #51: @24 = (-@24) */
  w24 = (- w24 );
  /* #52: @25 = @2[6] */
  for (rr=(&w25), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #53: @26 = (@25*@8) */
  w26  = (w25*w8);
  /* #54: @24 = (@24-@26) */
  w24 -= w26;
  /* #55: @26 = @2[3] */
  for (rr=(&w26), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #56: @27 = (@26*@9) */
  w27  = (w26*w9);
  /* #57: @24 = (@24+@27) */
  w24 += w27;
  /* #58: @27 = @2[4] */
  for (rr=(&w27), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #59: @28 = (@27*@10) */
  w28  = (w27*w10);
  /* #60: @24 = (@24+@28) */
  w24 += w28;
  /* #61: @28 = @2[5] */
  for (rr=(&w28), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #62: @8 = (@28*@8) */
  w8  = (w28*w8);
  /* #63: @29 = @2[6] */
  for (rr=(&w29), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #64: @7 = (@29*@7) */
  w7  = (w29*w7);
  /* #65: @8 = (@8-@7) */
  w8 -= w7;
  /* #66: @7 = @2[4] */
  for (rr=(&w7), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #67: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #68: @8 = (@8-@9) */
  w8 -= w9;
  /* #69: @9 = @2[3] */
  for (rr=(&w9), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #70: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #71: @8 = (@8+@10) */
  w8 += w10;
  /* #72: @10 = (@24*@8) */
  w10  = (w24*w8);
  /* #73: @22 = (@22-@10) */
  w22 -= w10;
  /* #74: @10 = (@6*@24) */
  w10  = (w6*w24);
  /* #75: @30 = (@18*@8) */
  w30  = (w18*w8);
  /* #76: @10 = (@10+@30) */
  w10 += w30;
  /* #77: @31 = vertcat(@22, @10, @8) */
  rr=w31;
  *rr++ = w22;
  *rr++ = w10;
  *rr++ = w8;
  /* #78: @22 = 0.001 */
  w22 = 1.0000000000000000e-03;
  /* #79: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #80: @30 = sq(@8) */
  w30 = casadi_sq( w8 );
  /* #81: @10 = (@10+@30) */
  w10 += w30;
  /* #82: @22 = (@22+@10) */
  w22 += w10;
  /* #83: @22 = sqrt(@22) */
  w22 = sqrt( w22 );
  /* #84: @31 = (@31/@22) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w22;
  /* #85: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #86: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #87: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #88: (@33[0] = @10) */
  for (rr=w33+0, ss=(&w10); rr!=w33+1; rr+=1) *rr = *ss++;
  /* #89: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #90: (@33[4] = @10) */
  for (rr=w33+4, ss=(&w10); rr!=w33+5; rr+=1) *rr = *ss++;
  /* #91: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #92: (@33[8] = @10) */
  for (rr=w33+8, ss=(&w10); rr!=w33+9; rr+=1) *rr = *ss++;
  /* #93: @12 = mac(@32,@33,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #94: @4 = mac(@12,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #95: @0 = (@0+@4) */
  w0 += w4;
  /* #96: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #97: @11 = zeros(7x1) */
  casadi_clear(w11, 7);
  /* #98: @1 = @1' */
  /* #99: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #100: @3 = @3' */
  /* #101: @34 = @13' */
  for (i=0, rr=w34, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #102: @32 = mac(@3,@34,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #103: @32 = @32' */
  /* #104: @1 = (@1+@32) */
  for (i=0, rr=w1, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #105: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #106: (@11[:3] += @1) */
  for (rr=w11+0, ss=w1; rr!=w11+3; rr+=1) *rr += *ss++;
  /* #107: {@0, @4, @10, @30, @35, @36, @37} = vertsplit(@11) */
  w0 = w11[0];
  w4 = w11[1];
  w10 = w11[2];
  w30 = w11[3];
  w35 = w11[4];
  w36 = w11[5];
  w37 = w11[6];
  /* #108: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #109: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #110: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #111: @12 = @12' */
  /* #112: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #113: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #114: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #115: @1 = mac(@32,@34,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #116: @1 = @1' */
  /* #117: @12 = (@12+@1) */
  for (i=0, rr=w12, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #118: @1 = (@12/@22) */
  for (i=0, rr=w1, cr=w12; i<3; ++i) (*rr++)  = ((*cr++)/w22);
  /* #119: {@10, @4, @0} = vertsplit(@1) */
  w10 = w1[0];
  w4 = w1[1];
  w0 = w1[2];
  /* #120: @38 = (@6*@4) */
  w38  = (w6*w4);
  /* #121: @39 = (@8*@10) */
  w39  = (w8*w10);
  /* #122: @38 = (@38-@39) */
  w38 -= w39;
  /* #123: @23 = (@23*@38) */
  w23 *= w38;
  /* #124: @23 = (-@23) */
  w23 = (- w23 );
  /* #125: @39 = (2.*@8) */
  w39 = (2.* w8 );
  /* #126: @31 = (@31/@22) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w22;
  /* #127: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #128: @40 = dot(@31, @12) */
  w40 = casadi_dot(3, w31, w12);
  /* #129: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #130: @40 = (@40/@22) */
  w40 /= w22;
  /* #131: @39 = (@39*@40) */
  w39 *= w40;
  /* #132: @39 = (@39+@0) */
  w39 += w0;
  /* #133: @0 = (@18*@4) */
  w0  = (w18*w4);
  /* #134: @39 = (@39+@0) */
  w39 += w0;
  /* #135: @0 = (@24*@10) */
  w0  = (w24*w10);
  /* #136: @39 = (@39-@0) */
  w39 -= w0;
  /* #137: @29 = (@29*@39) */
  w29 *= w39;
  /* #138: @23 = (@23-@29) */
  w23 -= w29;
  /* #139: @8 = (@8*@4) */
  w8 *= w4;
  /* #140: @29 = (@6*@10) */
  w29  = (w6*w10);
  /* #141: @8 = (@8+@29) */
  w8 += w29;
  /* #142: @19 = (@19*@8) */
  w19 *= w8;
  /* #143: @23 = (@23-@19) */
  w23 -= w19;
  /* #144: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #145: @6 = (@6*@40) */
  w6 *= w40;
  /* #146: @24 = (@24*@4) */
  w24 *= w4;
  /* #147: @6 = (@6+@24) */
  w6 += w24;
  /* #148: @18 = (@18*@10) */
  w18 *= w10;
  /* #149: @6 = (@6+@18) */
  w6 += w18;
  /* #150: @5 = (@5*@6) */
  w5 *= w6;
  /* #151: @23 = (@23+@5) */
  w23 += w5;
  /* #152: @23 = (@23+@30) */
  w23 += w30;
  /* #153: output[1][3] = @23 */
  if (res[1]) res[1][3] = w23;
  /* #154: @28 = (@28*@39) */
  w28 *= w39;
  /* #155: @25 = (@25*@38) */
  w25 *= w38;
  /* #156: @28 = (@28-@25) */
  w28 -= w25;
  /* #157: @17 = (@17*@8) */
  w17 *= w8;
  /* #158: @28 = (@28+@17) */
  w28 += w17;
  /* #159: @14 = (@14*@6) */
  w14 *= w6;
  /* #160: @28 = (@28+@14) */
  w28 += w14;
  /* #161: @28 = (@28+@35) */
  w28 += w35;
  /* #162: output[1][4] = @28 */
  if (res[1]) res[1][4] = w28;
  /* #163: @26 = (@26*@38) */
  w26 *= w38;
  /* #164: @7 = (@7*@39) */
  w7 *= w39;
  /* #165: @26 = (@26-@7) */
  w26 -= w7;
  /* #166: @20 = (@20*@8) */
  w20 *= w8;
  /* #167: @26 = (@26+@20) */
  w26 += w20;
  /* #168: @15 = (@15*@6) */
  w15 *= w6;
  /* #169: @26 = (@26+@15) */
  w26 += w15;
  /* #170: @26 = (@26+@36) */
  w26 += w36;
  /* #171: output[1][5] = @26 */
  if (res[1]) res[1][5] = w26;
  /* #172: @9 = (@9*@39) */
  w9 *= w39;
  /* #173: @27 = (@27*@38) */
  w27 *= w38;
  /* #174: @9 = (@9+@27) */
  w9 += w27;
  /* #175: @21 = (@21*@8) */
  w21 *= w8;
  /* #176: @9 = (@9-@21) */
  w9 -= w21;
  /* #177: @16 = (@16*@6) */
  w16 *= w6;
  /* #178: @9 = (@9+@16) */
  w9 += w16;
  /* #179: @9 = (@9+@37) */
  w9 += w37;
  /* #180: output[1][6] = @9 */
  if (res[1]) res[1][6] = w9;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 94;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
