/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* quadrotor_cost_ext_cost_0_fun_jac:(i0[7],i1[6],i2[],i3[13])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, *w2=w+5, *w3=w+18, w4, w5, w6, w7, w8, w9, w10, *w11=w+28, *w12=w+35, *w13=w+38, *w14=w+47, w15, w16, w17, w18, *w19=w+57, *w20=w+63, *w21=w+69, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w35=w+118, *w36=w+121, *w37=w+124, *w38=w+133, w39, w40, *w41=w+171, w42, w43, w44, w45;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 13, w2);
  /* #3: @3 = @2[:3] */
  for (rr=w3, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #5: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #6: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #7: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #8: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #9: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #10: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #11: @11 = vertcat(@4, @5, @6, @7, @8, @9, @10) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @12 = @11[:3] */
  for (rr=w12, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #13: @3 = (@3-@12) */
  for (i=0, rr=w3, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @12 = @3' */
  casadi_copy(w3, 3, w12);
  /* #15: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #16: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #17: (@13[0] = @4) */
  for (rr=w13+0, ss=(&w4); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #18: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #19: (@13[4] = @4) */
  for (rr=w13+4, ss=(&w4); rr!=w13+5; rr+=1) *rr = *ss++;
  /* #20: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #21: (@13[8] = @4) */
  for (rr=w13+8, ss=(&w4); rr!=w13+9; rr+=1) *rr = *ss++;
  /* #22: @1 = mac(@12,@13,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #23: @0 = mac(@1,@3,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #24: @4 = 0 */
  w4 = 0.;
  /* #25: @14 = zeros(1x6) */
  casadi_clear(w14, 6);
  /* #26: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #27: @6 = input[1][1] */
  w6 = arg[1] ? arg[1][1] : 0;
  /* #28: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #29: @16 = input[1][3] */
  w16 = arg[1] ? arg[1][3] : 0;
  /* #30: @17 = input[1][4] */
  w17 = arg[1] ? arg[1][4] : 0;
  /* #31: @18 = input[1][5] */
  w18 = arg[1] ? arg[1][5] : 0;
  /* #32: @19 = vertcat(@5, @6, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #33: @20 = @19' */
  casadi_copy(w19, 6, w20);
  /* #34: @21 = zeros(6x6) */
  casadi_clear(w21, 36);
  /* #35: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #36: (@21[0] = @5) */
  for (rr=w21+0, ss=(&w5); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #37: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #38: (@21[7] = @5) */
  for (rr=w21+7, ss=(&w5); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #39: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #40: (@21[14] = @5) */
  for (rr=w21+14, ss=(&w5); rr!=w21+15; rr+=1) *rr = *ss++;
  /* #41: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #42: (@21[21] = @5) */
  for (rr=w21+21, ss=(&w5); rr!=w21+22; rr+=1) *rr = *ss++;
  /* #43: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #44: (@21[28] = @5) */
  for (rr=w21+28, ss=(&w5); rr!=w21+29; rr+=1) *rr = *ss++;
  /* #45: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #46: (@21[35] = @5) */
  for (rr=w21+35, ss=(&w5); rr!=w21+36; rr+=1) *rr = *ss++;
  /* #47: @14 = mac(@20,@21,@14) */
  for (i=0, rr=w14; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #48: @4 = mac(@14,@19,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w19+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #49: @0 = (@0+@4) */
  w0 += w4;
  /* #50: @4 = 0 */
  w4 = 0.;
  /* #51: @12 = zeros(1x3) */
  casadi_clear(w12, 3);
  /* #52: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #53: @6 = (@5*@7) */
  w6  = (w5*w7);
  /* #54: @15 = @2[4] */
  for (rr=(&w15), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #55: @16 = (@15*@8) */
  w16  = (w15*w8);
  /* #56: @6 = (@6+@16) */
  w6 += w16;
  /* #57: @16 = @2[5] */
  for (rr=(&w16), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #58: @17 = (@16*@9) */
  w17  = (w16*w9);
  /* #59: @6 = (@6+@17) */
  w6 += w17;
  /* #60: @17 = @2[6] */
  for (rr=(&w17), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #61: @18 = (@17*@10) */
  w18  = (w17*w10);
  /* #62: @6 = (@6+@18) */
  w6 += w18;
  /* #63: @18 = @2[3] */
  for (rr=(&w18), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #64: @22 = (@18*@8) */
  w22  = (w18*w8);
  /* #65: @23 = @2[4] */
  for (rr=(&w23), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #66: @24 = (@23*@7) */
  w24  = (w23*w7);
  /* #67: @22 = (@22-@24) */
  w22 -= w24;
  /* #68: @24 = @2[6] */
  for (rr=(&w24), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #69: @25 = (@24*@9) */
  w25  = (w24*w9);
  /* #70: @22 = (@22+@25) */
  w22 += w25;
  /* #71: @25 = @2[5] */
  for (rr=(&w25), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #72: @26 = (@25*@10) */
  w26  = (w25*w10);
  /* #73: @22 = (@22-@26) */
  w22 -= w26;
  /* #74: @26 = (@6*@22) */
  w26  = (w6*w22);
  /* #75: @27 = @2[5] */
  for (rr=(&w27), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #76: @28 = (@27*@7) */
  w28  = (w27*w7);
  /* #77: @28 = (-@28) */
  w28 = (- w28 );
  /* #78: @29 = @2[6] */
  for (rr=(&w29), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #79: @30 = (@29*@8) */
  w30  = (w29*w8);
  /* #80: @28 = (@28-@30) */
  w28 -= w30;
  /* #81: @30 = @2[3] */
  for (rr=(&w30), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #82: @31 = (@30*@9) */
  w31  = (w30*w9);
  /* #83: @28 = (@28+@31) */
  w28 += w31;
  /* #84: @31 = @2[4] */
  for (rr=(&w31), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #85: @32 = (@31*@10) */
  w32  = (w31*w10);
  /* #86: @28 = (@28+@32) */
  w28 += w32;
  /* #87: @32 = @2[5] */
  for (rr=(&w32), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #88: @8 = (@32*@8) */
  w8  = (w32*w8);
  /* #89: @33 = @2[6] */
  for (rr=(&w33), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #90: @7 = (@33*@7) */
  w7  = (w33*w7);
  /* #91: @8 = (@8-@7) */
  w8 -= w7;
  /* #92: @7 = @2[4] */
  for (rr=(&w7), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #93: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #94: @8 = (@8-@9) */
  w8 -= w9;
  /* #95: @9 = @2[3] */
  for (rr=(&w9), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #96: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #97: @8 = (@8+@10) */
  w8 += w10;
  /* #98: @10 = (@28*@8) */
  w10  = (w28*w8);
  /* #99: @26 = (@26-@10) */
  w26 -= w10;
  /* #100: @10 = (@6*@28) */
  w10  = (w6*w28);
  /* #101: @34 = (@22*@8) */
  w34  = (w22*w8);
  /* #102: @10 = (@10+@34) */
  w10 += w34;
  /* #103: @35 = vertcat(@26, @10, @8) */
  rr=w35;
  *rr++ = w26;
  *rr++ = w10;
  *rr++ = w8;
  /* #104: @26 = 0.001 */
  w26 = 1.0000000000000000e-03;
  /* #105: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #106: @34 = sq(@8) */
  w34 = casadi_sq( w8 );
  /* #107: @10 = (@10+@34) */
  w10 += w34;
  /* #108: @26 = (@26+@10) */
  w26 += w10;
  /* #109: @26 = sqrt(@26) */
  w26 = sqrt( w26 );
  /* #110: @35 = (@35/@26) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w26;
  /* #111: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #112: @37 = zeros(3x3) */
  casadi_clear(w37, 9);
  /* #113: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #114: (@37[0] = @10) */
  for (rr=w37+0, ss=(&w10); rr!=w37+1; rr+=1) *rr = *ss++;
  /* #115: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #116: (@37[4] = @10) */
  for (rr=w37+4, ss=(&w10); rr!=w37+5; rr+=1) *rr = *ss++;
  /* #117: @10 = 60.5 */
  w10 = 6.0500000000000000e+01;
  /* #118: (@37[8] = @10) */
  for (rr=w37+8, ss=(&w10); rr!=w37+9; rr+=1) *rr = *ss++;
  /* #119: @12 = mac(@36,@37,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @4 = mac(@12,@35,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #121: @0 = (@0+@4) */
  w0 += w4;
  /* #122: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #123: @14 = @14' */
  /* #124: @20 = zeros(1x6) */
  casadi_clear(w20, 6);
  /* #125: @19 = @19' */
  /* #126: @38 = @21' */
  for (i=0, rr=w38, cs=w21; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #127: @20 = mac(@19,@38,@20) */
  for (i=0, rr=w20; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w38+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #128: @20 = @20' */
  /* #129: @14 = (@14+@20) */
  for (i=0, rr=w14, cs=w20; i<6; ++i) (*rr++) += (*cs++);
  /* #130: {@0, @4, @10, @34, @39, @40} = vertsplit(@14) */
  w0 = w14[0];
  w4 = w14[1];
  w10 = w14[2];
  w34 = w14[3];
  w39 = w14[4];
  w40 = w14[5];
  /* #131: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #132: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #133: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #134: output[1][3] = @34 */
  if (res[1]) res[1][3] = w34;
  /* #135: output[1][4] = @39 */
  if (res[1]) res[1][4] = w39;
  /* #136: output[1][5] = @40 */
  if (res[1]) res[1][5] = w40;
  /* #137: @11 = zeros(7x1) */
  casadi_clear(w11, 7);
  /* #138: @1 = @1' */
  /* #139: @36 = zeros(1x3) */
  casadi_clear(w36, 3);
  /* #140: @3 = @3' */
  /* #141: @41 = @13' */
  for (i=0, rr=w41, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #142: @36 = mac(@3,@41,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #143: @36 = @36' */
  /* #144: @1 = (@1+@36) */
  for (i=0, rr=w1, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #145: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #146: (@11[:3] += @1) */
  for (rr=w11+0, ss=w1; rr!=w11+3; rr+=1) *rr += *ss++;
  /* #147: {@40, @39, @34, @10, @4, @0, @42} = vertsplit(@11) */
  w40 = w11[0];
  w39 = w11[1];
  w34 = w11[2];
  w10 = w11[3];
  w4 = w11[4];
  w0 = w11[5];
  w42 = w11[6];
  /* #148: output[1][6] = @40 */
  if (res[1]) res[1][6] = w40;
  /* #149: output[1][7] = @39 */
  if (res[1]) res[1][7] = w39;
  /* #150: output[1][8] = @34 */
  if (res[1]) res[1][8] = w34;
  /* #151: @12 = @12' */
  /* #152: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #153: @36 = @35' */
  casadi_copy(w35, 3, w36);
  /* #154: @41 = @37' */
  for (i=0, rr=w41, cs=w37; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #155: @1 = mac(@36,@41,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #156: @1 = @1' */
  /* #157: @12 = (@12+@1) */
  for (i=0, rr=w12, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #158: @1 = (@12/@26) */
  for (i=0, rr=w1, cr=w12; i<3; ++i) (*rr++)  = ((*cr++)/w26);
  /* #159: {@34, @39, @40} = vertsplit(@1) */
  w34 = w1[0];
  w39 = w1[1];
  w40 = w1[2];
  /* #160: @43 = (@6*@39) */
  w43  = (w6*w39);
  /* #161: @44 = (@8*@34) */
  w44  = (w8*w34);
  /* #162: @43 = (@43-@44) */
  w43 -= w44;
  /* #163: @27 = (@27*@43) */
  w27 *= w43;
  /* #164: @27 = (-@27) */
  w27 = (- w27 );
  /* #165: @44 = (2.*@8) */
  w44 = (2.* w8 );
  /* #166: @35 = (@35/@26) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w26;
  /* #167: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #168: @45 = dot(@35, @12) */
  w45 = casadi_dot(3, w35, w12);
  /* #169: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #170: @45 = (@45/@26) */
  w45 /= w26;
  /* #171: @44 = (@44*@45) */
  w44 *= w45;
  /* #172: @44 = (@44+@40) */
  w44 += w40;
  /* #173: @40 = (@22*@39) */
  w40  = (w22*w39);
  /* #174: @44 = (@44+@40) */
  w44 += w40;
  /* #175: @40 = (@28*@34) */
  w40  = (w28*w34);
  /* #176: @44 = (@44-@40) */
  w44 -= w40;
  /* #177: @33 = (@33*@44) */
  w33 *= w44;
  /* #178: @27 = (@27-@33) */
  w27 -= w33;
  /* #179: @8 = (@8*@39) */
  w8 *= w39;
  /* #180: @33 = (@6*@34) */
  w33  = (w6*w34);
  /* #181: @8 = (@8+@33) */
  w8 += w33;
  /* #182: @23 = (@23*@8) */
  w23 *= w8;
  /* #183: @27 = (@27-@23) */
  w27 -= w23;
  /* #184: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #185: @6 = (@6*@45) */
  w6 *= w45;
  /* #186: @28 = (@28*@39) */
  w28 *= w39;
  /* #187: @6 = (@6+@28) */
  w6 += w28;
  /* #188: @22 = (@22*@34) */
  w22 *= w34;
  /* #189: @6 = (@6+@22) */
  w6 += w22;
  /* #190: @5 = (@5*@6) */
  w5 *= w6;
  /* #191: @27 = (@27+@5) */
  w27 += w5;
  /* #192: @27 = (@27+@10) */
  w27 += w10;
  /* #193: output[1][9] = @27 */
  if (res[1]) res[1][9] = w27;
  /* #194: @32 = (@32*@44) */
  w32 *= w44;
  /* #195: @29 = (@29*@43) */
  w29 *= w43;
  /* #196: @32 = (@32-@29) */
  w32 -= w29;
  /* #197: @18 = (@18*@8) */
  w18 *= w8;
  /* #198: @32 = (@32+@18) */
  w32 += w18;
  /* #199: @15 = (@15*@6) */
  w15 *= w6;
  /* #200: @32 = (@32+@15) */
  w32 += w15;
  /* #201: @32 = (@32+@4) */
  w32 += w4;
  /* #202: output[1][10] = @32 */
  if (res[1]) res[1][10] = w32;
  /* #203: @30 = (@30*@43) */
  w30 *= w43;
  /* #204: @7 = (@7*@44) */
  w7 *= w44;
  /* #205: @30 = (@30-@7) */
  w30 -= w7;
  /* #206: @24 = (@24*@8) */
  w24 *= w8;
  /* #207: @30 = (@30+@24) */
  w30 += w24;
  /* #208: @16 = (@16*@6) */
  w16 *= w6;
  /* #209: @30 = (@30+@16) */
  w30 += w16;
  /* #210: @30 = (@30+@0) */
  w30 += w0;
  /* #211: output[1][11] = @30 */
  if (res[1]) res[1][11] = w30;
  /* #212: @9 = (@9*@44) */
  w9 *= w44;
  /* #213: @31 = (@31*@43) */
  w31 *= w43;
  /* #214: @9 = (@9+@31) */
  w9 += w31;
  /* #215: @25 = (@25*@8) */
  w25 *= w8;
  /* #216: @9 = (@9-@25) */
  w9 -= w25;
  /* #217: @17 = (@17*@6) */
  w17 *= w6;
  /* #218: @9 = (@9+@17) */
  w9 += w17;
  /* #219: @9 = (@9+@42) */
  w9 += w42;
  /* #220: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 184;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
