/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* quadrotor_cost_ext_cost_0_fun:(i0[7],i1[6],i2[],i3[13])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, *w2=w+5, *w3=w+18, w4, w5, w6, w7, w8, w9, w10, *w11=w+28, *w12=w+35, *w13=w+38, *w14=w+47, w15, w16, w17, w18, *w19=w+57, *w20=w+63, *w21=w+69;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 13, w2);
  /* #3: @3 = @2[:3] */
  for (rr=w3, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #5: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #6: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #7: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #8: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #9: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #10: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #11: @11 = vertcat(@4, @5, @6, @7, @8, @9, @10) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @12 = @11[:3] */
  for (rr=w12, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #13: @3 = (@3-@12) */
  for (i=0, rr=w3, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: @12 = @3' */
  casadi_copy(w3, 3, w12);
  /* #15: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #16: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #17: (@13[0] = @4) */
  for (rr=w13+0, ss=(&w4); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #18: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #19: (@13[4] = @4) */
  for (rr=w13+4, ss=(&w4); rr!=w13+5; rr+=1) *rr = *ss++;
  /* #20: @4 = 10.5 */
  w4 = 1.0500000000000000e+01;
  /* #21: (@13[8] = @4) */
  for (rr=w13+8, ss=(&w4); rr!=w13+9; rr+=1) *rr = *ss++;
  /* #22: @1 = mac(@12,@13,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #23: @0 = mac(@1,@3,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #24: @4 = 0 */
  w4 = 0.;
  /* #25: @14 = zeros(1x6) */
  casadi_clear(w14, 6);
  /* #26: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #27: @6 = input[1][1] */
  w6 = arg[1] ? arg[1][1] : 0;
  /* #28: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #29: @16 = input[1][3] */
  w16 = arg[1] ? arg[1][3] : 0;
  /* #30: @17 = input[1][4] */
  w17 = arg[1] ? arg[1][4] : 0;
  /* #31: @18 = input[1][5] */
  w18 = arg[1] ? arg[1][5] : 0;
  /* #32: @19 = vertcat(@5, @6, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #33: @20 = @19' */
  casadi_copy(w19, 6, w20);
  /* #34: @21 = zeros(6x6) */
  casadi_clear(w21, 36);
  /* #35: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #36: (@21[0] = @5) */
  for (rr=w21+0, ss=(&w5); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #37: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #38: (@21[7] = @5) */
  for (rr=w21+7, ss=(&w5); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #39: @5 = 0.142857 */
  w5 = 1.4285714285714285e-01;
  /* #40: (@21[14] = @5) */
  for (rr=w21+14, ss=(&w5); rr!=w21+15; rr+=1) *rr = *ss++;
  /* #41: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #42: (@21[21] = @5) */
  for (rr=w21+21, ss=(&w5); rr!=w21+22; rr+=1) *rr = *ss++;
  /* #43: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #44: (@21[28] = @5) */
  for (rr=w21+28, ss=(&w5); rr!=w21+29; rr+=1) *rr = *ss++;
  /* #45: @5 = 0.2 */
  w5 = 2.0000000000000001e-01;
  /* #46: (@21[35] = @5) */
  for (rr=w21+35, ss=(&w5); rr!=w21+36; rr+=1) *rr = *ss++;
  /* #47: @14 = mac(@20,@21,@14) */
  for (i=0, rr=w14; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #48: @4 = mac(@14,@19,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w19+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #49: @0 = (@0+@4) */
  w0 += w4;
  /* #50: @4 = 0 */
  w4 = 0.;
  /* #51: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #52: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #53: @5 = (@5*@7) */
  w5 *= w7;
  /* #54: @6 = @2[4] */
  for (rr=(&w6), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #55: @6 = (@6*@8) */
  w6 *= w8;
  /* #56: @5 = (@5+@6) */
  w5 += w6;
  /* #57: @6 = @2[5] */
  for (rr=(&w6), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #58: @6 = (@6*@9) */
  w6 *= w9;
  /* #59: @5 = (@5+@6) */
  w5 += w6;
  /* #60: @6 = @2[6] */
  for (rr=(&w6), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #61: @6 = (@6*@10) */
  w6 *= w10;
  /* #62: @5 = (@5+@6) */
  w5 += w6;
  /* #63: @6 = @2[3] */
  for (rr=(&w6), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #64: @6 = (@6*@8) */
  w6 *= w8;
  /* #65: @15 = @2[4] */
  for (rr=(&w15), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #66: @15 = (@15*@7) */
  w15 *= w7;
  /* #67: @6 = (@6-@15) */
  w6 -= w15;
  /* #68: @15 = @2[6] */
  for (rr=(&w15), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #69: @15 = (@15*@9) */
  w15 *= w9;
  /* #70: @6 = (@6+@15) */
  w6 += w15;
  /* #71: @15 = @2[5] */
  for (rr=(&w15), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #72: @15 = (@15*@10) */
  w15 *= w10;
  /* #73: @6 = (@6-@15) */
  w6 -= w15;
  /* #74: @15 = (@5*@6) */
  w15  = (w5*w6);
  /* #75: @16 = @2[5] */
  for (rr=(&w16), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #76: @16 = (@16*@7) */
  w16 *= w7;
  /* #77: @16 = (-@16) */
  w16 = (- w16 );
  /* #78: @17 = @2[6] */
  for (rr=(&w17), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #79: @17 = (@17*@8) */
  w17 *= w8;
  /* #80: @16 = (@16-@17) */
  w16 -= w17;
  /* #81: @17 = @2[3] */
  for (rr=(&w17), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #82: @17 = (@17*@9) */
  w17 *= w9;
  /* #83: @16 = (@16+@17) */
  w16 += w17;
  /* #84: @17 = @2[4] */
  for (rr=(&w17), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #85: @17 = (@17*@10) */
  w17 *= w10;
  /* #86: @16 = (@16+@17) */
  w16 += w17;
  /* #87: @17 = @2[5] */
  for (rr=(&w17), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #88: @17 = (@17*@8) */
  w17 *= w8;
  /* #89: @8 = @2[6] */
  for (rr=(&w8), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #90: @8 = (@8*@7) */
  w8 *= w7;
  /* #91: @17 = (@17-@8) */
  w17 -= w8;
  /* #92: @8 = @2[4] */
  for (rr=(&w8), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #93: @8 = (@8*@9) */
  w8 *= w9;
  /* #94: @17 = (@17-@8) */
  w17 -= w8;
  /* #95: @8 = @2[3] */
  for (rr=(&w8), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #96: @8 = (@8*@10) */
  w8 *= w10;
  /* #97: @17 = (@17+@8) */
  w17 += w8;
  /* #98: @8 = (@16*@17) */
  w8  = (w16*w17);
  /* #99: @15 = (@15-@8) */
  w15 -= w8;
  /* #100: @16 = (@5*@16) */
  w16  = (w5*w16);
  /* #101: @6 = (@6*@17) */
  w6 *= w17;
  /* #102: @16 = (@16+@6) */
  w16 += w6;
  /* #103: @3 = vertcat(@15, @16, @17) */
  rr=w3;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #104: @15 = 0.001 */
  w15 = 1.0000000000000000e-03;
  /* #105: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #106: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #107: @5 = (@5+@17) */
  w5 += w17;
  /* #108: @15 = (@15+@5) */
  w15 += w5;
  /* #109: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #110: @3 = (@3/@15) */
  for (i=0, rr=w3; i<3; ++i) (*rr++) /= w15;
  /* #111: @12 = @3' */
  casadi_copy(w3, 3, w12);
  /* #112: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #113: @15 = 60.5 */
  w15 = 6.0500000000000000e+01;
  /* #114: (@13[0] = @15) */
  for (rr=w13+0, ss=(&w15); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #115: @15 = 60.5 */
  w15 = 6.0500000000000000e+01;
  /* #116: (@13[4] = @15) */
  for (rr=w13+4, ss=(&w15); rr!=w13+5; rr+=1) *rr = *ss++;
  /* #117: @15 = 60.5 */
  w15 = 6.0500000000000000e+01;
  /* #118: (@13[8] = @15) */
  for (rr=w13+8, ss=(&w15); rr!=w13+9; rr+=1) *rr = *ss++;
  /* #119: @1 = mac(@12,@13,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @4 = mac(@1,@3,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #121: @0 = (@0+@4) */
  w0 += w4;
  /* #122: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
