/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, w3, *w4=w+30, *w5=w+39, *w6=w+42, *w7=w+45, *w8=w+54, *w9=w+63, *w10=w+76, *w11=w+79, *w12=w+82, *w13=w+86, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, *w27=w+102, *w28=w+106, w29, w30, w31, *w32=w+113, *w33=w+117, *w34=w+121, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, *w45=w+134, w46, *w47=w+139, *w48=w+155, *w49=w+171, w50, w51, w52, w53, w54;
  /* #0: @0 = zeros(13x1) */
  casadi_clear(w0, 13);
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #3: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #4: (@2[0] = @3) */
  for (rr=w2+0, ss=(&w3); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #5: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #6: (@2[4] = @3) */
  for (rr=w2+4, ss=(&w3); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #7: @3 = 0.00496 */
  w3 = 4.9600000000000000e-03;
  /* #8: (@2[8] = @3) */
  for (rr=w2+8, ss=(&w3); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #9: @4 = @2' */
  for (i=0, rr=w4, cs=w2; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #10: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #11: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #12: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #13: @7 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w7);
  /* #14: @7 = (@2\@7) */
  rr = w7;
  ss = w2;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #15: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #16: @9 = input[1][0] */
  casadi_copy(arg[1], 13, w9);
  /* #17: {@10, @11, @12, @13} = vertsplit(@9) */
  casadi_copy(w9, 3, w10);
  casadi_copy(w9+3, 3, w11);
  casadi_copy(w9+6, 4, w12);
  casadi_copy(w9+10, 3, w13);
  /* #18: @6 = mac(@8,@13,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #19: @13 = (-@6) */
  for (i=0, rr=w13, cs=w6; i<3; ++i) *rr++ = (- *cs++ );
  /* #20: {@14, @15, @16} = vertsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  /* #21: @17 = (@3*@15) */
  w17  = (w3*w15);
  /* #22: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #23: @19 = (@18*@16) */
  w19  = (w18*w16);
  /* #24: @17 = (@17-@19) */
  w17 -= w19;
  /* #25: (@5[0] += @17) */
  for (rr=w5+0, ss=(&w17); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #26: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #27: @19 = (@17*@16) */
  w19  = (w17*w16);
  /* #28: @20 = (@3*@14) */
  w20  = (w3*w14);
  /* #29: @19 = (@19-@20) */
  w19 -= w20;
  /* #30: (@5[1] += @19) */
  for (rr=w5+1, ss=(&w19); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #31: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #32: @20 = (@17*@15) */
  w20  = (w17*w15);
  /* #33: @19 = (@19-@20) */
  w19 -= w20;
  /* #34: (@5[2] += @19) */
  for (rr=w5+2, ss=(&w19); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #35: @1 = mac(@4,@5,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #36: (@0[10:13] += @1) */
  for (rr=w0+10, ss=w1; rr!=w0+13; rr+=1) *rr += *ss++;
  /* #37: @19 = 10 */
  w19 = 10.;
  /* #38: @20 = 1 */
  w20 = 1.;
  /* #39: @21 = input[0][6] */
  w21 = arg[0] ? arg[0][6] : 0;
  /* #40: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #41: @23 = input[0][7] */
  w23 = arg[0] ? arg[0][7] : 0;
  /* #42: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #43: @22 = (@22+@24) */
  w22 += w24;
  /* #44: @24 = input[0][8] */
  w24 = arg[0] ? arg[0][8] : 0;
  /* #45: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #46: @22 = (@22+@25) */
  w22 += w25;
  /* #47: @25 = input[0][9] */
  w25 = arg[0] ? arg[0][9] : 0;
  /* #48: @26 = sq(@25) */
  w26 = casadi_sq( w25 );
  /* #49: @22 = (@22+@26) */
  w22 += w26;
  /* #50: @20 = (@20-@22) */
  w20 -= w22;
  /* #51: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #52: @27 = (@20*@12) */
  for (i=0, rr=w27, cs=w12; i<4; ++i) (*rr++)  = (w20*(*cs++));
  /* #53: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #54: @20 = input[0][0] */
  w20 = arg[0] ? arg[0][0] : 0;
  /* #55: @22 = input[0][1] */
  w22 = arg[0] ? arg[0][1] : 0;
  /* #56: @26 = input[0][2] */
  w26 = arg[0] ? arg[0][2] : 0;
  /* #57: @29 = input[0][3] */
  w29 = arg[0] ? arg[0][3] : 0;
  /* #58: @30 = input[0][4] */
  w30 = arg[0] ? arg[0][4] : 0;
  /* #59: @31 = input[0][5] */
  w31 = arg[0] ? arg[0][5] : 0;
  /* #60: @9 = vertcat(@20, @22, @26, @29, @30, @31, @21, @23, @24, @25, @17, @18, @3) */
  rr=w9;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w26;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w3;
  /* #61: @32 = @9[6:10] */
  for (rr=w32, ss=w9+6; ss!=w9+10; ss+=1) *rr++ = *ss;
  /* #62: @20 = 0 */
  w20 = 0.;
  /* #63: @33 = @32' */
  casadi_copy(w32, 4, w33);
  /* #64: @20 = mac(@33,@32,@20) */
  for (i=0, rr=(&w20); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w32+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #65: @33 = (@32/@20) */
  for (i=0, rr=w33, cr=w32; i<4; ++i) (*rr++)  = ((*cr++)/w20);
  /* #66: @22 = @33[3] */
  for (rr=(&w22), ss=w33+3; ss!=w33+4; ss+=1) *rr++ = *ss;
  /* #67: @26 = (2.*@22) */
  w26 = (2.* w22 );
  /* #68: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #69: @29 = input[2][0] */
  w29 = arg[2] ? arg[2][0] : 0;
  /* #70: @1 = (@29*@11) */
  for (i=0, rr=w1, cs=w11; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #71: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #72: @29 = 1 */
  w29 = 1.;
  /* #73: (@5[2] = @29) */
  for (rr=w5+2, ss=(&w29); rr!=w5+3; rr+=1) *rr = *ss++;
  /* #74: @13 = @5' */
  casadi_copy(w5, 3, w13);
  /* #75: @4 = mac(@1,@13,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w13+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #76: @8 = @4' */
  for (i=0, rr=w8, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #77: {@1, @13, @34} = horzsplit(@8) */
  casadi_copy(w8, 3, w1);
  casadi_copy(w8+3, 3, w13);
  casadi_copy(w8+6, 3, w34);
  /* #78: @34 = @34' */
  /* #79: {@29, @30, @31} = horzsplit(@34) */
  w29 = w34[0];
  w30 = w34[1];
  w31 = w34[2];
  /* #80: @26 = (@26*@31) */
  w26 *= w31;
  /* #81: @35 = @33[2] */
  for (rr=(&w35), ss=w33+2; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #82: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #83: @36 = (@35*@30) */
  w36  = (w35*w30);
  /* #84: @26 = (@26+@36) */
  w26 += w36;
  /* #85: @36 = @33[1] */
  for (rr=(&w36), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #86: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #87: @37 = (@36*@29) */
  w37  = (w36*w29);
  /* #88: @26 = (@26+@37) */
  w26 += w37;
  /* #89: @13 = @13' */
  /* #90: {@37, @38, @39} = horzsplit(@13) */
  w37 = w13[0];
  w38 = w13[1];
  w39 = w13[2];
  /* #91: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #92: @40 = (@35*@39) */
  w40  = (w35*w39);
  /* #93: @26 = (@26+@40) */
  w26 += w40;
  /* #94: @40 = (2.*@22) */
  w40 = (2.* w22 );
  /* #95: @40 = (@40*@38) */
  w40 *= w38;
  /* #96: @26 = (@26-@40) */
  w26 -= w40;
  /* #97: @40 = @33[0] */
  for (rr=(&w40), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #98: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #99: @41 = (@40*@37) */
  w41  = (w40*w37);
  /* #100: @26 = (@26+@41) */
  w26 += w41;
  /* #101: @1 = @1' */
  /* #102: {@41, @42, @43} = horzsplit(@1) */
  w41 = w1[0];
  w42 = w1[1];
  w43 = w1[2];
  /* #103: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #104: @44 = (@36*@43) */
  w44  = (w36*w43);
  /* #105: @26 = (@26+@44) */
  w26 += w44;
  /* #106: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #107: @44 = (@40*@42) */
  w44  = (w40*w42);
  /* #108: @26 = (@26-@44) */
  w26 -= w44;
  /* #109: @44 = (2.*@22) */
  w44 = (2.* w22 );
  /* #110: @44 = (@44*@41) */
  w44 *= w41;
  /* #111: @26 = (@26-@44) */
  w26 -= w44;
  /* #112: (@28[3] += @26) */
  for (rr=w28+3, ss=(&w26); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #113: @26 = (@22*@30) */
  w26  = (w22*w30);
  /* #114: @44 = (2.*@35) */
  w44 = (2.* w35 );
  /* #115: @44 = (@44*@31) */
  w44 *= w31;
  /* #116: @26 = (@26-@44) */
  w26 -= w44;
  /* #117: @44 = (@40*@29) */
  w44  = (w40*w29);
  /* #118: @26 = (@26-@44) */
  w26 -= w44;
  /* #119: @44 = (@22*@39) */
  w44  = (w22*w39);
  /* #120: @26 = (@26+@44) */
  w26 += w44;
  /* #121: @44 = (2.*@35) */
  w44 = (2.* w35 );
  /* #122: @44 = (@44*@38) */
  w44 *= w38;
  /* #123: @26 = (@26+@44) */
  w26 += w44;
  /* #124: @44 = (@36*@37) */
  w44  = (w36*w37);
  /* #125: @26 = (@26+@44) */
  w26 += w44;
  /* #126: @44 = (@40*@43) */
  w44  = (w40*w43);
  /* #127: @26 = (@26+@44) */
  w26 += w44;
  /* #128: @44 = (@36*@42) */
  w44  = (w36*w42);
  /* #129: @26 = (@26+@44) */
  w26 += w44;
  /* #130: @44 = (2.*@35) */
  w44 = (2.* w35 );
  /* #131: @44 = (@44*@41) */
  w44 *= w41;
  /* #132: @26 = (@26-@44) */
  w26 -= w44;
  /* #133: (@28[2] += @26) */
  for (rr=w28+2, ss=(&w26); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #134: @26 = (@40*@30) */
  w26  = (w40*w30);
  /* #135: @44 = (2.*@36) */
  w44 = (2.* w36 );
  /* #136: @44 = (@44*@31) */
  w44 *= w31;
  /* #137: @26 = (@26-@44) */
  w26 -= w44;
  /* #138: @44 = (@22*@29) */
  w44  = (w22*w29);
  /* #139: @26 = (@26+@44) */
  w26 += w44;
  /* #140: @44 = (@40*@39) */
  w44  = (w40*w39);
  /* #141: @26 = (@26-@44) */
  w26 -= w44;
  /* #142: @44 = (2.*@36) */
  w44 = (2.* w36 );
  /* #143: @44 = (@44*@38) */
  w44 *= w38;
  /* #144: @26 = (@26-@44) */
  w26 -= w44;
  /* #145: @44 = (@35*@37) */
  w44  = (w35*w37);
  /* #146: @26 = (@26+@44) */
  w26 += w44;
  /* #147: @44 = (@22*@43) */
  w44  = (w22*w43);
  /* #148: @26 = (@26+@44) */
  w26 += w44;
  /* #149: @44 = (@35*@42) */
  w44  = (w35*w42);
  /* #150: @26 = (@26+@44) */
  w26 += w44;
  /* #151: @44 = (2.*@36) */
  w44 = (2.* w36 );
  /* #152: @44 = (@44*@41) */
  w44 *= w41;
  /* #153: @26 = (@26+@44) */
  w26 += w44;
  /* #154: (@28[1] += @26) */
  for (rr=w28+1, ss=(&w26); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #155: @26 = (2.*@40) */
  w26 = (2.* w40 );
  /* #156: @26 = (@26*@31) */
  w26 *= w31;
  /* #157: @30 = (@36*@30) */
  w30  = (w36*w30);
  /* #158: @26 = (@26+@30) */
  w26 += w30;
  /* #159: @29 = (@35*@29) */
  w29  = (w35*w29);
  /* #160: @26 = (@26-@29) */
  w26 -= w29;
  /* #161: @39 = (@36*@39) */
  w39  = (w36*w39);
  /* #162: @26 = (@26-@39) */
  w26 -= w39;
  /* #163: @39 = (2.*@40) */
  w39 = (2.* w40 );
  /* #164: @39 = (@39*@38) */
  w39 *= w38;
  /* #165: @26 = (@26+@39) */
  w26 += w39;
  /* #166: @37 = (@22*@37) */
  w37  = (w22*w37);
  /* #167: @26 = (@26+@37) */
  w26 += w37;
  /* #168: @43 = (@35*@43) */
  w43  = (w35*w43);
  /* #169: @26 = (@26+@43) */
  w26 += w43;
  /* #170: @42 = (@22*@42) */
  w42  = (w22*w42);
  /* #171: @26 = (@26-@42) */
  w26 -= w42;
  /* #172: @42 = (2.*@40) */
  w42 = (2.* w40 );
  /* #173: @42 = (@42*@41) */
  w42 *= w41;
  /* #174: @26 = (@26+@42) */
  w26 += w42;
  /* #175: (@28[0] += @26) */
  for (rr=w28+0, ss=(&w26); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #176: @45 = (@28/@20) */
  for (i=0, rr=w45, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)/w20);
  /* #177: @27 = (@27+@45) */
  for (i=0, rr=w27, cs=w45; i<4; ++i) (*rr++) += (*cs++);
  /* #178: @33 = (@33/@20) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w20;
  /* #179: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) *rr++ = (- *cs++ );
  /* #180: @20 = dot(@33, @28) */
  w20 = casadi_dot(4, w33, w28);
  /* #181: @33 = (@32*@20) */
  for (i=0, rr=w33, cr=w32; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #182: @27 = (@27+@33) */
  for (i=0, rr=w27, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #183: @33 = @32' */
  casadi_copy(w32, 4, w33);
  /* #184: @33 = (@20*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w20*(*cs++));
  /* #185: @33 = @33' */
  /* #186: @27 = (@27+@33) */
  for (i=0, rr=w27, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #187: (@0[6:10] += @27) */
  for (rr=w0+6, ss=w27; rr!=w0+10; rr+=1) *rr += *ss++;
  /* #188: (@0[3:6] += @10) */
  for (rr=w0+3, ss=w10; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #189: {@20, @26, @42, @41, @43, @37, @39, @38, @29, @30, @31, @44, @46} = vertsplit(@0) */
  w20 = w0[0];
  w26 = w0[1];
  w42 = w0[2];
  w41 = w0[3];
  w43 = w0[4];
  w37 = w0[5];
  w39 = w0[6];
  w38 = w0[7];
  w29 = w0[8];
  w30 = w0[9];
  w31 = w0[10];
  w44 = w0[11];
  w46 = w0[12];
  /* #190: output[0][0] = @20 */
  if (res[0]) res[0][0] = w20;
  /* #191: output[0][1] = @26 */
  if (res[0]) res[0][1] = w26;
  /* #192: output[0][2] = @42 */
  if (res[0]) res[0][2] = w42;
  /* #193: output[0][3] = @41 */
  if (res[0]) res[0][3] = w41;
  /* #194: output[0][4] = @43 */
  if (res[0]) res[0][4] = w43;
  /* #195: output[0][5] = @37 */
  if (res[0]) res[0][5] = w37;
  /* #196: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #197: @37 = 0.5 */
  w37 = 5.0000000000000000e-01;
  /* #198: @27 = (@37*@12) */
  for (i=0, rr=w27, cs=w12; i<4; ++i) (*rr++)  = (w37*(*cs++));
  /* #199: @37 = 0 */
  w37 = 0.;
  /* #200: @33 = vertcat(@37, @17, @18, @3) */
  rr=w33;
  *rr++ = w37;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w3;
  /* #201: @33 = @33' */
  /* #202: @47 = mac(@27,@33,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w27+j, tt=w33+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #203: @48 = @47' */
  for (i=0, rr=w48, cs=w47; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #204: {@33, @28, @45, @49} = horzsplit(@48) */
  casadi_copy(w48, 4, w33);
  casadi_copy(w48+4, 4, w28);
  casadi_copy(w48+8, 4, w45);
  casadi_copy(w48+12, 4, w49);
  /* #205: @49 = @49' */
  /* #206: {@37, @17, @18, @3} = horzsplit(@49) */
  w37 = w49[0];
  w17 = w49[1];
  w18 = w49[2];
  w3 = w49[3];
  /* #207: @43 = (2.*@21) */
  w43 = (2.* w21 );
  /* #208: @41 = dot(@32, @12) */
  w41 = casadi_dot(4, w32, w12);
  /* #209: @19 = (@19*@41) */
  w19 *= w41;
  /* #210: @43 = (@43*@19) */
  w43 *= w19;
  /* #211: @3 = (@3-@43) */
  w3 -= w43;
  /* #212: @45 = @45' */
  /* #213: {@43, @41, @42, @26} = horzsplit(@45) */
  w43 = w45[0];
  w41 = w45[1];
  w42 = w45[2];
  w26 = w45[3];
  /* #214: @3 = (@3+@42) */
  w3 += w42;
  /* #215: @28 = @28' */
  /* #216: {@42, @20, @50, @51} = horzsplit(@28) */
  w42 = w28[0];
  w20 = w28[1];
  w50 = w28[2];
  w51 = w28[3];
  /* #217: @3 = (@3+@20) */
  w3 += w20;
  /* #218: @33 = @33' */
  /* #219: {@20, @52, @53, @54} = horzsplit(@33) */
  w20 = w33[0];
  w52 = w33[1];
  w53 = w33[2];
  w54 = w33[3];
  /* #220: @3 = (@3+@20) */
  w3 += w20;
  /* #221: @3 = (@3+@39) */
  w3 += w39;
  /* #222: output[0][6] = @3 */
  if (res[0]) res[0][6] = w3;
  /* #223: @3 = (2.*@23) */
  w3 = (2.* w23 );
  /* #224: @3 = (@3*@19) */
  w3 *= w19;
  /* #225: @18 = (@18-@3) */
  w18 -= w3;
  /* #226: @18 = (@18-@26) */
  w18 -= w26;
  /* #227: @18 = (@18+@42) */
  w18 += w42;
  /* #228: @18 = (@18-@52) */
  w18 -= w52;
  /* #229: @18 = (@18+@38) */
  w18 += w38;
  /* #230: output[0][7] = @18 */
  if (res[0]) res[0][7] = w18;
  /* #231: @17 = (-@17) */
  w17 = (- w17 );
  /* #232: @18 = (2.*@24) */
  w18 = (2.* w24 );
  /* #233: @18 = (@18*@19) */
  w18 *= w19;
  /* #234: @17 = (@17-@18) */
  w17 -= w18;
  /* #235: @17 = (@17+@43) */
  w17 += w43;
  /* #236: @17 = (@17+@51) */
  w17 += w51;
  /* #237: @17 = (@17-@53) */
  w17 -= w53;
  /* #238: @17 = (@17+@29) */
  w17 += w29;
  /* #239: output[0][8] = @17 */
  if (res[0]) res[0][8] = w17;
  /* #240: @17 = (2.*@25) */
  w17 = (2.* w25 );
  /* #241: @17 = (@17*@19) */
  w17 *= w19;
  /* #242: @37 = (@37-@17) */
  w37 -= w17;
  /* #243: @37 = (@37+@41) */
  w37 += w41;
  /* #244: @37 = (@37-@50) */
  w37 -= w50;
  /* #245: @37 = (@37-@54) */
  w37 -= w54;
  /* #246: @37 = (@37+@30) */
  w37 += w30;
  /* #247: output[0][9] = @37 */
  if (res[0]) res[0][9] = w37;
  /* #248: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #249: @1 = @9[10:13] */
  for (rr=w1, ss=w9+10; ss!=w9+13; ss+=1) *rr++ = *ss;
  /* #250: @10 = mac(@2,@1,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #251: @37 = @10[1] */
  for (rr=(&w37), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #252: @30 = (@37*@16) */
  w30  = (w37*w16);
  /* #253: @54 = @10[2] */
  for (rr=(&w54), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #254: @50 = (@54*@15) */
  w50  = (w54*w15);
  /* #255: @30 = (@30-@50) */
  w30 -= w50;
  /* #256: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #257: @50 = (-@23) */
  w50 = (- w23 );
  /* #258: @41 = (-@24) */
  w41 = (- w24 );
  /* #259: @17 = (-@25) */
  w17 = (- w25 );
  /* #260: @28 = horzcat(@21, @50, @41, @17) */
  rr=w28;
  *rr++ = w21;
  *rr++ = w50;
  *rr++ = w41;
  *rr++ = w17;
  /* #261: @28 = @28' */
  /* #262: @50 = (-@25) */
  w50 = (- w25 );
  /* #263: @45 = horzcat(@23, @21, @50, @24) */
  rr=w45;
  *rr++ = w23;
  *rr++ = w21;
  *rr++ = w50;
  *rr++ = w24;
  /* #264: @45 = @45' */
  /* #265: @50 = (-@23) */
  w50 = (- w23 );
  /* #266: @32 = horzcat(@24, @25, @21, @50) */
  rr=w32;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w21;
  *rr++ = w50;
  /* #267: @32 = @32' */
  /* #268: @24 = (-@24) */
  w24 = (- w24 );
  /* #269: @12 = horzcat(@25, @24, @23, @21) */
  rr=w12;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w21;
  /* #270: @12 = @12' */
  /* #271: @48 = horzcat(@28, @45, @32, @12) */
  rr=w48;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #272: @33 = mac(@48,@27,@33) */
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w48+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #273: {NULL, @25, @24, @23} = vertsplit(@33) */
  w25 = w33[1];
  w24 = w33[2];
  w23 = w33[3];
  /* #274: @30 = (@30+@25) */
  w30 += w25;
  /* #275: @30 = (@30+@31) */
  w30 += w31;
  /* #276: output[0][10] = @30 */
  if (res[0]) res[0][10] = w30;
  /* #277: @54 = (@54*@14) */
  w54 *= w14;
  /* #278: @30 = @10[0] */
  for (rr=(&w30), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #279: @16 = (@30*@16) */
  w16  = (w30*w16);
  /* #280: @54 = (@54-@16) */
  w54 -= w16;
  /* #281: @54 = (@54+@24) */
  w54 += w24;
  /* #282: @54 = (@54+@44) */
  w54 += w44;
  /* #283: output[0][11] = @54 */
  if (res[0]) res[0][11] = w54;
  /* #284: @30 = (@30*@15) */
  w30 *= w15;
  /* #285: @37 = (@37*@14) */
  w37 *= w14;
  /* #286: @30 = (@30-@37) */
  w30 -= w37;
  /* #287: @30 = (@30+@23) */
  w30 += w23;
  /* #288: @30 = (@30+@46) */
  w30 += w46;
  /* #289: output[0][12] = @30 */
  if (res[0]) res[0][12] = w30;
  /* #290: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #291: (@33[1:4] += @6) */
  for (rr=w33+1, ss=w6; rr!=w33+4; rr+=1) *rr += *ss++;
  /* #292: {@30, @46, @23, @37} = vertsplit(@33) */
  w30 = w33[0];
  w46 = w33[1];
  w23 = w33[2];
  w37 = w33[3];
  /* #293: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #294: @14 = sq(@40) */
  w14 = casadi_sq( w40 );
  /* #295: @15 = sq(@36) */
  w15 = casadi_sq( w36 );
  /* #296: @14 = (@14+@15) */
  w14 += w15;
  /* #297: @15 = sq(@35) */
  w15 = casadi_sq( w35 );
  /* #298: @14 = (@14-@15) */
  w14 -= w15;
  /* #299: @15 = sq(@22) */
  w15 = casadi_sq( w22 );
  /* #300: @14 = (@14-@15) */
  w14 -= w15;
  /* #301: @15 = (@36*@35) */
  w15  = (w36*w35);
  /* #302: @54 = (@40*@22) */
  w54  = (w40*w22);
  /* #303: @15 = (@15-@54) */
  w15 -= w54;
  /* #304: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #305: @54 = (@36*@22) */
  w54  = (w36*w22);
  /* #306: @44 = (@40*@35) */
  w44  = (w40*w35);
  /* #307: @54 = (@54+@44) */
  w54 += w44;
  /* #308: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #309: @10 = horzcat(@14, @15, @54) */
  rr=w10;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w54;
  /* #310: @10 = @10' */
  /* #311: @14 = (@36*@35) */
  w14  = (w36*w35);
  /* #312: @15 = (@40*@22) */
  w15  = (w40*w22);
  /* #313: @14 = (@14+@15) */
  w14 += w15;
  /* #314: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #315: @15 = sq(@40) */
  w15 = casadi_sq( w40 );
  /* #316: @54 = sq(@35) */
  w54 = casadi_sq( w35 );
  /* #317: @15 = (@15+@54) */
  w15 += w54;
  /* #318: @54 = sq(@36) */
  w54 = casadi_sq( w36 );
  /* #319: @15 = (@15-@54) */
  w15 -= w54;
  /* #320: @54 = sq(@22) */
  w54 = casadi_sq( w22 );
  /* #321: @15 = (@15-@54) */
  w15 -= w54;
  /* #322: @54 = (@35*@22) */
  w54  = (w35*w22);
  /* #323: @44 = (@40*@36) */
  w44  = (w40*w36);
  /* #324: @54 = (@54-@44) */
  w54 -= w44;
  /* #325: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #326: @1 = horzcat(@14, @15, @54) */
  rr=w1;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w54;
  /* #327: @1 = @1' */
  /* #328: @14 = (@36*@22) */
  w14  = (w36*w22);
  /* #329: @15 = (@40*@35) */
  w15  = (w40*w35);
  /* #330: @14 = (@14-@15) */
  w14 -= w15;
  /* #331: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #332: @15 = (@35*@22) */
  w15  = (w35*w22);
  /* #333: @54 = (@40*@36) */
  w54  = (w40*w36);
  /* #334: @15 = (@15+@54) */
  w15 += w54;
  /* #335: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #336: @40 = sq(@40) */
  w40 = casadi_sq( w40 );
  /* #337: @22 = sq(@22) */
  w22 = casadi_sq( w22 );
  /* #338: @40 = (@40+@22) */
  w40 += w22;
  /* #339: @36 = sq(@36) */
  w36 = casadi_sq( w36 );
  /* #340: @40 = (@40-@36) */
  w40 -= w36;
  /* #341: @35 = sq(@35) */
  w35 = casadi_sq( w35 );
  /* #342: @40 = (@40-@35) */
  w40 -= w35;
  /* #343: @13 = horzcat(@14, @15, @40) */
  rr=w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w40;
  /* #344: @13 = @13' */
  /* #345: @2 = horzcat(@10, @1, @13) */
  rr=w2;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #346: @8 = @2' */
  for (i=0, rr=w8, cs=w2; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #347: @6 = mac(@8,@5,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #348: @14 = dot(@6, @11) */
  w14 = casadi_dot(3, w6, w11);
  /* #349: @30 = (@30+@14) */
  w30 += w14;
  /* #350: output[0][13] = @30 */
  if (res[0]) res[0][13] = w30;
  /* #351: output[0][14] = @46 */
  if (res[0]) res[0][14] = w46;
  /* #352: output[0][15] = @23 */
  if (res[0]) res[0][15] = w23;
  /* #353: output[0][16] = @37 */
  if (res[0]) res[0][16] = w37;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 180;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
