/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[5] = {8, 1, 0, 1, 0};
static const casadi_int casadi_s2[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[14] = {0, 1, 2, 3, 4, 5, 6, 7, 64, 65, 66, 67, 68, 69};
static const casadi_int casadi_s4[14] = {0, 8, 16, 24, 32, 40, 48, 56, 64, 65, 66, 67, 68, 69};
static const casadi_int casadi_s5[5] = {8, 1, 0, 1, 1};
static const casadi_int casadi_s6[5] = {8, 1, 0, 1, 2};
static const casadi_int casadi_s7[5] = {8, 1, 0, 1, 3};
static const casadi_int casadi_s8[5] = {8, 1, 0, 1, 4};
static const casadi_int casadi_s9[5] = {8, 1, 0, 1, 5};
static const casadi_int casadi_s10[5] = {8, 1, 0, 1, 6};
static const casadi_int casadi_s11[5] = {8, 1, 0, 1, 7};
static const casadi_int casadi_s12[87] = {14, 14, 0, 8, 16, 24, 32, 40, 48, 56, 64, 65, 66, 67, 68, 69, 70, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s13[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s14[3] = {0, 0, 0};
static const casadi_int casadi_s15[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s16[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s17[17] = {0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[8] = {1., 0., 0., 0., 0., 0., 0., 0.};
static const casadi_real casadi_c1[64] = {1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.};

/* quadrotor_cost_ext_cost_e_fun_jac_hess:(i0[14],i1[],i2[],i3[18])->(o0,o1[14],o2[14x14,70nz],o3[],o4[0x14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, *w2=w+10, *w3=w+18, w4, *w5=w+27, *w6=w+35, w7, w8, w9, w10, *w11=w+57, w12, w13, *w14=w+63, *w15=w+67, *w16=w+71, *w17=w+75, *w18=w+91, *w19=w+107, *w20=w+139, *w21=w+171, *w22=w+187, *w23=w+219, *w24=w+283, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+355, *w34=w+369, *w35=w+377, *w36=w+441, *w37=w+444, *w38=w+447, *w39=w+450, *w40=w+514, *w41=w+584, *w49=w+591;
  /* #0: @0 = 10 */
  w0 = 10.;
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #3: @3 = [1, 0, 0, 0, 0, 0, 0, 0] */
  casadi_copy(casadi_c0, 8, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #6: @6 = input[3][0] */
  casadi_copy(arg[3], 18, w6);
  /* #7: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #8: @8 = @6[1] */
  for (rr=(&w8), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #9: @9 = @6[2] */
  for (rr=(&w9), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #10: @10 = @6[3] */
  for (rr=(&w10), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w7 = (- w8 );
  /* #14: @12 = @6[0] */
  for (rr=(&w12), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #15: @13 = (-@9) */
  w13 = (- w9 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  for (rr=(&w12), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w8;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  for (rr=(&w13), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  for (rr=(&w10), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #31: @9 = @6[5] */
  for (rr=(&w9), ss=w6+5; ss!=w6+6; ss+=1) *rr++ = *ss;
  /* #32: @7 = @6[6] */
  for (rr=(&w7), ss=w6+6; ss!=w6+7; ss+=1) *rr++ = *ss;
  /* #33: @13 = @6[7] */
  for (rr=(&w13), ss=w6+7; ss!=w6+8; ss+=1) *rr++ = *ss;
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w9 );
  /* #37: @12 = @6[4] */
  for (rr=(&w12), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #38: @8 = (-@7) */
  w8 = (- w7 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w8;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  for (rr=(&w12), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w9;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  for (rr=(&w8), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w7 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #69: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #70: @5 = mac(@24,@34,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w24+j, tt=w34+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #71: @13 = @5[0] */
  for (rr=(&w13), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #72: @4 = (@4<@13) */
  w4  = (w4<w13);
  /* #73: @34 = (@4?@5:0) */
  for (i=0, rr=w34, cs=w5; i<8; ++i) (*rr++)  = (w4?(*cs++):0);
  /* #74: @13 = (!@4) */
  w13 = (! w4 );
  /* #75: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) *rr++ = (- *cs++ );
  /* #76: @5 = (@13?@5:0) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #77: @34 = (@34+@5) */
  for (i=0, rr=w34, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #78: @3 = (@3-@34) */
  for (i=0, rr=w3, cs=w34; i<8; ++i) (*rr++) -= (*cs++);
  /* #79: @34 = @3' */
  casadi_copy(w3, 8, w34);
  /* #80: @35 = 
  [[1, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 64, w35);
  /* #81: @2 = mac(@34,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #82: @1 = mac(@2,@3,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0*@1) */
  w0 *= w1;
  /* #84: @1 = 0 */
  w1 = 0.;
  /* #85: @36 = @33[8:11] */
  for (rr=w36, ss=w33+8; ss!=w33+11; ss+=1) *rr++ = *ss;
  /* #86: @37 = @36' */
  casadi_copy(w36, 3, w37);
  /* #87: @1 = mac(@37,@36,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #88: @0 = (@0+@1) */
  w0 += w1;
  /* #89: @1 = 0 */
  w1 = 0.;
  /* #90: @37 = @33[11:14] */
  for (rr=w37, ss=w33+11; ss!=w33+14; ss+=1) *rr++ = *ss;
  /* #91: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #92: @1 = mac(@38,@37,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #93: @0 = (@0+@1) */
  w0 += w1;
  /* #94: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #95: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #96: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: (@33[11:14] += @37) */
  for (rr=w33+11, ss=w37; rr!=w33+14; rr+=1) *rr += *ss++;
  /* #98: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #99: (@33[8:11] += @36) */
  for (rr=w33+8, ss=w36; rr!=w33+11; rr+=1) *rr += *ss++;
  /* #100: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #101: @0 = 1 */
  w0 = 1.;
  /* #102: @0 = (@13?@0:0) */
  w0  = (w13?w0:0);
  /* #103: @1 = 10 */
  w1 = 10.;
  /* #104: @2 = @2' */
  /* #105: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #106: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #107: @3 = @3' */
  /* #108: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #109: @39 = @35' */
  for (i=0, rr=w39, cs=w35; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #110: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #111: @5 = @5' */
  /* #112: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #113: @5 = (@0*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #114: @7 = 1 */
  w7 = 1.;
  /* #115: @7 = (@4?@7:0) */
  w7  = (w4?w7:0);
  /* #116: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #117: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #118: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #119: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #120: output[1][0] = @33 */
  casadi_copy(w33, 14, res[1]);
  /* #121: @40 = zeros(14x14,70nz) */
  casadi_clear(w40, 70);
  /* #122: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #123: @41 = ones(14x1,7nz) */
  casadi_fill(w41, 7, 1.);
  /* #124: {@10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @8, @12, @9, @25, @26, @27} = vertsplit(@41) */
  w10 = w41[0];
  w8 = w41[1];
  w12 = w41[2];
  w9 = w41[3];
  w25 = w41[4];
  w26 = w41[5];
  w27 = w41[6];
  /* #125: @42 = 00 */
  /* #126: @43 = 00 */
  /* #127: @44 = 00 */
  /* #128: @45 = 00 */
  /* #129: @46 = 00 */
  /* #130: @47 = 00 */
  /* #131: @48 = 00 */
  /* #132: @41 = vertcat(@10, @42, @43, @44, @45, @46, @47, @48, @8, @12, @9, @25, @26, @27) */
  rr=w41;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #133: @36 = @41[4:7] */
  for (rr=w36, ss=w41+4; ss!=w41+7; ss+=1) *rr++ = *ss;
  /* #134: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #135: (@33[11:14] += @36) */
  for (rr=w33+11, ss=w36; rr!=w33+14; rr+=1) *rr += *ss++;
  /* #136: @36 = @41[1:4] */
  for (rr=w36, ss=w41+1; ss!=w41+4; ss+=1) *rr++ = *ss;
  /* #137: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #138: (@33[8:11] += @36) */
  for (rr=w33+8, ss=w36; rr!=w33+11; rr+=1) *rr += *ss++;
  /* #139: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #140: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #141: @8 = 1 */
  w8 = 1.;
  /* #142: @4 = (@4?@8:0) */
  w4  = (w4?w8:0);
  /* #143: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #144: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #145: @2 = mac(@24,@8,@2) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s1, w2, casadi_s0, w, 0);
  /* #146: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #147: @8 = 1 */
  w8 = 1.;
  /* #148: @13 = (@13?@8:0) */
  w13  = (w13?w8:0);
  /* #149: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #150: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #151: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #152: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #153: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #154: @5 = @5' */
  /* #155: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #156: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #157: @3 = @3' */
  /* #158: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #159: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #160: @2 = @2' */
  /* #161: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #162: @2 = (@0*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #163: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #164: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #165: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #166: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #167: (@40[0, 1, 2, 3, 4, 5, 6, 7, 64, 65, 66, 67, 68, 69] = @33) */
  for (cii=casadi_s3, rr=w40, ss=w33; cii!=casadi_s3+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #168: (@40[0, 8, 16, 24, 32, 40, 48, 56, 64, 65, 66, 67, 68, 69] = @33) */
  for (cii=casadi_s4, rr=w40, ss=w33; cii!=casadi_s4+14; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #169: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #170: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #171: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #172: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #173: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #174: {NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #175: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #176: @5 = mac(@24,@8,@5) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s5, w5, casadi_s0, w, 0);
  /* #177: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #178: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #179: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #180: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #181: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #182: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #183: @2 = @2' */
  /* #184: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #185: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #186: @3 = @3' */
  /* #187: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #188: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #189: @5 = @5' */
  /* #190: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #191: @5 = (@0*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #192: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #193: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #194: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #195: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #196: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #197: (@40[8:16] = @34) */
  for (rr=w40+8, ss=w34; rr!=w40+16; rr+=1) *rr = *ss++;
  /* #198: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #199: (@40[1:65:8] = @34) */
  for (rr=w40+1, ss=w34; rr!=w40+65; rr+=8) *rr = *ss++;
  /* #200: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #201: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #202: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #203: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #204: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #205: {NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #206: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #207: @2 = mac(@24,@8,@2) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s6, w2, casadi_s0, w, 0);
  /* #208: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #209: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #210: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #211: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #212: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #213: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #214: @5 = @5' */
  /* #215: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #216: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #217: @3 = @3' */
  /* #218: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #219: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #220: @2 = @2' */
  /* #221: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #222: @2 = (@0*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #223: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #224: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #225: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #226: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #227: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #228: (@40[16:24] = @34) */
  for (rr=w40+16, ss=w34; rr!=w40+24; rr+=1) *rr = *ss++;
  /* #229: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #230: (@40[2:66:8] = @34) */
  for (rr=w40+2, ss=w34; rr!=w40+66; rr+=8) *rr = *ss++;
  /* #231: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #232: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #233: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #234: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #235: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #236: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #237: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #238: @5 = mac(@24,@8,@5) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s7, w5, casadi_s0, w, 0);
  /* #239: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #240: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #241: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #242: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #243: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #244: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #245: @2 = @2' */
  /* #246: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #247: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #248: @3 = @3' */
  /* #249: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #250: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #251: @5 = @5' */
  /* #252: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #253: @5 = (@0*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #254: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #255: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #256: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #257: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #258: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #259: (@40[24:32] = @34) */
  for (rr=w40+24, ss=w34; rr!=w40+32; rr+=1) *rr = *ss++;
  /* #260: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #261: (@40[3:67:8] = @34) */
  for (rr=w40+3, ss=w34; rr!=w40+67; rr+=8) *rr = *ss++;
  /* #262: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #263: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #264: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #265: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #266: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #267: {NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #268: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #269: @2 = mac(@24,@8,@2) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s8, w2, casadi_s0, w, 0);
  /* #270: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #271: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #272: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #273: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #274: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #275: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #276: @5 = @5' */
  /* #277: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #278: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #279: @3 = @3' */
  /* #280: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #281: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #282: @2 = @2' */
  /* #283: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #284: @2 = (@0*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #285: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #286: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #287: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #288: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #289: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #290: (@40[32:40] = @34) */
  for (rr=w40+32, ss=w34; rr!=w40+40; rr+=1) *rr = *ss++;
  /* #291: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #292: (@40[4:68:8] = @34) */
  for (rr=w40+4, ss=w34; rr!=w40+68; rr+=8) *rr = *ss++;
  /* #293: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #294: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #295: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #296: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #297: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #298: {NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #299: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #300: @5 = mac(@24,@8,@5) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s9, w5, casadi_s0, w, 0);
  /* #301: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #302: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #303: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #304: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #305: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #306: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #307: @2 = @2' */
  /* #308: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #309: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #310: @3 = @3' */
  /* #311: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #312: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #313: @5 = @5' */
  /* #314: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #315: @5 = (@0*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #316: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #317: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #318: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #319: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #320: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #321: (@40[40:48] = @34) */
  for (rr=w40+40, ss=w34; rr!=w40+48; rr+=1) *rr = *ss++;
  /* #322: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #323: (@40[5:69:8] = @34) */
  for (rr=w40+5, ss=w34; rr!=w40+69; rr+=8) *rr = *ss++;
  /* #324: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #325: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #326: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #327: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #328: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #329: {NULL, NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #330: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #331: @2 = mac(@24,@8,@2) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s10, w2, casadi_s0, w, 0);
  /* #332: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #333: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #334: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #335: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #336: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #337: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #338: @5 = @5' */
  /* #339: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #340: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #341: @3 = @3' */
  /* #342: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #343: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #344: @2 = @2' */
  /* #345: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #346: @2 = (@0*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #347: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #348: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #349: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #350: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #351: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #352: (@40[48:56] = @34) */
  for (rr=w40+48, ss=w34; rr!=w40+56; rr+=1) *rr = *ss++;
  /* #353: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #354: (@40[6:70:8] = @34) */
  for (rr=w40+6, ss=w34; rr!=w40+70; rr+=8) *rr = *ss++;
  /* #355: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #356: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #357: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #358: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #359: @8 = ones(14x1,1nz) */
  w8 = 1.;
  /* #360: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w10 = w8;
  /* #361: @8 = @10[0] */
  for (rr=(&w8), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #362: @5 = mac(@24,@8,@5) */
  casadi_mtimes(w24, casadi_s2, (&w8), casadi_s11, w5, casadi_s0, w, 0);
  /* #363: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #364: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #365: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #366: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #367: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #368: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #369: @2 = @2' */
  /* #370: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #371: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #372: @3 = @3' */
  /* #373: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #374: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #375: @5 = @5' */
  /* #376: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #377: @5 = (@0*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #378: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #379: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #380: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #381: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #382: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #383: (@40[56:64] = @34) */
  for (rr=w40+56, ss=w34; rr!=w40+64; rr+=1) *rr = *ss++;
  /* #384: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #385: (@40[7:71:8] = @34) */
  for (rr=w40+7, ss=w34; rr!=w40+71; rr+=8) *rr = *ss++;
  /* #386: @49 = @40' */
  casadi_trans(w40,casadi_s12, w49, casadi_s12, iw);
  /* #387: output[2][0] = @49 */
  casadi_copy(w49, 70, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s14;
    case 3: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s13;
    case 2: return casadi_s12;
    case 3: return casadi_s14;
    case 4: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 19;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 661;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
