/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s4[5] = {8, 1, 0, 1, 0};
static const casadi_int casadi_s5[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[18] = {0, 1, 2, 3, 16, 17, 18, 19, 20, 21, 22, 23, 80, 81, 82, 83, 84, 85};
static const casadi_int casadi_s7[18] = {0, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 81, 82, 83, 84, 85};
static const casadi_int casadi_s8[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s9[5] = {8, 1, 0, 1, 1};
static const casadi_int casadi_s10[12] = {4, 5, 6, 7, 24, 25, 26, 27, 28, 29, 30, 31};
static const casadi_int casadi_s11[12] = {1, 5, 9, 13, 17, 25, 33, 41, 49, 57, 65, 73};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[5] = {8, 1, 0, 1, 2};
static const casadi_int casadi_s14[12] = {8, 9, 10, 11, 32, 33, 34, 35, 36, 37, 38, 39};
static const casadi_int casadi_s15[12] = {2, 6, 10, 14, 18, 26, 34, 42, 50, 58, 66, 74};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[5] = {8, 1, 0, 1, 3};
static const casadi_int casadi_s18[12] = {12, 13, 14, 15, 40, 41, 42, 43, 44, 45, 46, 47};
static const casadi_int casadi_s19[12] = {3, 7, 11, 15, 19, 27, 35, 43, 51, 59, 67, 75};
static const casadi_int casadi_s20[5] = {8, 1, 0, 1, 4};
static const casadi_int casadi_s21[5] = {8, 1, 0, 1, 5};
static const casadi_int casadi_s22[5] = {8, 1, 0, 1, 6};
static const casadi_int casadi_s23[5] = {8, 1, 0, 1, 7};
static const casadi_int casadi_s24[107] = {18, 18, 0, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 81, 82, 83, 84, 85, 86, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s25[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s26[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s27[3] = {0, 0, 0};
static const casadi_int casadi_s28[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s29[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s30[21] = {0, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[8] = {1., 0., 0., 0., 0., 0., 0., 0.};
static const casadi_real casadi_c1[64] = {1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c2[16] = {6.7114093959731547e-01, 0., 0., 0., 0., 600., 0., 0., 0., 0., 600., 0., 0., 0., 0., 600.};

/* quadrotor_cost_ext_cost_0_fun_jac_hess:(i0[14],i1[4],i2[],i3[18])->(o0,o1[18],o2[18x18,86nz],o3[],o4[0x18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, *w2=w+10, *w3=w+18, w4, *w5=w+27, *w6=w+35, w7, w8, w9, w10, *w11=w+57, w12, w13, *w14=w+63, *w15=w+67, *w16=w+71, *w17=w+75, *w18=w+91, *w19=w+107, *w20=w+139, *w21=w+171, *w22=w+187, *w23=w+219, *w24=w+283, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+355, *w34=w+369, *w35=w+377, *w36=w+441, *w37=w+444, *w38=w+447, *w39=w+450, w40, w41, *w42=w+516, *w50=w+602, w51, w52, w53, w54, *w55=w+613, *w56=w+615, *w57=w+627;
  /* #0: @0 = 10 */
  w0 = 10.;
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #3: @3 = [1, 0, 0, 0, 0, 0, 0, 0] */
  casadi_copy(casadi_c0, 8, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #6: @6 = input[3][0] */
  casadi_copy(arg[3], 18, w6);
  /* #7: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #8: @8 = @6[1] */
  for (rr=(&w8), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #9: @9 = @6[2] */
  for (rr=(&w9), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #10: @10 = @6[3] */
  for (rr=(&w10), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w7 = (- w8 );
  /* #14: @12 = @6[0] */
  for (rr=(&w12), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #15: @13 = (-@9) */
  w13 = (- w9 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  for (rr=(&w12), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w8;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  for (rr=(&w13), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  for (rr=(&w10), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #31: @9 = @6[5] */
  for (rr=(&w9), ss=w6+5; ss!=w6+6; ss+=1) *rr++ = *ss;
  /* #32: @7 = @6[6] */
  for (rr=(&w7), ss=w6+6; ss!=w6+7; ss+=1) *rr++ = *ss;
  /* #33: @13 = @6[7] */
  for (rr=(&w13), ss=w6+7; ss!=w6+8; ss+=1) *rr++ = *ss;
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w9 );
  /* #37: @12 = @6[4] */
  for (rr=(&w12), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #38: @8 = (-@7) */
  w8 = (- w7 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w8;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  for (rr=(&w12), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w9;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  for (rr=(&w8), ss=w6+4; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w7 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #69: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #70: @5 = mac(@24,@34,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w24+j, tt=w34+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #71: @13 = @5[0] */
  for (rr=(&w13), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #72: @4 = (@4<@13) */
  w4  = (w4<w13);
  /* #73: @34 = (@4?@5:0) */
  for (i=0, rr=w34, cs=w5; i<8; ++i) (*rr++)  = (w4?(*cs++):0);
  /* #74: @13 = (!@4) */
  w13 = (! w4 );
  /* #75: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) *rr++ = (- *cs++ );
  /* #76: @5 = (@13?@5:0) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #77: @34 = (@34+@5) */
  for (i=0, rr=w34, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #78: @3 = (@3-@34) */
  for (i=0, rr=w3, cs=w34; i<8; ++i) (*rr++) -= (*cs++);
  /* #79: @34 = @3' */
  casadi_copy(w3, 8, w34);
  /* #80: @35 = 
  [[1, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 64, w35);
  /* #81: @2 = mac(@34,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #82: @1 = mac(@2,@3,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0*@1) */
  w0 *= w1;
  /* #84: @1 = 0 */
  w1 = 0.;
  /* #85: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #86: @14 = @6[14:18] */
  for (rr=w14, ss=w6+14; ss!=w6+18; ss+=1) *rr++ = *ss;
  /* #87: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #88: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #89: @8 = input[1][2] */
  w8 = arg[1] ? arg[1][2] : 0;
  /* #90: @12 = input[1][3] */
  w12 = arg[1] ? arg[1][3] : 0;
  /* #91: @15 = vertcat(@7, @10, @8, @12) */
  rr=w15;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w12;
  /* #92: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<4; ++i) (*rr++) -= (*cs++);
  /* #93: @15 = @14' */
  casadi_copy(w14, 4, w15);
  /* #94: @21 = 
  [[0.671141, 0, 0, 0], 
   [0, 600, 0, 0], 
   [0, 0, 600, 0], 
   [0, 0, 0, 600]] */
  casadi_copy(casadi_c2, 16, w21);
  /* #95: @11 = mac(@15,@21,@11) */
  for (i=0, rr=w11; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #96: @1 = mac(@11,@14,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w11+j, tt=w14+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #97: @0 = (@0+@1) */
  w0 += w1;
  /* #98: @1 = 0 */
  w1 = 0.;
  /* #99: @36 = @33[8:11] */
  for (rr=w36, ss=w33+8; ss!=w33+11; ss+=1) *rr++ = *ss;
  /* #100: @37 = @36' */
  casadi_copy(w36, 3, w37);
  /* #101: @1 = mac(@37,@36,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #102: @0 = (@0+@1) */
  w0 += w1;
  /* #103: @1 = 0 */
  w1 = 0.;
  /* #104: @37 = @33[11:14] */
  for (rr=w37, ss=w33+11; ss!=w33+14; ss+=1) *rr++ = *ss;
  /* #105: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #106: @1 = mac(@38,@37,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #107: @0 = (@0+@1) */
  w0 += w1;
  /* #108: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #109: @11 = @11' */
  /* #110: @15 = zeros(1x4) */
  casadi_clear(w15, 4);
  /* #111: @14 = @14' */
  /* #112: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #113: @15 = mac(@14,@18,@15) */
  for (i=0, rr=w15; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #114: @15 = @15' */
  /* #115: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #116: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #117: {@0, @1, @7, @10} = vertsplit(@11) */
  w0 = w11[0];
  w1 = w11[1];
  w7 = w11[2];
  w10 = w11[3];
  /* #118: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #119: output[1][1] = @1 */
  if (res[1]) res[1][1] = w1;
  /* #120: output[1][2] = @7 */
  if (res[1]) res[1][2] = w7;
  /* #121: output[1][3] = @10 */
  if (res[1]) res[1][3] = w10;
  /* #122: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #123: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #124: (@33[11:14] += @37) */
  for (rr=w33+11, ss=w37; rr!=w33+14; rr+=1) *rr += *ss++;
  /* #125: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #126: (@33[8:11] += @36) */
  for (rr=w33+8, ss=w36; rr!=w33+11; rr+=1) *rr += *ss++;
  /* #127: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #128: @10 = 1 */
  w10 = 1.;
  /* #129: @10 = (@13?@10:0) */
  w10  = (w13?w10:0);
  /* #130: @7 = 10 */
  w7 = 10.;
  /* #131: @2 = @2' */
  /* #132: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #133: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #134: @3 = @3' */
  /* #135: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #136: @39 = @35' */
  for (i=0, rr=w39, cs=w35; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #137: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #138: @5 = @5' */
  /* #139: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #140: @5 = (@10*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #141: @1 = 1 */
  w1 = 1.;
  /* #142: @1 = (@4?@1:0) */
  w1  = (w4?w1:0);
  /* #143: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #144: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #145: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #146: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #147: {@0, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32, @40, @41} = vertsplit(@33) */
  w0 = w33[0];
  w8 = w33[1];
  w12 = w33[2];
  w9 = w33[3];
  w25 = w33[4];
  w26 = w33[5];
  w27 = w33[6];
  w28 = w33[7];
  w29 = w33[8];
  w30 = w33[9];
  w31 = w33[10];
  w32 = w33[11];
  w40 = w33[12];
  w41 = w33[13];
  /* #148: output[1][4] = @0 */
  if (res[1]) res[1][4] = w0;
  /* #149: output[1][5] = @8 */
  if (res[1]) res[1][5] = w8;
  /* #150: output[1][6] = @12 */
  if (res[1]) res[1][6] = w12;
  /* #151: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #152: output[1][8] = @25 */
  if (res[1]) res[1][8] = w25;
  /* #153: output[1][9] = @26 */
  if (res[1]) res[1][9] = w26;
  /* #154: output[1][10] = @27 */
  if (res[1]) res[1][10] = w27;
  /* #155: output[1][11] = @28 */
  if (res[1]) res[1][11] = w28;
  /* #156: output[1][12] = @29 */
  if (res[1]) res[1][12] = w29;
  /* #157: output[1][13] = @30 */
  if (res[1]) res[1][13] = w30;
  /* #158: output[1][14] = @31 */
  if (res[1]) res[1][14] = w31;
  /* #159: output[1][15] = @32 */
  if (res[1]) res[1][15] = w32;
  /* #160: output[1][16] = @40 */
  if (res[1]) res[1][16] = w40;
  /* #161: output[1][17] = @41 */
  if (res[1]) res[1][17] = w41;
  /* #162: @42 = zeros(18x18,86nz) */
  casadi_clear(w42, 86);
  /* #163: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #164: @34 = ones(18x1,8nz) */
  casadi_fill(w34, 8, 1.);
  /* #165: {@41, NULL, NULL, NULL, @40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @32, @31, @30, @29, @28, @27} = vertsplit(@34) */
  w41 = w34[0];
  w40 = w34[1];
  w32 = w34[2];
  w31 = w34[3];
  w30 = w34[4];
  w29 = w34[5];
  w28 = w34[6];
  w27 = w34[7];
  /* #166: @43 = 00 */
  /* #167: @44 = 00 */
  /* #168: @45 = 00 */
  /* #169: @26 = vertcat(@41, @43, @44, @45) */
  rr=(&w26);
  *rr++ = w41;
  /* #170: @26 = (-@26) */
  w26 = (- w26 );
  /* #171: @41 = @26' */
  casadi_copy((&w26), 1, (&w41));
  /* #172: @11 = mac(@41,@21,@11) */
  casadi_mtimes((&w41), casadi_s2, w21, casadi_s1, w11, casadi_s0, w, 0);
  /* #173: @11 = @11' */
  /* #174: @15 = zeros(1x4) */
  casadi_clear(w15, 4);
  /* #175: @26 = @26' */
  /* #176: @15 = mac(@26,@18,@15) */
  casadi_mtimes((&w26), casadi_s2, w18, casadi_s1, w15, casadi_s0, w, 0);
  /* #177: @15 = @15' */
  /* #178: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #179: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #180: {@26, @41, @25, @9} = vertsplit(@11) */
  w26 = w11[0];
  w41 = w11[1];
  w25 = w11[2];
  w9 = w11[3];
  /* #181: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #182: @43 = 00 */
  /* #183: @44 = 00 */
  /* #184: @45 = 00 */
  /* #185: @46 = 00 */
  /* #186: @47 = 00 */
  /* #187: @48 = 00 */
  /* #188: @49 = 00 */
  /* #189: @50 = vertcat(@40, @43, @44, @45, @46, @47, @48, @49, @32, @31, @30, @29, @28, @27) */
  rr=w50;
  *rr++ = w40;
  *rr++ = w32;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  /* #190: @36 = @50[4:7] */
  for (rr=w36, ss=w50+4; ss!=w50+7; ss+=1) *rr++ = *ss;
  /* #191: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #192: (@33[11:14] += @36) */
  for (rr=w33+11, ss=w36; rr!=w33+14; rr+=1) *rr += *ss++;
  /* #193: @36 = @50[1:4] */
  for (rr=w36, ss=w50+1; ss!=w50+4; ss+=1) *rr++ = *ss;
  /* #194: @36 = (2.*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #195: (@33[8:11] += @36) */
  for (rr=w33+8, ss=w36; rr!=w33+11; rr+=1) *rr += *ss++;
  /* #196: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #197: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #198: @32 = 1 */
  w32 = 1.;
  /* #199: @4 = (@4?@32:0) */
  w4  = (w4?w32:0);
  /* #200: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #201: @32 = @40[0] */
  for (rr=(&w32), ss=(&w40)+0; ss!=(&w40)+1; ss+=1) *rr++ = *ss;
  /* #202: @2 = mac(@24,@32,@2) */
  casadi_mtimes(w24, casadi_s5, (&w32), casadi_s4, w2, casadi_s3, w, 0);
  /* #203: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #204: @32 = 1 */
  w32 = 1.;
  /* #205: @13 = (@13?@32:0) */
  w13  = (w13?w32:0);
  /* #206: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #207: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #208: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #209: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #210: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #211: @5 = @5' */
  /* #212: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #213: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #214: @3 = @3' */
  /* #215: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #216: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #217: @2 = @2' */
  /* #218: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #219: @2 = (@10*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #220: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #221: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #222: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #223: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #224: {@32, @40, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54} = vertsplit(@33) */
  w32 = w33[0];
  w40 = w33[1];
  w31 = w33[2];
  w30 = w33[3];
  w29 = w33[4];
  w28 = w33[5];
  w27 = w33[6];
  w12 = w33[7];
  w8 = w33[8];
  w0 = w33[9];
  w51 = w33[10];
  w52 = w33[11];
  w53 = w33[12];
  w54 = w33[13];
  /* #225: @6 = vertcat(@26, @41, @25, @9, @32, @40, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54) */
  rr=w6;
  *rr++ = w26;
  *rr++ = w41;
  *rr++ = w25;
  *rr++ = w9;
  *rr++ = w32;
  *rr++ = w40;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  /* #226: (@42[0, 1, 2, 3, 16, 17, 18, 19, 20, 21, 22, 23, 80, 81, 82, 83, 84, 85] = @6) */
  for (cii=casadi_s6, rr=w42, ss=w6; cii!=casadi_s6+18; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #227: (@42[0, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 81, 82, 83, 84, 85] = @6) */
  for (cii=casadi_s7, rr=w42, ss=w6; cii!=casadi_s7+18; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #228: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #229: @43 = 00 */
  /* #230: @55 = ones(18x1,2nz) */
  casadi_fill(w55, 2, 1.);
  /* #231: {NULL, @26, NULL, NULL, NULL, @41, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@55) */
  w26 = w55[0];
  w41 = w55[1];
  /* #232: @44 = 00 */
  /* #233: @45 = 00 */
  /* #234: @25 = vertcat(@43, @26, @44, @45) */
  rr=(&w25);
  *rr++ = w26;
  /* #235: @25 = (-@25) */
  w25 = (- w25 );
  /* #236: @26 = @25' */
  casadi_copy((&w25), 1, (&w26));
  /* #237: @11 = mac(@26,@21,@11) */
  casadi_mtimes((&w26), casadi_s8, w21, casadi_s1, w11, casadi_s0, w, 0);
  /* #238: @11 = @11' */
  /* #239: @15 = zeros(1x4) */
  casadi_clear(w15, 4);
  /* #240: @25 = @25' */
  /* #241: @15 = mac(@25,@18,@15) */
  casadi_mtimes((&w25), casadi_s8, w18, casadi_s1, w15, casadi_s0, w, 0);
  /* #242: @15 = @15' */
  /* #243: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #244: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #245: {@25, @26, @9, @32} = vertsplit(@11) */
  w25 = w11[0];
  w26 = w11[1];
  w9 = w11[2];
  w32 = w11[3];
  /* #246: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #247: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #248: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #249: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #250: @40 = @41[0] */
  for (rr=(&w40), ss=(&w41)+0; ss!=(&w41)+1; ss+=1) *rr++ = *ss;
  /* #251: @5 = mac(@24,@40,@5) */
  casadi_mtimes(w24, casadi_s5, (&w40), casadi_s9, w5, casadi_s3, w, 0);
  /* #252: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #253: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #254: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #255: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #256: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #257: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #258: @2 = @2' */
  /* #259: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #260: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #261: @3 = @3' */
  /* #262: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #263: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #264: @5 = @5' */
  /* #265: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #266: @5 = (@10*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #267: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #268: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #269: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #270: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #271: {@40, @41, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54} = vertsplit(@33) */
  w40 = w33[0];
  w41 = w33[1];
  w31 = w33[2];
  w30 = w33[3];
  w29 = w33[4];
  w28 = w33[5];
  w27 = w33[6];
  w12 = w33[7];
  w8 = w33[8];
  w0 = w33[9];
  w51 = w33[10];
  w52 = w33[11];
  w53 = w33[12];
  w54 = w33[13];
  /* #272: @6 = vertcat(@25, @26, @9, @32, @40, @41, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54) */
  rr=w6;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w9;
  *rr++ = w32;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  /* #273: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #274: (@42[4, 5, 6, 7, 24, 25, 26, 27, 28, 29, 30, 31] = @56) */
  for (cii=casadi_s10, rr=w42, ss=w56; cii!=casadi_s10+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #275: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #276: (@42[1, 5, 9, 13, 17, 25, 33, 41, 49, 57, 65, 73] = @56) */
  for (cii=casadi_s11, rr=w42, ss=w56; cii!=casadi_s11+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #277: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #278: @43 = 00 */
  /* #279: @44 = 00 */
  /* #280: @55 = ones(18x1,2nz) */
  casadi_fill(w55, 2, 1.);
  /* #281: {NULL, NULL, @25, NULL, NULL, NULL, @26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@55) */
  w25 = w55[0];
  w26 = w55[1];
  /* #282: @45 = 00 */
  /* #283: @9 = vertcat(@43, @44, @25, @45) */
  rr=(&w9);
  *rr++ = w25;
  /* #284: @9 = (-@9) */
  w9 = (- w9 );
  /* #285: @25 = @9' */
  casadi_copy((&w9), 1, (&w25));
  /* #286: @11 = mac(@25,@21,@11) */
  casadi_mtimes((&w25), casadi_s12, w21, casadi_s1, w11, casadi_s0, w, 0);
  /* #287: @11 = @11' */
  /* #288: @15 = zeros(1x4) */
  casadi_clear(w15, 4);
  /* #289: @9 = @9' */
  /* #290: @15 = mac(@9,@18,@15) */
  casadi_mtimes((&w9), casadi_s12, w18, casadi_s1, w15, casadi_s0, w, 0);
  /* #291: @15 = @15' */
  /* #292: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #293: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #294: {@9, @25, @32, @40} = vertsplit(@11) */
  w9 = w11[0];
  w25 = w11[1];
  w32 = w11[2];
  w40 = w11[3];
  /* #295: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #296: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #297: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #298: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #299: @41 = @26[0] */
  for (rr=(&w41), ss=(&w26)+0; ss!=(&w26)+1; ss+=1) *rr++ = *ss;
  /* #300: @2 = mac(@24,@41,@2) */
  casadi_mtimes(w24, casadi_s5, (&w41), casadi_s13, w2, casadi_s3, w, 0);
  /* #301: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #302: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #303: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #304: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #305: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #306: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #307: @5 = @5' */
  /* #308: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #309: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #310: @3 = @3' */
  /* #311: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #312: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #313: @2 = @2' */
  /* #314: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #315: @2 = (@10*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #316: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #317: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #318: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #319: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #320: {@41, @26, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54} = vertsplit(@33) */
  w41 = w33[0];
  w26 = w33[1];
  w31 = w33[2];
  w30 = w33[3];
  w29 = w33[4];
  w28 = w33[5];
  w27 = w33[6];
  w12 = w33[7];
  w8 = w33[8];
  w0 = w33[9];
  w51 = w33[10];
  w52 = w33[11];
  w53 = w33[12];
  w54 = w33[13];
  /* #321: @6 = vertcat(@9, @25, @32, @40, @41, @26, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54) */
  rr=w6;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w32;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  /* #322: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #323: (@42[8, 9, 10, 11, 32, 33, 34, 35, 36, 37, 38, 39] = @56) */
  for (cii=casadi_s14, rr=w42, ss=w56; cii!=casadi_s14+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #324: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #325: (@42[2, 6, 10, 14, 18, 26, 34, 42, 50, 58, 66, 74] = @56) */
  for (cii=casadi_s15, rr=w42, ss=w56; cii!=casadi_s15+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #326: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #327: @43 = 00 */
  /* #328: @44 = 00 */
  /* #329: @45 = 00 */
  /* #330: @55 = ones(18x1,2nz) */
  casadi_fill(w55, 2, 1.);
  /* #331: {NULL, NULL, NULL, @9, NULL, NULL, NULL, @25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@55) */
  w9 = w55[0];
  w25 = w55[1];
  /* #332: @32 = vertcat(@43, @44, @45, @9) */
  rr=(&w32);
  *rr++ = w9;
  /* #333: @32 = (-@32) */
  w32 = (- w32 );
  /* #334: @9 = @32' */
  casadi_copy((&w32), 1, (&w9));
  /* #335: @11 = mac(@9,@21,@11) */
  casadi_mtimes((&w9), casadi_s16, w21, casadi_s1, w11, casadi_s0, w, 0);
  /* #336: @11 = @11' */
  /* #337: @15 = zeros(1x4) */
  casadi_clear(w15, 4);
  /* #338: @32 = @32' */
  /* #339: @15 = mac(@32,@18,@15) */
  casadi_mtimes((&w32), casadi_s16, w18, casadi_s1, w15, casadi_s0, w, 0);
  /* #340: @15 = @15' */
  /* #341: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #342: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #343: {@32, @9, @40, @41} = vertsplit(@11) */
  w32 = w11[0];
  w9 = w11[1];
  w40 = w11[2];
  w41 = w11[3];
  /* #344: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #345: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #346: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #347: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #348: @26 = @25[0] */
  for (rr=(&w26), ss=(&w25)+0; ss!=(&w25)+1; ss+=1) *rr++ = *ss;
  /* #349: @5 = mac(@24,@26,@5) */
  casadi_mtimes(w24, casadi_s5, (&w26), casadi_s17, w5, casadi_s3, w, 0);
  /* #350: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #351: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #352: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #353: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #354: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #355: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #356: @2 = @2' */
  /* #357: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #358: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #359: @3 = @3' */
  /* #360: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #361: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #362: @5 = @5' */
  /* #363: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #364: @5 = (@10*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #365: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #366: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #367: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #368: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #369: {@26, @25, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54} = vertsplit(@33) */
  w26 = w33[0];
  w25 = w33[1];
  w31 = w33[2];
  w30 = w33[3];
  w29 = w33[4];
  w28 = w33[5];
  w27 = w33[6];
  w12 = w33[7];
  w8 = w33[8];
  w0 = w33[9];
  w51 = w33[10];
  w52 = w33[11];
  w53 = w33[12];
  w54 = w33[13];
  /* #370: @6 = vertcat(@32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0, @51, @52, @53, @54) */
  rr=w6;
  *rr++ = w32;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  /* #371: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #372: (@42[12, 13, 14, 15, 40, 41, 42, 43, 44, 45, 46, 47] = @56) */
  for (cii=casadi_s18, rr=w42, ss=w56; cii!=casadi_s18+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #373: @56 = @6[:12] */
  for (rr=w56, ss=w6+0; ss!=w6+12; ss+=1) *rr++ = *ss;
  /* #374: (@42[3, 7, 11, 15, 19, 27, 35, 43, 51, 59, 67, 75] = @56) */
  for (cii=casadi_s19, rr=w42, ss=w56; cii!=casadi_s19+12; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #375: @43 = 00 */
  /* #376: @44 = 00 */
  /* #377: @45 = 00 */
  /* #378: @46 = 00 */
  /* #379: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #380: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #381: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #382: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #383: @32 = ones(18x1,1nz) */
  w32 = 1.;
  /* #384: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w9 = w32;
  /* #385: @32 = @9[0] */
  for (rr=(&w32), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #386: @2 = mac(@24,@32,@2) */
  casadi_mtimes(w24, casadi_s5, (&w32), casadi_s20, w2, casadi_s3, w, 0);
  /* #387: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #388: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #389: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #390: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #391: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #392: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #393: @5 = @5' */
  /* #394: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #395: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #396: @3 = @3' */
  /* #397: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #398: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #399: @2 = @2' */
  /* #400: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #401: @2 = (@10*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #402: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #403: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #404: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #405: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #406: {@32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0} = vertsplit(@33) */
  w32 = w33[0];
  w9 = w33[1];
  w40 = w33[2];
  w41 = w33[3];
  w26 = w33[4];
  w25 = w33[5];
  w31 = w33[6];
  w30 = w33[7];
  w29 = w33[8];
  w28 = w33[9];
  w27 = w33[10];
  w12 = w33[11];
  w8 = w33[12];
  w0 = w33[13];
  /* #407: @33 = vertcat(@43, @44, @45, @46, @32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0) */
  rr=w33;
  *rr++ = w32;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  /* #408: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #409: (@42[48:56] = @34) */
  for (rr=w42+48, ss=w34; rr!=w42+56; rr+=1) *rr = *ss++;
  /* #410: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #411: (@42[20:84:8] = @34) */
  for (rr=w42+20, ss=w34; rr!=w42+84; rr+=8) *rr = *ss++;
  /* #412: @43 = 00 */
  /* #413: @44 = 00 */
  /* #414: @45 = 00 */
  /* #415: @46 = 00 */
  /* #416: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #417: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #418: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #419: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #420: @32 = ones(18x1,1nz) */
  w32 = 1.;
  /* #421: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w9 = w32;
  /* #422: @32 = @9[0] */
  for (rr=(&w32), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #423: @5 = mac(@24,@32,@5) */
  casadi_mtimes(w24, casadi_s5, (&w32), casadi_s21, w5, casadi_s3, w, 0);
  /* #424: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #425: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #426: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #427: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #428: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #429: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #430: @2 = @2' */
  /* #431: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #432: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #433: @3 = @3' */
  /* #434: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #435: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #436: @5 = @5' */
  /* #437: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #438: @5 = (@10*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #439: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #440: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #441: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #442: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #443: {@32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0} = vertsplit(@33) */
  w32 = w33[0];
  w9 = w33[1];
  w40 = w33[2];
  w41 = w33[3];
  w26 = w33[4];
  w25 = w33[5];
  w31 = w33[6];
  w30 = w33[7];
  w29 = w33[8];
  w28 = w33[9];
  w27 = w33[10];
  w12 = w33[11];
  w8 = w33[12];
  w0 = w33[13];
  /* #444: @33 = vertcat(@43, @44, @45, @46, @32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0) */
  rr=w33;
  *rr++ = w32;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  /* #445: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #446: (@42[56:64] = @34) */
  for (rr=w42+56, ss=w34; rr!=w42+64; rr+=1) *rr = *ss++;
  /* #447: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #448: (@42[21:85:8] = @34) */
  for (rr=w42+21, ss=w34; rr!=w42+85; rr+=8) *rr = *ss++;
  /* #449: @43 = 00 */
  /* #450: @44 = 00 */
  /* #451: @45 = 00 */
  /* #452: @46 = 00 */
  /* #453: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #454: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #455: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #456: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #457: @32 = ones(18x1,1nz) */
  w32 = 1.;
  /* #458: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w9 = w32;
  /* #459: @32 = @9[0] */
  for (rr=(&w32), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #460: @2 = mac(@24,@32,@2) */
  casadi_mtimes(w24, casadi_s5, (&w32), casadi_s22, w2, casadi_s3, w, 0);
  /* #461: @3 = (@4*@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #462: @2 = (@13*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #463: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #464: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #465: @2 = @3' */
  casadi_copy(w3, 8, w2);
  /* #466: @5 = mac(@2,@35,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #467: @5 = @5' */
  /* #468: @5 = (@7*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #469: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #470: @3 = @3' */
  /* #471: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #472: @2 = mac(@3,@39,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #473: @2 = @2' */
  /* #474: @5 = (@5+@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #475: @2 = (@10*@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #476: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #477: @2 = (@2-@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #478: @34 = mac(@23,@2,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w2+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #479: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #480: {@32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0} = vertsplit(@33) */
  w32 = w33[0];
  w9 = w33[1];
  w40 = w33[2];
  w41 = w33[3];
  w26 = w33[4];
  w25 = w33[5];
  w31 = w33[6];
  w30 = w33[7];
  w29 = w33[8];
  w28 = w33[9];
  w27 = w33[10];
  w12 = w33[11];
  w8 = w33[12];
  w0 = w33[13];
  /* #481: @33 = vertcat(@43, @44, @45, @46, @32, @9, @40, @41, @26, @25, @31, @30, @29, @28, @27, @12, @8, @0) */
  rr=w33;
  *rr++ = w32;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w27;
  *rr++ = w12;
  *rr++ = w8;
  *rr++ = w0;
  /* #482: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #483: (@42[64:72] = @34) */
  for (rr=w42+64, ss=w34; rr!=w42+72; rr+=1) *rr = *ss++;
  /* #484: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #485: (@42[22:86:8] = @34) */
  for (rr=w42+22, ss=w34; rr!=w42+86; rr+=8) *rr = *ss++;
  /* #486: @43 = 00 */
  /* #487: @44 = 00 */
  /* #488: @45 = 00 */
  /* #489: @46 = 00 */
  /* #490: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #491: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #492: @2 = zeros(1x8) */
  casadi_clear(w2, 8);
  /* #493: @5 = zeros(8x1) */
  casadi_clear(w5, 8);
  /* #494: @32 = ones(18x1,1nz) */
  w32 = 1.;
  /* #495: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w9 = w32;
  /* #496: @32 = @9[0] */
  for (rr=(&w32), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #497: @5 = mac(@24,@32,@5) */
  casadi_mtimes(w24, casadi_s5, (&w32), casadi_s23, w5, casadi_s3, w, 0);
  /* #498: @3 = (@4*@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #499: @5 = (@13*@5) */
  for (i=0, rr=w5, cs=w5; i<8; ++i) (*rr++)  = (w13*(*cs++));
  /* #500: @3 = (@3-@5) */
  for (i=0, rr=w3, cs=w5; i<8; ++i) (*rr++) -= (*cs++);
  /* #501: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) *rr++ = (- *cs++ );
  /* #502: @5 = @3' */
  casadi_copy(w3, 8, w5);
  /* #503: @2 = mac(@5,@35,@2) */
  for (i=0, rr=w2; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #504: @2 = @2' */
  /* #505: @2 = (@7*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #506: @5 = zeros(1x8) */
  casadi_clear(w5, 8);
  /* #507: @3 = @3' */
  /* #508: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<8; ++i) (*rr++)  = (w7*(*cs++));
  /* #509: @5 = mac(@3,@39,@5) */
  for (i=0, rr=w5; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w39+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #510: @5 = @5' */
  /* #511: @2 = (@2+@5) */
  for (i=0, rr=w2, cs=w5; i<8; ++i) (*rr++) += (*cs++);
  /* #512: @5 = (@10*@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++)  = (w10*(*cs++));
  /* #513: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<8; ++i) (*rr++)  = (w1*(*cs++));
  /* #514: @5 = (@5-@2) */
  for (i=0, rr=w5, cs=w2; i<8; ++i) (*rr++) -= (*cs++);
  /* #515: @34 = mac(@23,@5,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w23+j, tt=w5+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #516: (@33[:8] += @34) */
  for (rr=w33+0, ss=w34; rr!=w33+8; rr+=1) *rr += *ss++;
  /* #517: {@1, @10, @7, @13, @4, @32, @9, @40, @41, @26, @25, @31, @30, @29} = vertsplit(@33) */
  w1 = w33[0];
  w10 = w33[1];
  w7 = w33[2];
  w13 = w33[3];
  w4 = w33[4];
  w32 = w33[5];
  w9 = w33[6];
  w40 = w33[7];
  w41 = w33[8];
  w26 = w33[9];
  w25 = w33[10];
  w31 = w33[11];
  w30 = w33[12];
  w29 = w33[13];
  /* #518: @33 = vertcat(@43, @44, @45, @46, @1, @10, @7, @13, @4, @32, @9, @40, @41, @26, @25, @31, @30, @29) */
  rr=w33;
  *rr++ = w1;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w13;
  *rr++ = w4;
  *rr++ = w32;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w26;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w29;
  /* #519: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #520: (@42[72:80] = @34) */
  for (rr=w42+72, ss=w34; rr!=w42+80; rr+=1) *rr = *ss++;
  /* #521: @34 = @33[:8] */
  for (rr=w34, ss=w33+0; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #522: (@42[23:87:8] = @34) */
  for (rr=w42+23, ss=w34; rr!=w42+87; rr+=8) *rr = *ss++;
  /* #523: @57 = @42' */
  casadi_trans(w42,casadi_s24, w57, casadi_s24, iw);
  /* #524: output[2][0] = @57 */
  casadi_copy(w57, 86, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s25;
    case 1: return casadi_s26;
    case 2: return casadi_s27;
    case 3: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s29;
    case 1: return casadi_s28;
    case 2: return casadi_s24;
    case 3: return casadi_s27;
    case 4: return casadi_s30;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 19;
  if (sz_w) *sz_w = 713;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
